---bd_mon租户脚本---
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='CZ',month='201612');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='CZ',month='201612');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='CZ',month='201701');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='CZ',month='201701');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='CZ',month='201702');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='CZ',month='201702');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='CZ',month='201703');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='CZ',month='201703');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='CZ',month='201704');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='CZ',month='201704');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='CZ',month='201705');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='CZ',month='201705');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='CZ',month='201706');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='CZ',month='201706');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='CZ',month='201707');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='CZ',month='201707');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='DG',month='201612');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='DG',month='201612');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='DG',month='201701');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='DG',month='201701');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='DG',month='201702');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='DG',month='201702');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='DG',month='201703');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='DG',month='201703');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='DG',month='201704');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='DG',month='201704');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='DG',month='201705');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='DG',month='201705');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='DG',month='201706');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='DG',month='201706');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='DG',month='201707');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='DG',month='201707');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='FS',month='201612');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='FS',month='201612');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='FS',month='201701');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='FS',month='201701');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='FS',month='201702');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='FS',month='201702');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='FS',month='201703');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='FS',month='201703');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='FS',month='201704');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='FS',month='201704');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='FS',month='201705');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='FS',month='201705');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='FS',month='201706');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='FS',month='201706');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='FS',month='201707');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='FS',month='201707');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='GZ',month='201607');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='GZ',month='201607');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='GZ',month='201612');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='GZ',month='201612');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='GZ',month='201701');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='GZ',month='201701');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='GZ',month='201702');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='GZ',month='201702');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='GZ',month='201703');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='GZ',month='201703');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='GZ',month='201704');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='GZ',month='201704');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='GZ',month='201705');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='GZ',month='201705');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='GZ',month='201706');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='GZ',month='201706');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='GZ',month='201707');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='GZ',month='201707');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='HY',month='201612');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='HY',month='201612');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='HY',month='201701');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='HY',month='201701');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='HY',month='201702');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='HY',month='201702');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='HY',month='201703');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='HY',month='201703');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='HY',month='201704');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='HY',month='201704');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='HY',month='201705');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='HY',month='201705');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='HY',month='201706');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='HY',month='201706');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='HY',month='201707');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='HY',month='201707');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='HZ',month='201612');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='HZ',month='201612');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='HZ',month='201701');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='HZ',month='201701');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='HZ',month='201702');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='HZ',month='201702');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='HZ',month='201703');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='HZ',month='201703');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='HZ',month='201704');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='HZ',month='201704');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='HZ',month='201705');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='HZ',month='201705');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='HZ',month='201706');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='HZ',month='201706');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='HZ',month='201707');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='HZ',month='201707');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='JM',month='201612');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='JM',month='201612');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='JM',month='201701');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='JM',month='201701');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='JM',month='201702');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='JM',month='201702');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='JM',month='201703');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='JM',month='201703');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='JM',month='201704');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='JM',month='201704');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='JM',month='201705');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='JM',month='201705');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='JM',month='201706');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='JM',month='201706');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='JM',month='201707');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='JM',month='201707');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='JY',month='201612');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='JY',month='201612');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='JY',month='201701');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='JY',month='201701');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='JY',month='201702');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='JY',month='201702');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='JY',month='201703');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='JY',month='201703');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='JY',month='201704');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='JY',month='201704');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='JY',month='201705');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='JY',month='201705');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='JY',month='201706');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='JY',month='201706');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='JY',month='201707');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='JY',month='201707');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='MM',month='201612');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='MM',month='201612');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='MM',month='201701');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='MM',month='201701');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='MM',month='201702');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='MM',month='201702');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='MM',month='201703');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='MM',month='201703');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='MM',month='201704');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='MM',month='201704');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='MM',month='201705');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='MM',month='201705');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='MM',month='201706');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='MM',month='201706');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='MM',month='201707');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='MM',month='201707');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='MZ',month='201612');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='MZ',month='201612');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='MZ',month='201701');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='MZ',month='201701');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='MZ',month='201702');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='MZ',month='201702');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='MZ',month='201703');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='MZ',month='201703');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='MZ',month='201704');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='MZ',month='201704');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='MZ',month='201705');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='MZ',month='201705');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='MZ',month='201706');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='MZ',month='201706');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='MZ',month='201707');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='MZ',month='201707');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='QY',month='201612');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='QY',month='201612');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='QY',month='201701');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='QY',month='201701');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='QY',month='201702');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='QY',month='201702');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='QY',month='201703');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='QY',month='201703');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='QY',month='201704');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='QY',month='201704');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='QY',month='201705');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='QY',month='201705');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='QY',month='201706');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='QY',month='201706');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='QY',month='201707');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='QY',month='201707');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='SG',month='201612');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='SG',month='201612');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='SG',month='201701');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='SG',month='201701');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='SG',month='201702');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='SG',month='201702');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='SG',month='201703');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='SG',month='201703');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='SG',month='201704');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='SG',month='201704');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='SG',month='201705');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='SG',month='201705');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='SG',month='201706');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='SG',month='201706');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='SG',month='201707');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='SG',month='201707');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='ST',month='201612');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='ST',month='201612');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='ST',month='201701');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='ST',month='201701');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='ST',month='201702');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='ST',month='201702');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='ST',month='201703');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='ST',month='201703');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='ST',month='201704');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='ST',month='201704');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='ST',month='201705');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='ST',month='201705');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='ST',month='201706');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='ST',month='201706');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='ST',month='201707');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='ST',month='201707');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='SW',month='201612');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='SW',month='201612');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='SW',month='201701');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='SW',month='201701');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='SW',month='201702');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='SW',month='201702');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='SW',month='201703');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='SW',month='201703');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='SW',month='201704');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='SW',month='201704');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='SW',month='201705');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='SW',month='201705');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='SW',month='201706');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='SW',month='201706');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='SW',month='201707');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='SW',month='201707');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='SZ',month='201612');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='SZ',month='201612');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='SZ',month='201701');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='SZ',month='201701');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='SZ',month='201702');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='SZ',month='201702');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='SZ',month='201703');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='SZ',month='201703');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='SZ',month='201704');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='SZ',month='201704');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='SZ',month='201705');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='SZ',month='201705');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='SZ',month='201706');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='SZ',month='201706');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='SZ',month='201707');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='SZ',month='201707');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='YF',month='201612');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='YF',month='201612');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='YF',month='201701');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='YF',month='201701');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='YF',month='201702');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='YF',month='201702');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='YF',month='201703');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='YF',month='201703');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='YF',month='201704');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='YF',month='201704');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='YF',month='201705');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='YF',month='201705');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='YF',month='201706');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='YF',month='201706');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='YF',month='201707');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='YF',month='201707');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='YJ',month='201612');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='YJ',month='201612');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='YJ',month='201701');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='YJ',month='201701');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='YJ',month='201702');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='YJ',month='201702');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='YJ',month='201703');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='YJ',month='201703');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='YJ',month='201704');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='YJ',month='201704');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='YJ',month='201705');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='YJ',month='201705');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='YJ',month='201706');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='YJ',month='201706');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='YJ',month='201707');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='YJ',month='201707');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='ZH',month='201612');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='ZH',month='201612');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='ZH',month='201701');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='ZH',month='201701');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='ZH',month='201702');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='ZH',month='201702');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='ZH',month='201703');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='ZH',month='201703');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='ZH',month='201704');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='ZH',month='201704');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='ZH',month='201705');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='ZH',month='201705');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='ZH',month='201706');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='ZH',month='201706');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='ZH',month='201707');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='ZH',month='201707');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='ZJ',month='201612');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='ZJ',month='201612');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='ZJ',month='201701');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='ZJ',month='201701');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='ZJ',month='201702');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='ZJ',month='201702');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='ZJ',month='201703');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='ZJ',month='201703');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='ZJ',month='201704');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='ZJ',month='201704');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='ZJ',month='201705');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='ZJ',month='201705');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='ZJ',month='201706');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='ZJ',month='201706');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='ZJ',month='201707');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='ZJ',month='201707');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='ZQ',month='201612');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='ZQ',month='201612');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='ZQ',month='201701');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='ZQ',month='201701');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='ZQ',month='201702');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='ZQ',month='201702');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='ZQ',month='201703');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='ZQ',month='201703');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='ZQ',month='201704');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='ZQ',month='201704');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='ZQ',month='201705');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='ZQ',month='201705');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='ZQ',month='201706');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='ZQ',month='201706');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='ZQ',month='201707');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='ZQ',month='201707');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='ZS',month='201612');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='ZS',month='201612');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='ZS',month='201701');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='ZS',month='201701');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='ZS',month='201702');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='ZS',month='201702');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='ZS',month='201703');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='ZS',month='201703');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='ZS',month='201704');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='ZS',month='201704');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='ZS',month='201705');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='ZS',month='201705');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='ZS',month='201706');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='ZS',month='201706');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M DROP IF EXISTS PARTITION (branch='ZS',month='201707');"
remote_cli.pl bd_mon beeline -e "USE JCFW;ALTER TABLE JCFW.TW_TERMPAY_PROV_ACTVCALL_M ADD PARTITION (branch='ZS',month='201707');"

