----bd_b租户脚本----
DROP TABLE IF EXISTS JCFW.TO_R_BLANKSIM_IN_STORE_D;
CREATE EXTERNAL TABLE JCFW.TO_R_BLANKSIM_IN_STORE_D (
   IN_CITY_TIME    STRING,
   CHANNEL    STRING,
   CARD_ID    STRING,
   CITY    STRING,
   PRODUCT_ID    BIGINT
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES ('field.delim'='|','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/JRCL/BD_B/ODS/TO_R_BLANKSIM_IN_STORE_D';

DROP TABLE IF EXISTS JCFW.TO_E_ESOP_LOG_MAIN_D;
CREATE EXTERNAL TABLE JCFW.TO_E_ESOP_LOG_MAIN_D (
   LOG_ID    STRING,
   LOG_NAM    STRING,
   LOG_TYP    STRING,
   CTY_CD    STRING,
   OPERATION_ID    STRING,
   OPERATION_NAM    STRING,
   SERVICE_ACT    STRING,
   GROUP_ID    STRING,
   CRTEATOR    STRING,
   CREATE_DTS    STRING,
   CHG_TIM    STRING,
   LOG_CONT    STRING,
   LOG_SRC    STRING,
   STS_CD    STRING,
   LOG_ATTACH    STRING,
   GROUP_TYP    STRING,
   VISIT_DT    STRING,
   LOG_WRITE_LENGTH    STRING,
   GROUP_NAME    STRING,
   SER_TYP_CD    STRING,
   VISIT_FORM    STRING,
   VISIT_AIM    STRING,
   SUBSNUMBER    STRING,
   CUST_NAM    STRING,
   CUST_ROLE    STRING,
   CORP_SCOPE    STRING,
   DIST_NAM    STRING,
   CUST_MGR    STRING,
   FOLLOW_STAFF    STRING,
   PROJECT_FEE    STRING,
   PROJECT_BRIEF    STRING,
   COMP_OPPONENT    STRING,
   COMP_LEVEL    STRING,
   RESPONSE_EVENT    STRING,
   RESPONSE_RESULT    STRING,
   OTHER_RESULT    STRING,
   NOTES    STRING,
   CHIEF_VISIT_MGR_NAM    STRING,
   CHIEF_VISIT_MGR_JOB    STRING,
   VISIT_TYPE    STRING,
   MOVEMENT_DESC    STRING,
   IMPACT    STRING,
   PROJECT_NAM    STRING,
   REFER_PRDCT    STRING,
   AFFECT_RANGE    STRING,
   CMCC_BRANCH_CD    STRING
)
PARTITIONED BY (branch STRING,month INT,day INT)
STORED AS PARQUET
LOCATION '/tenant/BIGDATA/JCFW/JRCL/BD_B/ODS/TO_E_ESOP_LOG_MAIN_D'
TBLPROPERTIES ('serialization.null.format' ='NVL','serialization.encoding' ='GBK');

DROP TABLE IF EXISTS JCFW.TO_E_ESOP_LOG_VISITAIM_M;
CREATE EXTERNAL TABLE JCFW.TO_E_ESOP_LOG_VISITAIM_M (
   OID    STRING,
   LOG_ID    STRING,
   CMCC_BRANCH_CD    STRING,
   CTY_CD    STRING,
   VISIT_PERSON    STRING,
   DUTY    STRING,
   USR_NBR    STRING
)
PARTITIONED BY (branch STRING,month INT)
STORED AS PARQUET
LOCATION '/tenant/BIGDATA/JCFW/JRCL/BD_B/ODS/TO_E_ESOP_LOG_VISITAIM_M'
TBLPROPERTIES ('serialization.null.format' ='NVL','serialization.encoding' ='GBK');

DROP TABLE IF EXISTS JCFW.TO_P_CHNL_BBOSSWAY_D;
CREATE EXTERNAL TABLE JCFW.TO_P_CHNL_BBOSSWAY_D (
   UNIQUE_CHNL_CD    STRING,
   CHNL_CD    STRING,
   CMOP_CHNL_CD    STRING,
   CMCC_BRANCH_CD    STRING,
   CREATE_TIM    TIMESTAMP
)
PARTITIONED BY (branch STRING)
STORED AS PARQUET
LOCATION '/tenant/BIGDATA/JCFW/JRCL/BD_B/ODS/TO_P_CHNL_BBOSSWAY_D'
TBLPROPERTIES ('serialization.null.format' ='NVL','serialization.encoding' ='GBK');

DROP TABLE IF EXISTS JCFW.TO_R_CORP_XXT_CODEBI_D;
CREATE EXTERNAL TABLE JCFW.TO_R_CORP_XXT_CODEBI_D (
   SID    INT,
   CMCC_BRANCH_CD    STRING,
   BUSI_BRIEF    STRING,
   EFF_DT    INT,
   SP_SERV_CD    STRING,
   SP_SUBBUSI_CD    STRING,
   APPLY_SCOPE    INT,
   SP_SUBBUSI_TYP    STRING,
   TARIFF    DECIMAL(12,2),
   SP_SERV_TYP    SMALLINT
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/JRCL/BD_B/ODS/TO_R_CORP_XXT_CODEBI_D';

DROP TABLE IF EXISTS JCFW.TS_E_GRP_BBOSS_ARCHIVE_TASKHIS_M;
CREATE EXTERNAL TABLE JCFW.TS_E_GRP_BBOSS_ARCHIVE_TASKHIS_M (
   STAT_MO    INT,
   BBOSS_ORDER_ID    STRING,
   SOURCE    STRING,
   AREA_CD    STRING,
   GROUP_ID    STRING,
   PRDCT_SPEC_CD    STRING,
   HOST_PROVINCE    STRING,
   ORDER_TYPE    STRING,
   BUSI_NESS_MODE    STRING,
   STS_CD    STRING,
   STS_DT    INT,
   STS_TIM    STRING,
   ERR_MSG    STRING,
   TASK_TYP    STRING,
   TRANSIDO    STRING,
   TRANSIDH    STRING,
   RSPN_CD    STRING,
   RSPN_DESC    STRING
)
PARTITIONED BY (branch STRING,month INT)
STORED AS PARQUET
LOCATION '/tenant/BIGDATA/JCFW/JRCL/BD_B/STAGE/TS_E_GRP_BBOSS_ARCHIVE_TASKHIS_M'
TBLPROPERTIES ('serialization.null.format' ='NVL','serialization.encoding' ='GBK');

DROP TABLE IF EXISTS JCFW.TR_GRP_BBOSS_POINFO;
CREATE EXTERNAL TABLE JCFW.TR_GRP_BBOSS_POINFO (
   PRDCT_SPEC_CD    STRING,
   PRDCT_SPEC_NAM    STRING,
   PRDCT_TYP    STRING,
   BASS_PRDCT_CD    STRING,
   STS_CD    STRING,
   START_DT    STRING,
   END_DT    STRING,
   DESCRIPTION    STRING
)
PARTITIONED BY (branch STRING)
STORED AS PARQUET
LOCATION '/tenant/BIGDATA/JCFW/JRCL/BD_B/REF/TR_GRP_BBOSS_POINFO'
TBLPROPERTIES ('serialization.null.format' ='NVL','serialization.encoding' ='GBK');

ALTER TABLE JCFW.TR_GRP_BBOSS_POINFO ADD PARTITION (branch='GMCC');

DROP TABLE IF EXISTS JCFW.TR_PC_BBOSS_PRODUCT;
CREATE EXTERNAL TABLE JCFW.TR_PC_BBOSS_PRODUCT (
   POID    STRING,
   OWNE_RPOID    STRING,
   PROD_ID    STRING,
   PRDCT_SPEC_CD    STRING,
   PRDCT_SPEC_NAM    STRING,
   PRDCT_TYP    STRING,
   STS_CD    SMALLINT
)
PARTITIONED BY (branch STRING)
STORED AS PARQUET
LOCATION '/tenant/BIGDATA/JCFW/JRCL/BD_B/REF/TR_PC_BBOSS_PRODUCT'
TBLPROPERTIES ('serialization.null.format' ='NVL','serialization.encoding' ='GBK');

ALTER TABLE JCFW.TR_PC_BBOSS_PRODUCT ADD PARTITION (branch='GMCC');

DROP TABLE IF EXISTS JCFW.TS_LOAD_QY_INCOME_RPT;
CREATE EXTERNAL TABLE JCFW.TS_LOAD_QY_INCOME_RPT (
   TM_INTRVL_CD    INT,
   CMCC_BRANCH_CD    STRING,
   CHRG_CRD_AMT    DECIMAL(16,2),
   PKG_CRD_AMT    DECIMAL(16,2),
   GOTONE_PRECHRG_AMT    DECIMAL(16,2),
   IUSR_PRECHRG_AMT    DECIMAL(16,2),
   OTH_AMT    DECIMAL(16,2),
   SELL_AMT    DECIMAL(16,2),
   NEW_AMT    DECIMAL(16,2),
   TOT_AMT    DECIMAL(16,2),
   IUSR_CHRG_AMT    DECIMAL(16,2),
   IBOSS_CHRG_AMT    DECIMAL(16,2),
   BOSS_DG_PRECHRG    DECIMAL(16,2),
   BOSS_SZX_PRECHRG    DECIMAL(16,2),
   OCS_DG_PRECHRG    DECIMAL(16,2),
   OCS_SZX_PRECHRG    DECIMAL(16,2),
   SCP_DG_PRECHRG    DECIMAL(16,2),
   SCP_SZX_PRECHRG    DECIMAL(16,2),
   AIR_CHRG_AMT    DECIMAL(16,2),
   SIM_CRD_AMT    DECIMAL(16,2),
   BAD_BILL_AMT    DECIMAL(16,2),
   CHNL_AMT    DECIMAL(16,2),
   TAX_AMT    DECIMAL(16,2),
   AREA_BUSI_AMT    DECIMAL(16,2),
   SZX_PKGCRD_AMT    DECIMAL(16,2),
   DG_PKGCRD_AMT    DECIMAL(16,2),
   DATA_SOURCE    STRING
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/JRCL/BD_B/STAGE/TS_LOAD_QY_INCOME_RPT';

DROP TABLE IF EXISTS JCFW.TS_LOAD_QY_INCOME_RPT_MO;
CREATE EXTERNAL TABLE JCFW.TS_LOAD_QY_INCOME_RPT_MO (
   TM_INTRVL_CD    INT,
   CMCC_BRANCH_CD    STRING,
   CHRG_CRD_AMT    DECIMAL(16,2),
   PKG_CRD_AMT    DECIMAL(16,2),
   GOTONE_PRECHRG_AMT    DECIMAL(16,2),
   IUSR_PRECHRG_AMT    DECIMAL(16,2),
   OTH_AMT    DECIMAL(16,2),
   SELL_AMT    DECIMAL(16,2),
   NEW_AMT    DECIMAL(16,2),
   TOT_AMT    DECIMAL(16,2),
   IUSR_CHRG_AMT    DECIMAL(16,2),
   IBOSS_CHRG_AMT    DECIMAL(16,2),
   BOSS_DG_PRECHRG    DECIMAL(16,2),
   BOSS_SZX_PRECHRG    DECIMAL(16,2),
   OCS_DG_PRECHRG    DECIMAL(16,2),
   OCS_SZX_PRECHRG    DECIMAL(16,2),
   SCP_DG_PRECHRG    DECIMAL(16,2),
   SCP_SZX_PRECHRG    DECIMAL(16,2),
   AIR_CHRG_AMT    DECIMAL(16,2),
   SIM_CRD_AMT    DECIMAL(16,2),
   BAD_BILL_AMT    DECIMAL(16,2),
   CHNL_AMT    DECIMAL(16,2),
   TAX_AMT    DECIMAL(16,2),
   AREA_BUSI_AMT    DECIMAL(16,2),
   SZX_PKGCRD_AMT    DECIMAL(16,2),
   DG_PKGCRD_AMT    DECIMAL(16,2),
   DATA_SOURCE    STRING
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/JRCL/BD_B/STAGE/TS_LOAD_QY_INCOME_RPT_MO';

DROP TABLE IF EXISTS JCFW.TO_R_CRM_ELCTR_RECORD_DATA_M;
CREATE EXTERNAL TABLE JCFW.TO_R_CRM_ELCTR_RECORD_DATA_M (
   STAT_MO    INT,
   ORDR_SEQ    STRING,
   TRADE_OPR_TYP    STRING,
   OPR_DT    INT,
   OPR_TIM    STRING,
   ORDER_STS_CD    STRING,
   BATCH_NO    STRING,
   OPR_FEE    DECIMAL(20,2),
   USR_NBR    STRING,
   IMEI    STRING,
   OPR_CHNL_ID    STRING,
   CMCC_BRANCH_NAM    STRING,
   MARK_PLAN_CD    STRING,
   MARK_PLAN_NAM    STRING,
   OPR_CODE    STRING,
   CMCC_BRANCH_CD    STRING,
   ELCTR_OBT_TYP    STRING
)
PARTITIONED BY (branch STRING,month INT)
STORED AS PARQUET
LOCATION '/tenant/BIGDATA/JCFW/JRCL/BD_B/ODS/TO_R_CRM_ELCTR_RECORD_DATA_M'
TBLPROPERTIES ('serialization.null.format' ='NVL','serialization.encoding' ='GBK');

DROP TABLE IF EXISTS JCFW.TR_HSH_ASSIGNED_PRDCT;
CREATE EXTERNAL TABLE JCFW.TR_HSH_ASSIGNED_PRDCT (
   BASS_PRDCT_CD    STRING,
   BASS_PRDCT_NAM    STRING,
   PRDCT_TYP_CD    STRING,
   PRDCT_TYP_NAM    STRING
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES ('field.delim'=',','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/JRCL/BD_B/REF/TR_HSH_ASSIGNED_PRDCT';

ALTER TABLE JCFW.TR_HSH_ASSIGNED_PRDCT ADD PARTITION (branch='GMCC');

DROP TABLE IF EXISTS JCFW.TR_HSH_ASSIGNED_CHNL;
CREATE EXTERNAL TABLE JCFW.TR_HSH_ASSIGNED_CHNL (
   CMCC_BRANCH_CD    STRING,
   CHNL_CD    STRING
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES ('field.delim'=',','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/JRCL/BD_B/REF/TR_HSH_ASSIGNED_CHNL';

ALTER TABLE JCFW.TR_HSH_ASSIGNED_CHNL ADD PARTITION (branch='GMCC');

DROP TABLE IF EXISTS JCFW.TO_R_ADDR_INF_D;
CREATE EXTERNAL TABLE JCFW.TO_R_ADDR_INF_D (
   ADDR_ID    INT,
   ADDR_NAM    STRING,
   GRADE    INT,
   JP    STRING,
   WB    STRING,
   SUPER_ID    INT,
   ALIAS_ADDR    STRING,
   OLD_ADDR    INT,
   IS_CONFIRM    INT,
   ADDR    STRING,
   ADDR_PY    STRING,
   ALIAS_ADDR_PY    STRING,
   CONFIRM_DATE    STRING,
   CONFIRM_DATE2    STRING,
   AMEND    SMALLINT,
   RECDATE    STRING,
   SUBDEP_NAME    STRING,
   SYSFLAG    SMALLINT,
   POSTNUMBER    STRING,
   STYPE    STRING,
   NUM    STRING,
   TAG    INT,
   IBSS_ADDR_ID    INT,
   IBSEND    INT,
   OLD_PARENTID    INT,
   SPLIT_FLAGC    INT,
   SPLIT_FLAG    INT,
   ADDRTYPE    INT,
   REGIONID    INT,
   IMPORTFLAG    STRING,
   INTSID1    STRING,
   INTSID2    STRING,
   INTSID3    STRING,
   INTSID4    STRING,
   INTSID5    STRING,
   INTSID6    STRING,
   INTSID7    STRING,
   ADDR_TYPE_EX    INT,
   ADDR_TYPE_EX_2    INT,
   GREEN_LABEL    INT,
   GRADE3ID    INT,
   LONGITUDE    STRING,
   LATITUDE    STRING,
   BELONG_CELL_ID    STRING,
   RES_TYP_CD    SMALLINT,
   BS_TYP    SMALLINT,
   THRD_NAM    STRING,
   THIRD_NBR    STRING,
   PICTURE_LINK    STRING,
   ADDR_SOURCE    INT,
   STATUS    INT,
   HCOVERMODE    INT,
   REMARKS    STRING,
   SHIELD_OPEN_SERVICE    STRING,
   CN_WAY    STRING,
   REGION_ATTRI    INT,
   CMCC_BRANCH_CD    STRING
)
PARTITIONED BY (branch STRING)
STORED AS PARQUET
LOCATION '/tenant/BIGDATA/JCFW/JRCL/BD_B/ODS/TO_R_ADDR_INF_D'
TBLPROPERTIES ('serialization.null.format' ='NVL','serialization.encoding' ='GBK');


