----bd_b租户脚本----
DROP TABLE IF EXISTS JCFW.TS_BASS_NBRGRP;
CREATE EXTERNAL TABLE JCFW.TS_BASS_NBRGRP (
   NBRGRP_CD    INT,
   NBRGRP_NAM    STRING,
   CMCC_CTY_CD    STRING,
   HLR_CD    STRING,
   BAK_HLR_CD    STRING,
   NBRGRP_STS    STRING
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/JRCL/BD_B/STAGE/TS_BASS_NBRGRP';

DROP TABLE IF EXISTS JCFW.TS_BASS_MKPLN_OPR;
CREATE EXTERNAL TABLE JCFW.TS_BASS_MKPLN_OPR (
   MARK_PLAN_CD    STRING,
   AREA_CD    STRING,
   REGION    STRING,
   OBJ_CD    STRING,
   IS_OPR    STRING,
   CREAT_DT    INT,
   CREAT_TIM    STRING
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/JRCL/BD_B/STAGE/TS_BASS_MKPLN_OPR';

DROP TABLE IF EXISTS JCFW.TS_BASS_MKPLN_CUSTGRP_ALLOW;
CREATE EXTERNAL TABLE JCFW.TS_BASS_MKPLN_CUSTGRP_ALLOW (
   MARK_PLAN_CD    STRING,
   CUST_GRP_CD    STRING,
   AREA_CD    STRING,
   REGION    STRING,
   CREAT_DT    INT,
   CREAT_TIM    STRING,
   BEGIN_DT    INT,
   BEGIN_TIM    STRING,
   END_DT    INT,
   END_TIM    STRING
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/JRCL/BD_B/STAGE/TS_BASS_MKPLN_CUSTGRP_ALLOW';

DROP TABLE IF EXISTS JCFW.TS_BASS_MKPLN_CUSTGRP_FORBID;
CREATE EXTERNAL TABLE JCFW.TS_BASS_MKPLN_CUSTGRP_FORBID (
   MARK_PLAN_CD    STRING,
   CUST_GRP_CD    STRING,
   AREA_CD    STRING,
   REGION    STRING,
   CREAT_DT    INT,
   CREAT_TIM    STRING,
   BEGIN_DT    INT,
   BEGIN_TIM    STRING,
   END_DT    INT,
   END_TIM    STRING
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/JRCL/BD_B/STAGE/TS_BASS_MKPLN_CUSTGRP_FORBID';

DROP TABLE IF EXISTS JCFW.TS_BASS_DB_REGION_DAY;
CREATE EXTERNAL TABLE JCFW.TS_BASS_DB_REGION_DAY (
   AREA_CD    STRING,
   AREA_NAM    STRING,
   CITY_ID    STRING,
   CMCC_BRANCH_CD    STRING
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/JRCL/BD_B/STAGE/TS_BASS_DB_REGION_DAY';


