----bd_b租户脚本----
DROP TABLE IF EXISTS JCFW.TS_P_CRM_CUST_ADDR_D;
CREATE EXTERNAL TABLE JCFW.TS_P_CRM_CUST_ADDR_D (
   OID    BIGINT,
   REGION    INT,
   CUSTID    BIGINT,
   LANGTYPE    STRING,
   MAILTYPE    STRING,
   MAILADDR    STRING,
   POSTCODE    STRING,
   LINKMAN    STRING,
   LINKPHONE    STRING,
   EMAIL    STRING,
   ADDRNAME    STRING,
   ISDEFAULT    INT,
   CREATEDATE    STRING,
   STATUS    INT,
   STATUSDATE    STRING
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='&&','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/JRCL/BD_B/STAGE/TS_P_CRM_CUST_ADDR_D';

DROP TABLE IF EXISTS JCFW.TO_P_SCHOOL_USR_M;
CREATE EXTERNAL TABLE JCFW.TO_P_SCHOOL_USR_M (
   STAT_MO    INT,
   USR_NBR    STRING,
   CMCC_BRANCH_CD    STRING,
   SCHOOL_NAM    STRING
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='&&','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/JRCL/BD_B/ODS/TO_P_SCHOOL_USR_M';

DROP TABLE IF EXISTS JCFW.TO_E_USR_FLUX_LIMIT_M;
CREATE EXTERNAL TABLE JCFW.TO_E_USR_FLUX_LIMIT_M (
   STAT_MO    INT,
   REQ_ID    BIGINT,
   USR_NBR    STRING,
   LIMIT_OR_RESTORE    STRING,
   REQ_RESOURCE    SMALLINT,
   REQ_TIME    STRING,
   DEAL_STATE_CD    SMALLINT,
   OPER_CD    STRING,
   OLD_STATE    STRING,
   NEW_STATE    STRING,
   IS_SEND_SMS    STRING,
   REMARK    STRING
)
PARTITIONED BY (branch STRING,month INT)
STORED AS PARQUET
LOCATION '/tenant/BIGDATA/JCFW/JRCL/BD_B/ODS/TO_E_USR_FLUX_LIMIT_M'
TBLPROPERTIES ('serialization.null.format' ='NVL','serialization.encoding' ='GBK');


