----bd_day租户脚本----
DROP TABLE IF EXISTS JCFW.TM_PRDCT_BUSI_HANDLE_D;
CREATE EXTERNAL TABLE JCFW.TM_PRDCT_BUSI_HANDLE_D (
   STAT_DT    INT,
   CMCC_BRANCH_CD    STRING,
   DIST_ID    STRING,
   MICRODIST_ID    STRING,
   BUSI_USR_NBR    STRING,
   CHNL_STAR_LVL3_IND    STRING,
   CHNL_CD    STRING,
   CHNL_STS_CD    STRING,
   ACCEPT_OPR_ID    STRING,
   BUSI_ACCEPT_NBR    STRING,
   ACCEPT_DT    INT,
   ACCEPT_TIM    STRING,
   BASS_PRDCT_CD    STRING,
   BASS_PRDCT_NAM    STRING,
   OPR_TYP    STRING,
   WORKF_TYP_CD    STRING,
   MENU_ID    STRING,
   IN_SYSTEM    STRING,
   ORDER_ID    STRING
)
PARTITIONED BY (branch STRING,month INT,day INT)
STORED AS PARQUET
LOCATION '/tenant/BIGDATA/JCFW/BZMX/DAY/DM/TM_PRDCT_BUSI_HANDLE_D'
TBLPROPERTIES ('serialization.null.format' ='NVL','serialization.encoding' ='GBK');


