----bd_gdoth租户脚本----
DROP TABLE IF EXISTS JCFW.TR_R_ZH_TERM_PRDCT;
CREATE EXTERNAL TABLE JCFW.TR_R_ZH_TERM_PRDCT (
   TAC    STRING,
   TERM_BRND_NAM    STRING,
   TERM_MDL_NAM    STRING,
   IF_INTELL    STRING,
   IF_WIFI    STRING,
   IF_FRONT_CAMERA    STRING,
   IF_TD    STRING,
   IF_DUAL_CARD    STRING,
   CAMERA_PIXEL    INT,
   SCREEN_SIZE    DECIMAL(14,4),
   SCREEN_PIEL    INT,
   NETWORK    STRING,
   ROM    STRING,
   RAM    DECIMAL(14,4),
   WEIHT    DECIMAL(14,4),
   BATTERY_CAPACITY    INT,
   PRTCL_PRC    INT,
   PRICE_RANGE    STRING,
   TER_TYPE_NAME    STRING,
   TDLTE_IND    STRING,
   FDLTE_IND    STRING,
   SALE_PATH    STRING,
   IF_NFC    STRING,
   PRODUCT_MODEL    STRING,
   IF_LTE    STRING,
   NEW_PRTCL_PRC    INT,
   NEW_PRICE_RANGE    STRING,
   FRONT_CAMERA_PIXEL    STRING,
   IF_FINGERPRINT    STRING,
   TERM_NET_TYP    STRING,
   MARKET_TIME    INT,
   A4G_TERM    STRING,
   TERM_TYP_CD    STRING
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES ('field.delim'=',','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_OTH/REF/TR_R_ZH_TERM_PRDCT';

ALTER TABLE JCFW.TR_R_ZH_TERM_PRDCT ADD PARTITION (branch='GMCC');

DROP TABLE IF EXISTS JCFW.TR_NB_GPRS_PRDCT;
CREATE EXTERNAL TABLE JCFW.TR_NB_GPRS_PRDCT (
   BASS_PRDCT_CD    STRING,
   BASS_PRDCT_NAM    STRING,
   PKG_KIND_CD    SMALLINT,
   GPRS_PKG_TYP_CD    SMALLINT,
   GPRS_PKG_TYP_DTL_CD    INT,
   GPRS_PKG_TM_TYP_CD    SMALLINT,
   GPRS_PKG_TYP_NAM    STRING,
   GPRS_PKG_TYP_DTL_NAM    STRING,
   GPRS_PKG_COMMON_FLUX    BIGINT,
   GPRS_PKG_TD_FLUX    BIGINT,
   GPRS_PKG_TDLTE_FLUX    BIGINT,
   GPRS_PKG_IDLE_FLUX    BIGINT,
   GPRS_PKG_FEE    DECIMAL(12,2),
   PRDCT_FEE    DECIMAL(16,2),
   FLUX_MAIN_PKG_IND    SMALLINT,
   PKG_SUPL_TYP_CD    SMALLINT,
   PKG_SUPL_TYP_NAM    STRING,
   V_TYP_CD_1    SMALLINT,
   V_TYP_NAM_1    STRING,
   MIX_PKG_IND    STRING,
   A4G_PKG_IND    STRING,
   A4G_MIX_PKG_IND    STRING,
   A4G_FLUX_PKG_IND    STRING,
   C_FLUX_PKG_IND    STRING,
   V_TYP_CD_2    SMALLINT,
   V_TYP_NAM_2    STRING,
   LC_FLUX_PKG_IND    STRING,
   PM_PKG_IND    STRING,
   SWYH_PRDCT_CD    STRING,
   CORP_PKG_IND    STRING,
   YEAR_PKG_IND    STRING,
   YEAR_PKG_NAM    STRING,
   WHPKG_CD    STRING,
   V_TYP_CD_3    SMALLINT,
   V_TYP_NAM_3    STRING,
   GIF_PRDCT_CD    STRING,
   GIF_PRDCT_NAM    STRING,
   GIF2_PRDCT_CD    STRING,
   V_TYP_CD_4    SMALLINT,
   V_TYP_NAM_4    STRING,
   SNACK_PKG_IND    STRING,
   EQUITY_PKG_IND    STRING,
   A4G_TK_PKG_IND    STRING,
   CHNL_MNTR_FLUX_PKG_IND    STRING,
   MON_FLUX_PKG_IND    STRING,
   TIM_LIMIT_PKG_IND    STRING,
   SR201708210015001_IND    STRING
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES ('field.delim'=',','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_OTH/REF/TR_NB_GPRS_PRDCT';

ALTER TABLE JCFW.TR_NB_GPRS_PRDCT ADD PARTITION (branch='GMCC');


