----bd_gdmm租户脚本----
DROP TABLE IF EXISTS JCFW.TW_BASS_GUSR_MO;
CREATE EXTERNAL TABLE JCFW.TW_BASS_GUSR_MO (
   TM_INTRVL_CD    INT,
   CUST_ID    STRING,
   USR_ID    STRING,
   AREA_CD    STRING,
   CMCC_BRANCH_CD    STRING,
   PAR_GROUP_ID    STRING,
   CUST_NAM    STRING,
   GROUP_ID    STRING,
   INDUS_TYP_CD    SMALLINT,
   INDUS_TYP2_CD    INT,
   CORP_TYP_CD    SMALLINT,
   CORP_PAY_TYP_CD    STRING,
   EMPLOYE_CNT    INT,
   MGR_CNT    INT,
   CMN_EMPLOYE_CNT    INT,
   RGST_NO    STRING,
   CORP_SCOP_TYP_CD    SMALLINT,
   CORP_SIZE_TYP_CD    SMALLINT,
   MRKT_CHNL_CD    STRING,
   CUST_INNET_DT    INT,
   BUDGET_AMT    DECIMAL(18,2),
   MEM_LIMIT    INT,
   CORP_MOB_CNT    INT,
   CORP_CMCC_MOB_CNT    INT,
   CORP_CDMA_CNT    INT,
   CORP_CUNC_GSM_CNT    INT,
   CORP_CTLC_MOB_CNT    INT,
   GLB_USR_CNT    INT,
   PREP_USR_CNT    INT,
   DZK_USR_CNT    INT,
   MZONE_USR_CNT    INT,
   RGST_FUND    DECIMAL(18,2),
   INVOICE_TYP_CD    STRING,
   INVOICE_NAME    STRING,
   CMPT_STS_CD    STRING,
   CROS_BUSI_TYP    STRING,
   CORP_SRVC_RNK_CD    STRING,
   IFCONSIST    STRING,
   SML_CORP_TYP    STRING,
   CUST_LVL    STRING,
   CREAT_TIM    INT,
   YEAR_SALE_AMT    DECIMAL(18,2),
   YEAR_PROF_AMT    DECIMAL(18,2),
   LAST_YEAR_INCOMING    DECIMAL(18,2),
   VIP_CNT    INT,
   VPMN_CODE_CTY    STRING,
   FUND_TYP    STRING,
   FUND_CO    STRING,
   CUST_CHG_DT    INT,
   CUST_INNET_IND    SMALLINT,
   PAY_TYP_CD    STRING,
   USR_NBR    STRING,
   BASS_PRDCT_CD    STRING,
   USR_STS_CD    STRING,
   INNET_MO_CNT    SMALLINT,
   REG_DT    INT,
   START_DT    INT,
   INVALID_DT    INT,
   USR_STS_DT    INT,
   USR_OUTNET_DT    INT,
   TGT_CUST_IND    STRING,
   CO_ADDRESS    STRING,
   LEADER_MOB_NBR    STRING,
   LEADER_OFFICE_TEL    STRING,
   DEPUTY_EMP_ID    STRING
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/EDS/TW_BASS_GUSR_MO';

DROP TABLE IF EXISTS JCFW.TW_BASS_CORP_PRDCT_MO;
CREATE EXTERNAL TABLE JCFW.TW_BASS_CORP_PRDCT_MO (
   TM_INTRVL_CD    INT,
   GUSR_ID    STRING,
   AREA_CD    STRING,
   INTRL_ID    STRING,
   GCUST_ID    STRING,
   BASS_PRDCT_CD    STRING,
   YJ_PRD_CODE    STRING,
   BUSI_TYP_IND    SMALLINT,
   REL_GUSR_ID    STRING,
   MAX_MBR_CNT    INT,
   EFF_DT    INT,
   USR_STS_CD    STRING,
   STS_DT    INT,
   CUST_TYP    SMALLINT,
   PRDCT_PKG_IND    STRING,
   PRDCT_PKG_ID    STRING,
   CORP_PRDCT_NBR    STRING,
   CORP_USR_NBR    STRING,
   INTR_PRVC_IND    STRING,
   MSTR_IND    STRING,
   PAY_GCUST_ID    STRING,
   ORDR_ID    STRING,
   INTR_USR_ID    STRING,
   GUSR_NAM    STRING,
   EBOX_ID    STRING,
   MEMCOUNT    INT,
   CONTRACTCODE    STRING,
   CONTRACTOID    STRING,
   CMCC_BRANCH_CD    STRING,
   CORP_PRDCT_CODE    STRING,
   MAIN_ATR_DESC    STRING,
   VTL_CORP_PRD_IND    STRING,
   IOT_TYP_CD    STRING,
   IOT_ATR_IND    STRING,
   BRND_CD    SMALLINT,
   PRDCT_SRC    SMALLINT
)
PARTITIONED BY (branch STRING,month INT)
STORED AS PARQUET
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/EDS/TW_BASS_CORP_PRDCT_MO'
TBLPROPERTIES ('serialization.null.format' ='NVL','serialization.encoding' ='GBK');

DROP TABLE IF EXISTS JCFW.TW_CORP_BRCC_SNAP;
CREATE EXTERNAL TABLE JCFW.TW_CORP_BRCC_SNAP (
   CMCC_BRANCH_CD    STRING,
   GROUP_ID    STRING,
   SNGRP_AB_CD    STRING
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/EDS/TW_CORP_BRCC_SNAP';

DROP TABLE IF EXISTS JCFW.TW_CORP_INCOME;
CREATE EXTERNAL TABLE JCFW.TW_CORP_INCOME (
   TM_INTRVL_CD    INT,
   GROUP_ID    STRING,
   CMCC_BRANCH_CD    STRING,
   CMCC_CNTRY_CD    STRING,
   CMCC_TOWN_CD    STRING,
   CUST_NAM    STRING,
   DEPUTY_NAM    STRING,
   PROVCUST_NAM    STRING,
   GRP_AB_CD    STRING,
   SNGRP_AB_CD    STRING,
   CORP_TYP_CD    INT,
   INDUS_TYP_CD    INT,
   INDUS_TYP2_CD    INT,
   MEMBER_CNT_RNK_CD    SMALLINT,
   CORP_STS_CD    INT,
   CORP_VALID_IND    STRING,
   MEMBER_CNT    INT,
   CORP_DGUSR_CNT    INT,
   CORP_DFUSR_CNT    INT,
   IMPIND_USR_CNT    INT,
   CORP_DG_INCOME    DECIMAL(14,2),
   CORP_DF_INCOME    DECIMAL(14,2),
   CORP_TOTAL_INCOME    DECIMAL(14,2),
   STD_PRDCT_INCOME    DECIMAL(14,2),
   MEMBER_INCOME    DECIMAL(14,2),
   INDAPPLY_INCOME    DECIMAL(14,2),
   DF_INDAPPLY_INCOME    DECIMAL(14,2),
   STD_INFINCOME    DECIMAL(14,2),
   DF_STD_INFINCOME    DECIMAL(14,2),
   INFSOL_IND    INT,
   BASE_INFSOL_IND    INT,
   VCE_INCOME    DECIMAL(14,2),
   DEPUTY_ID    STRING,
   UNIT_KIND_CD    STRING,
   DTGRP_AB_CD    STRING,
   USE_PRDCT_CNT    INT,
   CORP_AVL_TOT_BAL    DECIMAL(14,2),
   ZB_INF_INCOME    DECIMAL(14,2),
   CROSS_PRVC_GROUP_IND    STRING,
   GROUP_CUST_TYP    STRING,
   GROUP_CUST_IMP_TYP    STRING
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/EDS/TW_CORP_INCOME';

DROP TABLE IF EXISTS JCFW.TW_CORP_INDAPPLY_DATA;
CREATE EXTERNAL TABLE JCFW.TW_CORP_INDAPPLY_DATA (
   TM_INTRVL_CD    INT,
   GROUP_ID    STRING,
   CMCC_BRANCH_CD    STRING,
   SERV_CMCC_BRANCH_CD    STRING,
   INDUSTRY_PRDCT_TYP    INT,
   BUSI_TYP    INT,
   SP_CODE    STRING,
   SP_SERV_CD    STRING,
   SP_SUBBUSI_CD    STRING,
   INDUSTRY_PRDCT_NAM    STRING,
   APPLY_SCOPE    INT,
   EFF_MONTH    INT,
   CUST_TYP    INT,
   STD_PRDCT_NBR    STRING,
   GROUP_NAM    STRING,
   MMS_BUSI_TYP    INT,
   REACH_USR_CNT    INT,
   NEW_USR_CNT    INT,
   ADDUP_USR_CNT    INT,
   INF_INCOME    DECIMAL(12,2),
   DF_INDUSUSR_CNT    INT,
   DF_INF_INCOME    DECIMAL(12,2),
   TOTAL_CALL_CNT    INT,
   UP_CALL_CNT    INT,
   DOWN_CALL_CNT    INT,
   MON_FEE    DECIMAL(12,2),
   INDAPPLY_ZB_IND    STRING,
   APPL_TYP_NAM    STRING
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/EDS/TW_CORP_INDAPPLY_DATA';

DROP TABLE IF EXISTS JCFW.TW_PROVCORP_UP;
CREATE EXTERNAL TABLE JCFW.TW_PROVCORP_UP (
   TM_INTRVL_CD    INT,
   CMCC_BRANCH_CD    STRING,
   INDUS_TYP_NAM    STRING,
   PROVCUST_NAM    STRING,
   CUST_MGR    STRING,
   BRANCH_ORGAN    STRING,
   GROUP_ID    STRING,
   CUST_NAM    STRING,
   CNTCT_NAM    STRING
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES ('field.delim'=',','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/EDS/TW_PROVCORP_UP';

DROP TABLE IF EXISTS JCFW.TR_CORP_CMCC_CNTRY;
CREATE EXTERNAL TABLE JCFW.TR_CORP_CMCC_CNTRY (
   CMCC_BRANCH_CD    STRING,
   CMCC_CNTRY_CD    STRING,
   CMCC_CNTRY_NAM    STRING,
   BI_CMCC_CNTRY_CD    STRING
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/REF/TR_CORP_CMCC_CNTRY';

ALTER TABLE JCFW.TR_CORP_CMCC_CNTRY ADD PARTITION (branch='GMCC');

DROP TABLE IF EXISTS JCFW.TW_CORP_STDPRDCT;
CREATE EXTERNAL TABLE JCFW.TW_CORP_STDPRDCT (
   TM_INTRVL_CD    INT,
   GROUP_ID    STRING,
   GUSR_ID    STRING,
   GCUST_ID    STRING,
   CMCC_BRANCH_CD    STRING,
   CMCC_CNTRY_CD    STRING,
   CMCC_TOWN_CD    STRING,
   GRP_AB_CD    STRING,
   SNGRP_AB_CD    STRING,
   USR_STS_CD    STRING,
   CORP_PRDCT_NBR    STRING,
   YJ_PRD_CODE    STRING,
   BUSI_TYP_IND    SMALLINT,
   CORP_PRDCT_CODE    STRING,
   CORP_PRDCT_NAM    STRING,
   USR_VALID_IND    STRING,
   USR_VALID2_IND    STRING,
   REACH_USR_CNT    INT,
   NEW_USR_CNT    INT,
   LOSE_USR_CNT    INT,
   TOTAL_DUR    INT,
   STD_PRDCT_INCOME    DECIMAL(14,2),
   STD_PRDCT_INFINCOME    DECIMAL(14,2),
   MEMBER_INCOME    DECIMAL(14,2),
   MEMBER_INFINCOME    DECIMAL(14,2),
   DF_MEMBER_CNT    INT,
   DF_MEMBER_INCOME    DECIMAL(14,2),
   DF_MEMBER_INFINCOME    DECIMAL(14,2),
   QN_DUR    INT,
   QN_INCOME    DECIMAL(14,2),
   DF_QN_INCOME    DECIMAL(14,2),
   UP_CALL_CNT    INT,
   DOWN_CALL_CNT    INT,
   BASS_PRDCT_CD    STRING,
   CORP_ZB_IND    STRING
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/EDS/TW_CORP_STDPRDCT';

DROP TABLE IF EXISTS JCFW.TR_CORP_PRDCT;
CREATE EXTERNAL TABLE JCFW.TR_CORP_PRDCT (
   PRDCT_CODE    STRING,
   PRDCT_NAM    STRING,
   PRDCT_TYP    STRING,
   CARRY_TYP    STRING,
   DATA_INCOME_IND    STRING,
   INFSOL_IND    STRING,
   DIV_PRDCT_IND    STRING,
   SORT_VAL    INT,
   CORP_ZB_IND    STRING,
   GFEE_TYP_CD    SMALLINT,
   MBR_FEE_PRR    INT,
   GACT_TYP_CD    SMALLINT,
   YJ_PRD_CODE    STRING,
   PRDCT_TYP_CD    INT,
   PRDCT_TYP_NAM    STRING
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES ('field.delim'=',','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/REF/TR_CORP_PRDCT';

ALTER TABLE JCFW.TR_CORP_PRDCT ADD PARTITION (branch='GMCC');

DROP TABLE IF EXISTS JCFW.TW_CORP_TF_EBOX_RELA_M;
CREATE EXTERNAL TABLE JCFW.TW_CORP_TF_EBOX_RELA_M (
   STAT_MO    INT,
   EBOX_ID    STRING,
   GROUP_ID    STRING,
   GCUST_ID    STRING,
   BL_GCUST_IND    STRING,
   BL_PRD_NDF_IND    STRING,
   BL_PRD_DF_IND    STRING,
   BL_DG_GCUST_IND    STRING,
   BL_DG_PCUST_IND    STRING,
   BL_DG_NGRP_PCUST_IND    STRING
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/EDS/TW_CORP_TF_EBOX_RELA_M';

DROP TABLE IF EXISTS JCFW.TW_ADC_CORP_MEMBER_MO;
CREATE EXTERNAL TABLE JCFW.TW_ADC_CORP_MEMBER_MO (
   TM_INTRVL_CD    INT,
   GUSR_ID    STRING,
   USR_NBR    STRING,
   CMCC_BRANCH_CD    STRING,
   CORP_PRDCT_CODE    STRING,
   BASS_PRDCT_CD    STRING,
   GROUP_ID    STRING,
   CORP_PRDCT_NBR    STRING,
   USR_ID    STRING,
   EFF_DT    INT,
   END_DT    INT,
   STATUS    STRING,
   UPDT_DT    INT
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/EDS/TW_ADC_CORP_MEMBER_MO';

DROP TABLE IF EXISTS JCFW.TW_CORP_MAS_DATA_RAW;
CREATE EXTERNAL TABLE JCFW.TW_CORP_MAS_DATA_RAW (
   TM_INTRVL_CD    INT,
   SORT_ID    STRING,
   MANU_NAM    STRING,
   CMCC_BRANCH    STRING,
   MAS_NAM    STRING,
   MAS_ID    STRING,
   INDUS_TYP    STRING,
   INNET_DT    STRING,
   INNET_STS    STRING,
   VPN_STS    STRING,
   GROUP_ID    STRING,
   BGOUP_ID    STRING
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/EDS/TW_CORP_MAS_DATA_RAW';

DROP TABLE IF EXISTS JCFW.TW_CORP_INDAPPLY_USEUSR;
CREATE EXTERNAL TABLE JCFW.TW_CORP_INDAPPLY_USEUSR (
   TM_INTRVL_CD    INT,
   SP_CODE    STRING,
   SP_SERV_CD    STRING,
   SP_SUBBUSI_CD    STRING,
   USR_NBR    STRING,
   SERV_CMCC_BRANCH_CD    STRING,
   CMCC_BRANCH_CD    STRING,
   APPLY_SCOPE    INT,
   BRND_CD    INT,
   UP_CALL_CNT    INT,
   DOWN_CALL_CNT    INT,
   MOB_FEE    DECIMAL(12,2),
   TOLL_FEE    DECIMAL(12,2),
   INF_FEE    DECIMAL(12,2),
   MON_FEE    DECIMAL(12,2),
   APPL_TYP_NAM    STRING
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/EDS/TW_CORP_INDAPPLY_USEUSR';

DROP TABLE IF EXISTS JCFW.TW_CORP_INDAPPLY_LJUSEUSR;
CREATE EXTERNAL TABLE JCFW.TW_CORP_INDAPPLY_LJUSEUSR (
   TM_INTRVL_CD    INT,
   SP_CODE    STRING,
   SP_SERV_CD    STRING,
   SP_SUBBUSI_CD    STRING,
   USR_NBR    STRING,
   SERV_CMCC_BRANCH_CD    STRING,
   CMCC_BRANCH_CD    STRING,
   APPLY_SCOPE    INT,
   BRND_CD    INT,
   NEW_USR_IND    STRING,
   USE_CNT    INT,
   CHRG_CNT    INT,
   LJ_MOB_FEE    DECIMAL(12,2),
   LJ_TOLL_FEE    DECIMAL(12,2),
   LJ_INF_FEE    DECIMAL(12,2),
   LJ_MON_FEE    DECIMAL(12,2),
   CURRMO_USE_IND    STRING,
   CURRMO_CHRG_IND    STRING,
   APPL_TYP_NAM    STRING
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/EDS/TW_CORP_INDAPPLY_LJUSEUSR';

DROP TABLE IF EXISTS JCFW.TW_GUSRCALL_MO;
CREATE EXTERNAL TABLE JCFW.TW_GUSRCALL_MO (
   TM_INTRVL_CD    INT,
   GROUP_ID    STRING,
   GCUST_ID    STRING,
   GUSR_ID    STRING,
   CORP_USR_NBR    STRING,
   CORP_PRDCT_NBR    STRING,
   DIR_TYP_CD    STRING,
   GRP_AGGREGATE_IND    STRING,
   IO_GRP_IND    STRING,
   TOLL_TYP_CD    SMALLINT,
   CMCC_BRANCH_CD    STRING,
   CALL_CNT    INT,
   CALL_DUR    BIGINT,
   CALL_FLUX    INT,
   DEBET_MOB_DUR    INT,
   MOB_FEE    DECIMAL(10,2),
   TOLL_FEE    DECIMAL(10,2),
   INF_FEE    DECIMAL(10,2),
   MOB_DEBET1_FEE    DECIMAL(10,2),
   TOLL_DEBET1_FEE    DECIMAL(10,2),
   INF_DEBET1_FEE    DECIMAL(10,2)
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/EDS/TW_GUSRCALL_MO';

DROP TABLE IF EXISTS JCFW.TW_GCUST_CONSUME;
CREATE EXTERNAL TABLE JCFW.TW_GCUST_CONSUME (
   BILL_CYC_CD    INT,
   USR_ID    STRING,
   GRP_AGGREGATE_IND    STRING,
   CUST_ID    STRING,
   CMCC_BRANCH_CD    STRING,
   USR_NBR    STRING,
   BASS_PRDCT_CD    STRING,
   INNET_MO_CNT    SMALLINT,
   CORP_TYP_CD    SMALLINT,
   CORP_SIZE_TYP_CD    SMALLINT,
   CORP_SRVC_RNK_CD    SMALLINT,
   INDUS_TYP_CD    SMALLINT,
   CORP_PAY_TYP_CD    STRING,
   CORP_SCOP_TYP_CD    SMALLINT,
   LB_FEE    DECIMAL(10,2),
   LB_DDD    DECIMAL(10,2),
   LB_IDD    DECIMAL(10,2),
   PB_FEE    DECIMAL(10,2),
   PB_DDD    DECIMAL(10,2),
   PB_IDD    DECIMAL(10,2),
   GB_FEE    DECIMAL(10,2),
   GB_DDD    DECIMAL(10,2),
   GB_IDD    DECIMAL(10,2),
   M_IP_FEE    DECIMAL(10,2),
   M_IP_DDD    DECIMAL(10,2),
   M_IP_IDD    DECIMAL(10,2),
   IB_FEE    DECIMAL(10,2),
   T_IP_FEE    DECIMAL(10,2),
   N_IP_FEE    DECIMAL(10,2),
   MW_SMS_FEE    DECIMAL(10,2),
   LB_GPRS_FEE    DECIMAL(10,2),
   ZJFF_FEE    DECIMAL(10,2),
   BJFF_FEE    DECIMAL(10,2),
   SMS_FEE    DECIMAL(10,2),
   MMS_FEE    DECIMAL(10,2),
   WAP_FEE    DECIMAL(10,2),
   WLAN_FEE    DECIMAL(10,2),
   LBT_TEL_FEE    DECIMAL(10,2),
   IPZT_FEE    DECIMAL(10,2),
   IPZT_DDD    DECIMAL(10,2),
   IPZT_IDD    DECIMAL(10,2),
   IB_GPRS_FEE    DECIMAL(10,2),
   OTH_TEL_FEE    DECIMAL(10,2),
   BASE_MONTH_FEE    DECIMAL(10,2),
   TAOCAN_MONTH_FEE    DECIMAL(10,2),
   VPMN_MONTH_FEE    DECIMAL(10,2),
   BYCALL_MONTH_FEE    DECIMAL(10,2),
   SMS_MONTH_FEE    DECIMAL(10,2),
   G_CALL_MONTH_FEE    DECIMAL(10,2),
   GPRS_MONTH_FEE    DECIMAL(10,2),
   MW_MONTH_FEE    DECIMAL(10,2),
   DVOICE_GPS_FEE    DECIMAL(10,2),
   CORP_SMS_FEE    DECIMAL(10,2),
   IDLE_MONTH_FEE    DECIMAL(10,2),
   LBT_MONTH_FEE    DECIMAL(10,2),
   SUB_NBR_FEE    DECIMAL(10,2),
   SVOICE_GPS_FEE    DECIMAL(10,2),
   NVOICE_GPS_FEE    DECIMAL(10,2),
   WIRELESS_POS_FEE    DECIMAL(10,2),
   LINE_MONTH_FEE    DECIMAL(10,2),
   IP_ADDR_FEE    DECIMAL(10,2),
   IP_VPN_FEE    DECIMAL(10,2),
   NET_USE_FEE    DECIMAL(10,2),
   OTH_MONTH_FEE    DECIMAL(10,2),
   NEW_FUNC_FEE    DECIMAL(10,2),
   ICP_INFO_FEE    DECIMAL(10,2),
   GPRS_INFO_FEE    DECIMAL(10,2),
   WAP_INFO_FEE    DECIMAL(10,2),
   LBT_INFO_FEE    DECIMAL(10,2),
   OTH_INFO_FEE    DECIMAL(10,2),
   DOFOR_FEE    DECIMAL(10,2),
   OTH_FEE    DECIMAL(10,2),
   BREACH_FEE    DECIMAL(10,2),
   MEND_FEE    DECIMAL(10,2),
   DISCOUNT_FEE    DECIMAL(10,2),
   REDUCE_FEE    DECIMAL(10,2),
   MO_AMT_FEE    DECIMAL(10,2),
   DT_AVG_FEE    DECIMAL(10,2)
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/EDS/TW_GCUST_CONSUME';

DROP TABLE IF EXISTS JCFW.TW_CORP_INDAPPLY_CODEBI;
CREATE EXTERNAL TABLE JCFW.TW_CORP_INDAPPLY_CODEBI (
   TM_INTRVL_CD    INT,
   CMCC_BRANCH_CD    STRING,
   GROUP_ID    STRING,
   INDUSTRY_PRDCT_TYP    INT,
   BUSI_TYP    INT,
   SP_CODE    STRING,
   SP_SERV_CD    STRING,
   SP_SUBBUSI_CD    STRING,
   SP_SUBBUSI_TYP    STRING,
   INDUSTRY_PRDCT_NAM    STRING,
   APPLY_SCOPE    INT,
   EFF_MONTH    INT,
   CUST_TYP    INT,
   GROUP_NAM    STRING,
   STD_PRDCT_NBR    STRING,
   MMS_BUSI_TYP    INT,
   CNTC_NAM    STRING,
   CNTC_NBR    STRING,
   BUSI_BRIEF    STRING
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/EDS/TW_CORP_INDAPPLY_CODEBI';

DROP TABLE IF EXISTS JCFW.TW_CORP_MAS_DATA;
CREATE EXTERNAL TABLE JCFW.TW_CORP_MAS_DATA (
   TM_INTRVL_CD    INT,
   CMCC_BRANCH_CD    STRING,
   MAS_ID    STRING,
   GROUP_ID    STRING,
   BGROUP_ID    STRING,
   CORP_PRDCT_CODE    STRING,
   INNET_IND    STRING,
   USR_VALID_IND    STRING
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/EDS/TW_CORP_MAS_DATA';

DROP TABLE IF EXISTS JCFW.TW_CORP_PDTPRT_RELA_MO;
CREATE EXTERNAL TABLE JCFW.TW_CORP_PDTPRT_RELA_MO (
   TM_INTRVL_CD    INT,
   CMCC_BRANCH_CD    STRING,
   GUSR_ID    STRING,
   CORP_USR_NBR    STRING,
   USR_STS_CD    STRING,
   CORP_PRDCT_NBR    STRING,
   CORP_PRDCT_NAM    STRING
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/EDS/TW_CORP_PDTPRT_RELA_MO';

DROP TABLE IF EXISTS JCFW.TR_INDUSTRY_PRDCT_TYP;
CREATE EXTERNAL TABLE JCFW.TR_INDUSTRY_PRDCT_TYP (
   INDUSTRY_PRDCT_TYP    INT,
   INDUSTRY_PRDCT_NAM    STRING,
   INDAPPLY_ZB_IND    STRING,
   YJ_PRD_CODE    STRING
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/REF/TR_INDUSTRY_PRDCT_TYP';

ALTER TABLE JCFW.TR_INDUSTRY_PRDCT_TYP ADD PARTITION (branch='GMCC');

DROP TABLE IF EXISTS JCFW.TW_CORP_INDAPPLY_CODE;
CREATE EXTERNAL TABLE JCFW.TW_CORP_INDAPPLY_CODE (
   TM_INTRVL_CD    INT,
   CMCC_BRANCH_CD    STRING,
   INDUSTRY_PRDCT_TYP    INT,
   INDUSTRY_PRDCT_NAM    STRING,
   APPLY_SCOPE    INT,
   EFF_MONTH    INT,
   CUST_TYP    INT,
   GROUP_NAM    STRING,
   GROUP_ID    STRING,
   STD_PRDCT_NBR    STRING,
   BUSI_TYP    INT,
   MMS_BUSI_TYP    INT,
   SP_CODE    STRING,
   SP_SERV_CD    STRING,
   SP_SUBBUSI_CD    STRING,
   CNTC_NAM    STRING,
   CNTC_NBR    STRING,
   BUSI_BRIEF    STRING
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/EDS/TW_CORP_INDAPPLY_CODE';

DROP TABLE IF EXISTS JCFW.TW_CORP_INDAPPLY_CODE_RAW;
CREATE EXTERNAL TABLE JCFW.TW_CORP_INDAPPLY_CODE_RAW (
   TM_INTRVL_CD    INT,
   CMCC_BRANCH_CD    STRING,
   GROUP_ID    STRING,
   INDUSTRY_PRDCT_TYP    INT,
   BUSI_TYP    INT,
   SP_CODE    STRING,
   SP_SERV_CD    STRING,
   SP_SUBBUSI_CD    STRING,
   INDUSTRY_PRDCT_NAM    STRING,
   APPLY_SCOPE    INT,
   EFF_MONTH    INT,
   CUST_TYP    INT,
   GROUP_NAM    STRING,
   STD_PRDCT_NBR    STRING,
   MMS_BUSI_TYP    INT,
   PASS_IND    STRING,
   RATIFIER    STRING,
   REMARK    STRING,
   RATIFY_DT    STRING,
   CNTC_NAM    STRING,
   CNTC_NBR    STRING,
   BUSI_BRIEF    STRING
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/EDS/TW_CORP_INDAPPLY_CODE_RAW';

DROP TABLE IF EXISTS JCFW.TW_CORP_INDAPPLY_CODE_PREVIEW;
CREATE EXTERNAL TABLE JCFW.TW_CORP_INDAPPLY_CODE_PREVIEW (
   TM_INTRVL_CD    INT,
   CMCC_BRANCH_CD    STRING,
   GROUP_ID    STRING,
   INDUSTRY_PRDCT_TYP    INT,
   BUSI_TYP    INT,
   SP_CODE    STRING,
   SP_SERV_CD    STRING,
   SP_SUBBUSI_CD    STRING,
   INDUSTRY_PRDCT_NAM    STRING,
   APPLY_SCOPE    INT,
   EFF_MONTH    INT,
   CUST_TYP    INT,
   GROUP_NAM    STRING,
   STD_PRDCT_NBR    STRING,
   MMS_BUSI_TYP    INT,
   PASS_IND    STRING,
   RATIFIER    STRING,
   REMARK    STRING,
   RATIFY_DT    STRING,
   CNTC_NAM    STRING,
   CNTC_NBR    STRING,
   BUSI_BRIEF    STRING
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/EDS/TW_CORP_INDAPPLY_CODE_PREVIEW';

DROP TABLE IF EXISTS JCFW.TW_CORP_INDAPPLY_CODE_RATIFY;
CREATE EXTERNAL TABLE JCFW.TW_CORP_INDAPPLY_CODE_RATIFY (
   TM_INTRVL_CD    INT,
   CMCC_BRANCH_CD    STRING,
   GROUP_ID    STRING,
   INDUSTRY_PRDCT_TYP    INT,
   BUSI_TYP    INT,
   SP_CODE    STRING,
   SP_SERV_CD    STRING,
   SP_SUBBUSI_CD    STRING,
   INDUSTRY_PRDCT_NAM    STRING,
   APPLY_SCOPE    INT,
   EFF_MONTH    INT,
   CUST_TYP    INT,
   GROUP_NAM    STRING,
   STD_PRDCT_NBR    STRING,
   MMS_BUSI_TYP    INT,
   PASS_IND    STRING,
   RATIFIER    STRING,
   REMARK    STRING,
   RATIFY_DT    STRING,
   CNTC_NAM    STRING,
   CNTC_NBR    STRING,
   BUSI_BRIEF    STRING
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/EDS/TW_CORP_INDAPPLY_CODE_RATIFY';

DROP TABLE IF EXISTS JCFW.TW_APN_USR_MO;
CREATE EXTERNAL TABLE JCFW.TW_APN_USR_MO (
   TM_INTRVL_CD    INT,
   CMCC_BRANCH_CD    STRING,
   USR_NBR    STRING,
   APN_NBR    STRING,
   B_NBR    STRING,
   DIR_TYP_CD    STRING,
   BRND_CD    SMALLINT,
   USR_TYP_CD    STRING,
   CALL_CNT    BIGINT,
   CALL_FLUX    BIGINT,
   MOB_FEE    DECIMAL(12,2),
   TOLL_FEE    DECIMAL(12,2),
   INF_FEE    DECIMAL(12,2),
   GPRS_DDD_OTC_FLUX    INT,
   GPRS_IDD_FLUX    INT,
   GPRS_IDD_OTC_FLUX    INT,
   GPRS_LOC_FLUX    BIGINT,
   GPRS_IPR_FLUX    BIGINT,
   GPRS_OPR_FLUX    BIGINT,
   GPAY_FLUX    BIGINT
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/EDS/TW_APN_USR_MO';

DROP TABLE IF EXISTS JCFW.TM_NB_MOBLOT_DTL_M;
CREATE EXTERNAL TABLE JCFW.TM_NB_MOBLOT_DTL_M (
   STAT_MO    INT,
   LOTRY_CD    SMALLINT,
   LOTRY_DTL_CD    SMALLINT,
   BUY_AMT    DECIMAL(16,2)
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_NB_MOBLOT_DTL_M';

DROP TABLE IF EXISTS JCFW.TM_NB_MOBLOT_DVLP_M;
CREATE EXTERNAL TABLE JCFW.TM_NB_MOBLOT_DVLP_M (
   STAT_MO    INT,
   CMCC_BRANCH_CD    STRING,
   LOTRY_TYP_CD    SMALLINT,
   TOT_USR_CNT    INT,
   ACT_USR_CNT    INT,
   NEW_USR_CNT    INT,
   TOT_BUY_AMT    DECIMAL(16,2),
   TOT_FEE    DECIMAL(16,2),
   DEVIDED_FEE    DECIMAL(16,2)
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_NB_MOBLOT_DVLP_M';

DROP TABLE IF EXISTS JCFW.TW_CORP_G3_MBR_MO;
CREATE EXTERNAL TABLE JCFW.TW_CORP_G3_MBR_MO (
   TM_INTRVL_CD    INT,
   CMCC_BRANCH_CD    STRING,
   USR_NBR    STRING,
   USR_ID    STRING,
   BIND_USR_NBR    STRING,
   BIND_USR_ID    STRING,
   PAY_GROUP_ID    STRING,
   PAY_CUST_ID    STRING,
   PAY_EBOX_ID    STRING,
   PAY_TYP_CD    SMALLINT,
   AMT_FEE    DECIMAL(14,2),
   FIX_FEE    DECIMAL(14,2),
   TF_AMT_FEE    DECIMAL(14,2),
   TF_FIX_FEE    DECIMAL(14,2),
   INF_INCOME    DECIMAL(14,2),
   USR_STS_CD    STRING,
   BASS_PRDCT_CD    STRING,
   INNET_DT    INT,
   CORP_PRDCT_CODE    STRING
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/EDS/TW_CORP_G3_MBR_MO';

DROP TABLE IF EXISTS JCFW.TW_CORP_APN_USEUSR_MO;
CREATE EXTERNAL TABLE JCFW.TW_CORP_APN_USEUSR_MO (
   TM_INTRVL_CD    INT,
   CMCC_BRANCH_CD    STRING,
   APN_NBR    STRING,
   USR_NBR    STRING,
   GROUP_ID    STRING,
   CORP_PRDCT_NBR    STRING,
   CHRG_GRP_IND    STRING,
   UP_CALL_CNT    BIGINT,
   DOWN_CALL_CNT    BIGINT,
   UP_CALL_FLUX    BIGINT,
   DOWN_CALL_FLUX    BIGINT,
   DEBET_FEE    DECIMAL(14,2),
   USR_GPRS_FEE    DECIMAL(14,2)
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/EDS/TW_CORP_APN_USEUSR_MO';

DROP TABLE IF EXISTS JCFW.TW_CORP_MEMBER_CRM_MO;
CREATE EXTERNAL TABLE JCFW.TW_CORP_MEMBER_CRM_MO (
   TM_INTRVL_CD    INT,
   GROUP_ID    STRING,
   USR_ID    STRING,
   USR_NBR    STRING,
   IMP_LVL_CD    STRING,
   GCUST_ID    STRING,
   ROLE_TYP    STRING,
   CREAT_DT    INT,
   MBR_STS_CD    STRING,
   STS_DT    INT,
   CMCC_BRANCH_CD    STRING,
   CRM_IND    SMALLINT,
   PLAT_TYP_CD    STRING
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/EDS/TW_CORP_MEMBER_CRM_MO';

DROP TABLE IF EXISTS JCFW.TW_CORP_BARGAIN_USR_MO;
CREATE EXTERNAL TABLE JCFW.TW_CORP_BARGAIN_USR_MO (
   TM_INTRVL_CD    INT,
   CMCC_BRANCH_CD    STRING,
   PRDCT_TYP    STRING,
   USR_NBR    STRING,
   CARD_TYP_CD    SMALLINT,
   BRND_CD    SMALLINT,
   PRDCT_TYP_NAM    STRING,
   VALID_IND    STRING,
   CM_TOT_FEE    DECIMAL(14,2),
   CM_VOC_FEE    DECIMAL(14,2),
   CM_VOC_CNT    INT,
   CM_SMS_CNT    INT,
   CM_GPRS_FLUX    BIGINT,
   CMNCT_2APN_IND    STRING,
   NEAR3_VOC_CNT    INT,
   NEAR3_SMS_CNT    INT,
   NEAR3_GPRS_FLUX    BIGINT,
   NEAR3_CMNCT_2APN_IND    STRING,
   INNET_IND    STRING,
   USR_STS_CD    STRING,
   DG_IND    STRING,
   DF_IND    STRING
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/EDS/TW_CORP_BARGAIN_USR_MO';

DROP TABLE IF EXISTS JCFW.TW_CORP_BARGAIN_REG_USR_M;
CREATE EXTERNAL TABLE JCFW.TW_CORP_BARGAIN_REG_USR_M (
   STAT_MO    INT,
   USR_NBR    STRING,
   GROUP_ID    STRING,
   GUSR_ID    STRING,
   CMCC_BRANCH_CD    STRING,
   BASS_PRDCT_CD    STRING,
   CORP_PRDCT_CODE    STRING,
   BRND_CD    SMALLINT,
   DICT_CD    STRING,
   CM_VOC_BUSI_CNT    INT,
   CM_SMS_BUSI_CNT    INT,
   CM_GPRS_BUSI_CNT    BIGINT,
   CM_MMS_BUSI_CNT    INT,
   CM_BILL_INC    DECIMAL(14,2),
   CM_NB_INC    DECIMAL(14,2),
   KPI_MBR_IND    STRING,
   CUST_NAM    STRING,
   DF_IND    STRING,
   PRDCT_NAM    STRING
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/EDS/TW_CORP_BARGAIN_REG_USR_M';

DROP TABLE IF EXISTS JCFW.TW_F_USR_COST_TRANS_DIV_M;
CREATE EXTERNAL TABLE JCFW.TW_F_USR_COST_TRANS_DIV_M (
   STAT_MO    INT,
   USR_NBR    STRING,
   BADBIL    DECIMAL(20,12),
   BUSI_FEE    DECIMAL(20,12),
   INNER_SETL_FEE    DECIMAL(20,12),
   AOASETL_FEE    DECIMAL(20,12),
   ROMA_SETL_FEE    DECIMAL(20,12),
   TERM_REWARD    DECIMAL(20,12),
   BASE_REWARD    DECIMAL(20,12),
   INTEGRAL_DLVR    DECIMAL(20,12),
   INTEGRAL_XCHG    DECIMAL(20,12),
   ZERO_SELL_FEE    DECIMAL(20,12),
   SYS_CHRG_FEE    DECIMAL(20,12),
   RTN_PROC_FEE    DECIMAL(20,12),
   USR_INNET_FEE    DECIMAL(20,12),
   CARD_FEE    DECIMAL(20,12),
   CALLFEE_SRV_FEE    DECIMAL(20,12),
   CONTRACT_SRV_FEE    DECIMAL(20,12),
   OTH_SRV_FEE    DECIMAL(20,12),
   SP_SETL_FEE    DECIMAL(20,12)
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/EDS/TW_F_USR_COST_TRANS_DIV_M';

DROP TABLE IF EXISTS JCFW.TW_F_CUST_INC_DIV_M;
CREATE EXTERNAL TABLE JCFW.TW_F_CUST_INC_DIV_M (
   USR_NBR    STRING,
   CARD_SELL_DIS_FEE    DECIMAL(20,12),
   SP_SETL_FEE    DECIMAL(20,12),
   CARD_MAKE_FEE    DECIMAL(20,12),
   SELL_ORG_WORK_FEE    DECIMAL(20,12),
   AD_PRGD_FEE    DECIMAL(20,12),
   CARD_REWARD    DECIMAL(20,12),
   STAR_AWARD_FEE    DECIMAL(20,12),
   PRTL_SUBSY_FEE    DECIMAL(20,12),
   MNG_FEE    DECIMAL(20,12),
   CNSLT_FEE    DECIMAL(20,12)
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/EDS/TW_F_CUST_INC_DIV_M';

DROP TABLE IF EXISTS JCFW.TW_F_PRDCT_BUSI_DIV_M;
CREATE EXTERNAL TABLE JCFW.TW_F_PRDCT_BUSI_DIV_M (
   STAT_MO    INT,
   USR_NBR    STRING,
   DEPR_DIV_FEE    DECIMAL(20,12),
   NET_MNG_DIV_FEE    DECIMAL(20,12),
   BUSI_SUPP_DIV_FEE    DECIMAL(20,12),
   DEBET_DUR    BIGINT,
   GPRS_FLUX    BIGINT,
   SMS_CNT    INT,
   MMS_CNT    INT
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/EDS/TW_F_PRDCT_BUSI_DIV_M';

DROP TABLE IF EXISTS JCFW.TR_TERM_INF_M;
CREATE EXTERNAL TABLE JCFW.TR_TERM_INF_M (
   TERM_MDL_ID    INT,
   TERM_TYP    STRING,
   PROD_CORP    STRING,
   TERM_BRND_NAM    STRING,
   TERM_BRND_NAM_EN    STRING,
   TERM_MDL_NAM    STRING,
   TERM_MDL_NCKNM    STRING,
   TERM_SIZE    STRING,
   TERM_LEN    DECIMAL(8,2),
   TERM_WDTH    DECIMAL(8,2),
   TERM_HGT    DECIMAL(8,2),
   TERM_WGT    DECIMAL(8,2),
   TERM_STYLE    STRING,
   TERM_COLR    STRING,
   MKT_PSTN    STRING,
   PRTCL_PRC    INT,
   TERM_ABL    STRING,
   CERT_IND    STRING,
   PERMT_DT    INT,
   STOP_PROD_DT    INT,
   OS_UA_STR    STRING,
   CPU_CNT    INT,
   CPU_BRND    STRING,
   CPU_MDL    STRING,
   CPU_ARM_VER    STRING,
   CPU_FREQ    STRING,
   GPU_BRND    STRING,
   GPU_MDL    STRING,
   MEM_SIZE    STRING,
   RAM_SIZE    STRING,
   ROM_SIZE    STRING,
   ROM_IDLE_SIZE    STRING,
   STOR_TYP    STRING,
   STOR_MAX_SIZE    STRING,
   PHNBK_SIZE    STRING,
   PHNBK_CARD_IND    STRING,
   PHNBK_GRP_IND    STRING,
   STACK_SIZE    STRING,
   JARPKG_SIZE    STRING,
   MAXOBJ_SIZE    STRING,
   XPND_CARD_IND    STRING,
   OS_TYP    STRING,
   OS_VER    STRING,
   OS_SUBVER    STRING,
   SFTWE_VER    STRING,
   OTH_SFTWE_VER    STRING,
   VIEW_MTHD    STRING,
   HDWE_VER    STRING,
   DVLP_PLTFM    STRING,
   PLTFM_BRND    STRING,
   PLTFM_VER    STRING,
   DGT_BSBND    STRING,
   PHYS_PRTCL_SFTWE    STRING,
   ANLG_BSBND    STRING,
   SMTPHN_IND    STRING,
   CHAR_SET    STRING,
   CHAR_ENCD    STRING,
   CHAR_LANG    STRING,
   LRG_CHAR_SIZE    STRING,
   MID_CHAR_SIZE    STRING,
   SML_CHAR_SIZE    STRING,
   FLLT_VER    STRING,
   FLLT_PLUGIN_IND    STRING,
   FLLT_SCR_IND    STRING,
   FLLT_WPAPR_IND    STRING,
   FLLT_RINGTN_IND    STRING,
   FL_CALL_IND    STRING,
   FL_SMS_IND    STRING,
   FL_AUDIO_FMT    STRING,
   FL_VIDEO_FMT    STRING,
   MAIL_PRTCL    STRING,
   DOC_TYP    STRING,
   BLDIN_APP    STRING,
   EKA_CERT_IND    STRING,
   WAP_COMPRS_IND    STRING,
   UMA_IND    STRING,
   ADHN_STS_IND    STRING,
   ACTV_STS_IND    STRING,
   DATA_TRNSMS_IND    STRING,
   HANDWRT_IND    STRING,
   TCH_SCR_TYP    STRING,
   MUTI_TCH_IND    STRING,
   SCR_CNT    STRING,
   SCR_SIZE    STRING,
   DSPL_SIZE    STRING,
   SCR_RSVL_WDTH    STRING,
   SCR_RSVL_LEN    STRING,
   SCR_MTRL    STRING,
   COLR_DPTH    STRING,
   CHAR_SIZE    STRING,
   CHAR_SIZE_WDTH    STRING,
   CHAR_SIZE_LEN    STRING,
   ROW_CHAR_CNT    INT,
   IP_CHAR_SET    STRING,
   OP_CHAR_SET    STRING,
   CHRG_INTF    STRING,
   HEADPHN_INTF    STRING,
   CHRG_IP    STRING,
   BTR_CPCY    STRING,
   STNDBY_TM_DESC    STRING,
   TALK_TM_DESC    STRING,
   KEYBD_TYP    STRING,
   SOFTKEY_CNT    INT,
   SIM_CNT    INT,
   TCTW_IND    STRING,
   DBL_CRD_MDE    STRING,
   OTA_IND    STRING,
   SIM_VLT    STRING,
   CAM_CNT    INT,
   CAM_PIXEL    STRING,
   MACRO_LENS_IND    STRING,
   FILLLIGHT_CNT    INT,
   FLASHLIGHT_CNT    INT,
   IMAG_RSVL    STRING,
   CAM_IND    STRING,
   PHOT_IMG_FMT    STRING,
   VIDEO_RSVL    STRING,
   VIDEO_FPS    INT,
   SMS_FUNC_IND    STRING,
   SMS_GRP_SND_IND    STRING,
   LNG_SMS_IND    STRING,
   FSMS_IND    STRING,
   SMS_RECPT_IND    STRING,
   SMS_SGN    STRING,
   MMS_IND    STRING,
   MMS_VER    STRING,
   MMS_SIZE    STRING,
   MMS_IMG_RSVL    STRING,
   MMS_DFLT_CHAR_SET    STRING,
   MMS_CHAR_SET    STRING,
   MMS_SMIL_IND    STRING,
   MMS_MEDIA_IND    STRING,
   MMS_FRAM_CNT    INT,
   MMS_HPLNK_IND    STRING,
   MMS_PER_WORDS    STRING,
   ELCTR_DICT_IND    STRING,
   REC_FUNC_IND    STRING,
   CLOS_ALRM_IND    STRING,
   WAP_VER    STRING,
   WAP_CHAR_SET    STRING,
   WML_SCRIPT_VER    STRING,
   WML_VER    STRING,
   WTA_VER    STRING,
   OMA_DRM_VER    STRING,
   DRM_FUNC_SET    STRING,
   DRM_TRNS_MTHD    STRING,
   OMA_DWLD_IND    STRING,
   OMA_CLI_VER    STRING,
   OMA_DEVC    STRING,
   OMA_DATA    STRING,
   WAP_PUSH_IND    STRING,
   PUSH_MSG    STRING,
   NET_MDE_TYP    STRING,
   GSM_IND    STRING,
   WCDMA_IND    STRING,
   TDSCDMA_IND    STRING,
   NET_MDE    STRING,
   NET_STD_GEN    STRING,
   NET_FREQ    STRING,
   CARRY_FREQ_SEG    STRING,
   GPRS_IND    STRING,
   EDGE_FUNC_IND    STRING,
   USSD_IND    STRING,
   BLUETOOTH_IND    STRING,
   BT_VER    STRING,
   BLUETOOTH_PRTCL    STRING,
   WIFI_IND    STRING,
   WLAN_PRTCL    STRING,
   INFRA_RED_IND    STRING,
   USB_VER    STRING,
   MODEM_IND    STRING,
   HDMI_TYP    STRING,
   HDMI_VER    STRING,
   APN_IND    STRING,
   APN_AUTO_IND    STRING,
   LCL_LNL_MDE    STRING,
   GPS_IND    STRING,
   PS_CS_IND    STRING,
   PS_CS_SPD    STRING,
   SYNCML_IND    STRING,
   IMPS_IND    STRING,
   WEB_NAM    STRING,
   WEB_VER    STRING,
   HTML_VER    STRING,
   XHTML_VER    STRING,
   WEB_TAB_IND    STRING,
   WEB_FRAME_IND    STRING,
   WEB_JA_IND    STRING,
   WEB_JA_VER    STRING,
   WEB_JS_IND    STRING,
   WEB_JS_VER    STRING,
   JAVA_IND    STRING,
   MIDP_VER    STRING,
   CLDC_VER    STRING,
   JAVA_PKG    STRING,
   JAVA_PRTCL    STRING,
   IMG_FMT    STRING,
   MAX_JPEG_SIZE    STRING,
   MAX_PNG_SIZE    STRING,
   STDBY_IMG_FMT    STRING,
   STDBY_IMG_SIZE    STRING,
   STDBY_IMG_SIZE_WDTH    STRING,
   STDBY_IMG_SIZE_LEN    STRING,
   SCRSV_IMG_FMT    STRING,
   SCRSV_IMG_SIZE    STRING,
   SCRSV_IMG_SIZE_WDTH    STRING,
   SCRSV_IMG_SIZE_LEN    STRING,
   AUDIO_FMT    STRING,
   CHORD_CNT    INT,
   BELL_BYTE_SIZE    STRING,
   SPKEAR_IND    STRING,
   MP3_IND    STRING,
   POC_IND    STRING,
   MEDIA_PLAY_TYP    STRING,
   MEDIA_FMT    STRING,
   MEDIA_DWLD_IND    STRING,
   MEDIA_AUDIO_FMT    STRING,
   MEDIA_VIDEO_FMT    STRING,
   VIDEO_FMT    STRING,
   DNMC_MEM_IND    STRING,
   VIDEO_STACK_SIZE    STRING,
   DGTL_CPRT_TYP    STRING,
   HTTP_DWLD    STRING,
   OMA_DWLD    STRING,
   ACC_BELL    STRING,
   VIDEO_ENCD    STRING,
   AUDIO_ENCD    STRING,
   GRVTY_IND    STRING,
   ELCTR_CMPS_IND    STRING,
   DISTN_SNS_IND    STRING,
   RDL_SNS_IND    STRING,
   ACCL_SNS_IND    STRING,
   GRSCP_SNS_IND    STRING,
   ACCL_3D_IND    STRING,
   RADIO_FUNC    STRING,
   RFSIM_IND    STRING,
   NFC_IND    STRING,
   MP_SMS_IND    STRING,
   USAT_MENU    STRING,
   FETION_IND    STRING,
   MOBILE_STOCK_IND    STRING,
   MUSIC_WALKMAN_IND    STRING,
   PHNBK_MNG_IND    STRING,
   GPLUS_GAME_IND    STRING,
   MOBILE_NVGT_IND    STRING,
   MAIL_139_IND    STRING,
   MOBILE_READ_IND    STRING,
   MOBILE_VIDEO_IND    STRING,
   MM_CLI_IND    STRING,
   CMMB_IND    STRING,
   ANMT_CTN_IND    STRING,
   WRLS_CITY_IND    STRING,
   GAME_IND    STRING,
   THRD_UC_IND    STRING,
   THRD_QQ_IND    STRING,
   TDLTE_IND    STRING,
   FDLTE_IND    STRING
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/REF/TR_TERM_INF_M';

DROP TABLE IF EXISTS JCFW.TR_TAC_TERM_M;
CREATE EXTERNAL TABLE JCFW.TR_TAC_TERM_M (
   TAC    STRING,
   TERM_MDL_ID    INT,
   TERM_DS_ID    INT,
   TERM_MDL_KEY    INT,
   IS_DFLT    STRING,
   IS_CHK    STRING,
   REC_FLG    STRING,
   USER_ID    STRING,
   EFF_DT    INT,
   EFF_TM    STRING,
   INV_DT    INT,
   INV_TM    STRING,
   CURR_FLG    STRING,
   UPDT_FLG    STRING,
   REMARK    STRING
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/REF/TR_TAC_TERM_M';

DROP TABLE IF EXISTS JCFW.TW_F_PRDCT_USE_M;
CREATE EXTERNAL TABLE JCFW.TW_F_PRDCT_USE_M (
   STAT_MO    INT,
   USR_NBR    STRING,
   PRDCT_ELMT_CD    STRING,
   CMCC_BRANCH_CD    STRING,
   USE_CNT    BIGINT
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/EDS/TW_F_PRDCT_USE_M';

DROP TABLE IF EXISTS JCFW.TR_TERM_PRDCT_M;
CREATE EXTERNAL TABLE JCFW.TR_TERM_PRDCT_M (
   TAC    STRING,
   TERM_BRND_NAM    STRING,
   TERM_BRND_NAM_EN    STRING,
   TERM_MDL_NAM    STRING,
   TERM_TYP    SMALLINT,
   OS_TYP_CD    STRING,
   CUSTM_TERM_TYP    SMALLINT,
   INTELL_TERM_IND    STRING,
   TYJ_INTELL_TERM_IND    STRING,
   GSM_IND    STRING,
   GPRS_IND    STRING,
   WLAN_IND    STRING,
   WCDMA_IND    STRING,
   TDSCDMA_IND    STRING,
   TYJ_TDSCDMA_IND    STRING,
   TDLTE_IND    STRING,
   TYJ_TDLTE_IND    STRING,
   FDLTE_IND    STRING,
   TERM_STANDARD_TYP    STRING,
   TAC_SOURCE    STRING,
   CDMA2000_IND    STRING,
   TCTW_IND    STRING,
   PRTCL_PRC    INT,
   SCR_SIZE    STRING,
   BACK_PIXEL    BIGINT,
   SUPPORT_VOLTE_IND    STRING,
   TCH_SCR_TYP    STRING,
   PERMT_DT    INT,
   HANDWRT_IND    STRING
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='&&','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/REF/TR_TERM_PRDCT_M';

DROP TABLE IF EXISTS JCFW.TW_PERS_MIN_CNSM_M;
CREATE EXTERNAL TABLE JCFW.TW_PERS_MIN_CNSM_M (
   STAT_MO    INT,
   USR_NBR    STRING,
   N1_MIN_CNSM_FEE    DECIMAL(10,2),
   N2_MIN_CNSM_FEE    DECIMAL(10,2),
   N3_MIN_CNSM_FEE    DECIMAL(10,2)
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/EDS/TW_PERS_MIN_CNSM_M';

DROP TABLE IF EXISTS JCFW.TM_139_MAIL_USR_AGGR_MO;
CREATE EXTERNAL TABLE JCFW.TM_139_MAIL_USR_AGGR_MO (
   TM_INTRVL_CD    INT,
   BRND_CD    SMALLINT,
   CMCC_BRANCH_CD    STRING,
   REACH_USRCNT    INT,
   NCKNAM_REG_USRCNT    INT,
   SILENT_USRCNT    INT,
   LOST_USRCNT    INT,
   TRM_REG_USRCNT    INT,
   SMS_REG_USRCNT    INT,
   WEB_REG_USRCNT    INT,
   WAP_REG_USRCNT    INT,
   OTH_REG_USRCNT    INT,
   PUSHMAIL_USRCNT    INT,
   PAUD_ACT_USRCNT    INT,
   WAP_0FLUX_ACT_USRCNT    INT,
   HI_SAMEIP_WEP_ACTUSR_CNT    INT,
   INV_USRCNT    INT,
   AUD_UNCN_USRCNT    INT
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_139_MAIL_USR_AGGR_MO';

DROP TABLE IF EXISTS JCFW.TM_FETION_USR_MO;
CREATE EXTERNAL TABLE JCFW.TM_FETION_USR_MO (
   TM_INTRVL_CD    INT,
   CMCC_BRANCH_CD    STRING,
   BRND_CD    SMALLINT,
   USR_TYP_CD    SMALLINT,
   OPEN_REQSRS_CD    STRING,
   CLOSE_REQSRS_CD    STRING,
   LASTMO_USR_CNT    INT,
   CURRMO_NEWUSR_CNT    INT,
   TOT_USR_CNT    INT,
   FRD_TOTAL_CNT    INT,
   HAVE_FRD_USRCNT    INT,
   JNGRP_TOTAL_CNT    INT,
   HAVE_JNGRP_USRCNT    INT
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_FETION_USR_MO';

DROP TABLE IF EXISTS JCFW.TM_FETION_USE_MO;
CREATE EXTERNAL TABLE JCFW.TM_FETION_USE_MO (
   TM_INTRVL_CD    INT,
   CMCC_BRANCH_CD    STRING,
   BRND_CD    SMALLINT,
   PKG_CD    SMALLINT,
   PC_USR_CNT    INT,
   SMS_USR_CNT    INT,
   IVR_USR_CNT    INT,
   WAP_USR_CNT    INT,
   MOB_USR_CNT    INT,
   TOT_USR_CNT    INT,
   LOW_ACTV_USR_CNT    INT,
   HI_ACTV_USR_CNT    INT,
   UP_SMS_CNT    INT,
   DOWN_SMS_CNT    INT,
   CALL_DUR    INT,
   PCMOB_ACTUSR_CNT    INT,
   UP_SMS_USRCNT    INT,
   DOWN_SMS_USRCNT    INT,
   TOTAL_SMS_USRCNT    INT,
   MOB_GPRSFLUX_UND50K_USRCNT    INT,
   MOB_NOFRD_ACTUSRCNT    INT,
   PC_NOFRD_ACTUSRCNT    INT,
   SENDMSG_TOTAL_CNT    BIGINT,
   HAVE_SENDMSG_USRCNT    INT,
   MOB_NEEDRDUC_USRCNT    INT,
   PC_NEEDRDUC_USRCNT    INT,
   MOB_GPRSFLUX_ZERO_USRCNT    INT,
   MOB_SMS_ZERO_USRCNT    INT,
   PC_SMS_ZERO_USRCNT    INT,
   PC_ACTV_USRCNT_REFAUD    INT,
   MOB_ACTV_USRCNT_REFAUD    INT,
   ACTV_USRCNT_REFAUD    INT,
   PC_ACTV_USRCNT_AUD    INT,
   MOB_ACTV_USRCNT_AUD    INT,
   PCMOB_0SMS_0FRD_USRCNT    INT,
   PC_0SMS_0FRD_USRCNT    INT,
   MOB_0SMS_0FRD_USRCNT    INT,
   INV_USRCNT    INT,
   AUD_UNCN_USRCNT    INT
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_FETION_USE_MO';

DROP TABLE IF EXISTS JCFW.TW_BIXF_CMNCT_USR_MO;
CREATE EXTERNAL TABLE JCFW.TW_BIXF_CMNCT_USR_MO (
   TM_INTRVL_CD    INT,
   USR_NBR    STRING,
   BRND_CD    SMALLINT,
   PKG_CD    SMALLINT,
   ACT_CALLUSR_IND    STRING,
   CALLUSR_IND    STRING,
   TD_DEBET_DUR    INT,
   TD_GPRS_FLUX    INT,
   MO_ARPU_FEE    DECIMAL(10,2),
   LOCK_MH_LOST_IND    STRING,
   CMCC_BRANCH_CD    STRING,
   MON_NEW_CMNCT_IND    STRING,
   ACTV_USR_IND    STRING,
   FST_ACTV_DT    INT,
   LAST_ACTV_DT    INT,
   ACTV_DAY_CNT    INT,
   SMS_UP_CNT    INT,
   ACTVCALL_CNT    INT,
   BYCALL_CNT    INT,
   GSM_GPRS_FLUX    INT,
   T_GPRS_FLUX    INT
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/EDS/TW_BIXF_CMNCT_USR_MO';

DROP TABLE IF EXISTS JCFW.TW_SHL_AREA_USE_DTL_MO;
CREATE EXTERNAL TABLE JCFW.TW_SHL_AREA_USE_DTL_MO (
   TM_INTRVL_CD    INT,
   USR_NBR    STRING,
   CMCC_BRANCH_CD    STRING,
   BRND_CD    SMALLINT,
   ARPU    DECIMAL(10,2),
   MSG_CNT    INT,
   SCHOOL_AREA_CALL_CNT    INT,
   SCHOOL_AREA_CALL_DUR    INT,
   SCHOOL_AREA_ACTV_DAYS    INT,
   SCHOOL_FIRST_LOCAL_CD    STRING,
   SCHOOL_FIRST_CELL_CD    STRING,
   FIRST_CELL_CALL_CNT    INT,
   FIRST_CELL_CALL_DUR    INT,
   CALL_CNT    INT,
   CALL_DUR    BIGINT,
   GPRS_FLUX    BIGINT,
   SCHOOL_CD    STRING,
   TP_STUDENT_FLAG    INT,
   TP_SCHOOL_CD    STRING
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/EDS/TW_SHL_AREA_USE_DTL_MO';

DROP TABLE IF EXISTS JCFW.TM_F_INOUT_NET_SETL_M;
CREATE EXTERNAL TABLE JCFW.TM_F_INOUT_NET_SETL_M (
   STAT_MO    INT,
   CMCC_BRANCH_CD    STRING,
   DISTICT_NAM    STRING,
   USR_TYP_NAM    STRING,
   OBJ_TYP_NAM    STRING,
   SETL_TYP_NAM    STRING,
   SETL_OBJ_NAM    STRING,
   CALL_TYP_NAM    STRING,
   STAT_TYP_NAM    STRING,
   DEB_DUR    BIGINT,
   MOB_FEE    DECIMAL(18,2),
   TOLL_FEE    DECIMAL(18,2),
   PAY_CMCC_CALL_FEE    DECIMAL(18,2),
   PAY_CMCC_TOLL_FEE    DECIMAL(18,2),
   REC_CMCC_CALL_FEE    DECIMAL(18,2),
   REC_CMCC_TOLL_FEE    DECIMAL(18,2)
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_F_INOUT_NET_SETL_M';

DROP TABLE IF EXISTS JCFW.TM_F_LOCALFEE_FC_M;
CREATE EXTERNAL TABLE JCFW.TM_F_LOCALFEE_FC_M (
   STAT_MO    INT,
   CMCC_BRANCH_CD    STRING,
   DISTICT_NAM    STRING,
   USR_TYP_NAM    STRING,
   BUSI_NAM    STRING,
   SETL_TYP_NAM    STRING,
   TOT_LOCAL_FEE    DECIMAL(16,2),
   UNWOFF_FEE    DECIMAL(16,2),
   SELF_COMP_DIV_FEE    DECIMAL(16,2),
   COOPR_DIV_FEE    DECIMAL(16,2)
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_F_LOCALFEE_FC_M';

DROP TABLE IF EXISTS JCFW.TM_F_BOSS_USER_XZ_M;
CREATE EXTERNAL TABLE JCFW.TM_F_BOSS_USER_XZ_M (
   STAT_MO    INT,
   CMCC_BRANCH_CD    STRING,
   DISTICT_NAM    STRING,
   USR_TYP_NAM    STRING,
   XZ_TYP_NAM    STRING,
   XZ_DTL_NAM    STRING,
   TOTAL_FEE    DECIMAL(16,2)
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_F_BOSS_USER_XZ_M';

DROP TABLE IF EXISTS JCFW.TM_JF_SP_MO;
CREATE EXTERNAL TABLE JCFW.TM_JF_SP_MO (
   TM_INTRVL_CD    INT,
   SP_BUSI_TYP_1    SMALLINT,
   INF_FEE    DECIMAL(16,2),
   SP_INCM    DECIMAL(16,2),
   CMCC_INCM    DECIMAL(16,2),
   SP_INVC_FEE    DECIMAL(16,2)
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES ('field.delim'='&','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_JF_SP_MO';

DROP TABLE IF EXISTS JCFW.TM_JF_SP_OTH_MO;
CREATE EXTERNAL TABLE JCFW.TM_JF_SP_OTH_MO (
   TM_INTRVL_CD    INT,
   SP_BUSI_TYP_2    SMALLINT,
   SP_CNT    INT,
   CMNCT_FEE    DECIMAL(16,2),
   BCK_FEE    DECIMAL(16,2),
   GIFT_FEE    DECIMAL(16,2),
   SP_INCM    DECIMAL(16,2),
   DIV_INF_FEE    DECIMAL(16,2),
   SP_INVC_FEE    DECIMAL(16,2),
   TOT_INF_FEE    DECIMAL(16,2),
   CMCC_INCM    DECIMAL(16,2)
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES ('field.delim'='&','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_JF_SP_OTH_MO';

DROP TABLE IF EXISTS JCFW.TM_JF_SP_SMS_MO;
CREATE EXTERNAL TABLE JCFW.TM_JF_SP_SMS_MO (
   TM_INTRVL_CD    INT,
   SP_BUSI_TYP_2    SMALLINT,
   SP_CNT    INT,
   UP_CMNCT_FEE    DECIMAL(16,2),
   BAL_CMNCT_FEE    DECIMAL(16,2),
   TOT_INF_FEE    DECIMAL(16,2),
   NOHOST_FEE    DECIMAL(16,2),
   GIFT_FEE    DECIMAL(16,2),
   DIV_INF_FEE    DECIMAL(16,2),
   CMCC_INCM    DECIMAL(16,2),
   SP_INCM    DECIMAL(16,2),
   SP_INVC_FEE    DECIMAL(16,2)
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES ('field.delim'='&','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_JF_SP_SMS_MO';

DROP TABLE IF EXISTS JCFW.TM_JF_SP_MMS_MO;
CREATE EXTERNAL TABLE JCFW.TM_JF_SP_MMS_MO (
   TM_INTRVL_CD    INT,
   SP_BUSI_TYP_2    SMALLINT,
   SP_CNT    INT,
   UP_CMNCT_FEE    DECIMAL(16,2),
   BAL_CMNCT_FEE    DECIMAL(16,2),
   TOT_INF_FEE    DECIMAL(16,2),
   NOHOST_FEE    DECIMAL(16,2),
   GIFT_FEE    DECIMAL(16,2),
   DIV_INF_FEE    DECIMAL(16,2),
   CMCC_INCM    DECIMAL(16,2),
   SP_INCM    DECIMAL(16,2),
   SP_INVC_FEE    DECIMAL(16,2)
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES ('field.delim'='&','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_JF_SP_MMS_MO';

DROP TABLE IF EXISTS JCFW.TM_MWSMS_NOTBALA_MO;
CREATE EXTERNAL TABLE JCFW.TM_MWSMS_NOTBALA_MO (
   TM_INTRVL_CD    INT,
   BUSCODE    STRING,
   ADDRESS_CODE    STRING,
   SP_CODE    STRING,
   SP_NAM    STRING,
   NOTBAL_CMNCT_CNT    INT,
   NOTBAL_CMNCT_FEE    DECIMAL(14,2)
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES ('field.delim'='&','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_MWSMS_NOTBALA_MO';

DROP TABLE IF EXISTS JCFW.TM_NB_SMS_BUSI_DTL_SRC_M;
CREATE EXTERNAL TABLE JCFW.TM_NB_SMS_BUSI_DTL_SRC_M (
   DEBET_MO    INT,
   CMCC_BRANCH_CD    STRING,
   DISTICT_CD    STRING,
   USR_TYP_NAM    STRING,
   PAY_TYP_NAM    STRING,
   SMS_TYP_NAM    STRING,
   BUSI_NAM    STRING,
   BUSI_ATR_NAM    STRING,
   BUSI_TYP_NAM    STRING,
   PORT_NO    STRING,
   BUSI_SCOPE_NAM    STRING,
   SUBBUSI_CD    STRING,
   DEVIDED_FEE    DECIMAL(14,2),
   COOPR_DIV_FEE    DECIMAL(14,2),
   MON_SERV_FEE    DECIMAL(14,2),
   INF_FEE    DECIMAL(14,2),
   GIFT_CALL_FEE    DECIMAL(14,2),
   UP_CARRY_FEE    DECIMAL(14,2),
   DOWN_CARRY_FEE    DECIMAL(14,2),
   SMS_UP_CNT    INT,
   SMS_DOWN_CNT    INT
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='&&','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_NB_SMS_BUSI_DTL_SRC_M';

DROP TABLE IF EXISTS JCFW.TM_NB_SMS_BUSI_SRC_M;
CREATE EXTERNAL TABLE JCFW.TM_NB_SMS_BUSI_SRC_M (
   DEBET_MO    INT,
   CMCC_BRANCH_CD    STRING,
   DISTICT_CD    STRING,
   USR_TYP_NAM    STRING,
   SMS_TYP_NAM    STRING,
   BUSI_SCOPE_NAM    STRING,
   BUSI_ATR_NAM    STRING,
   BUSI_TYP_NAM    STRING,
   DEVIDED_FEE    DECIMAL(14,2),
   COOPR_DIV_FEE    DECIMAL(14,2),
   MON_SERV_FEE    DECIMAL(14,2),
   INF_FEE    DECIMAL(14,2),
   GIFT_CALL_FEE    DECIMAL(14,2),
   UP_CARRY_FEE    DECIMAL(14,2),
   DOWN_CARRY_FEE    DECIMAL(14,2),
   SMS_UP_CNT    INT,
   SMS_DOWN_CNT    INT
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='&&','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_NB_SMS_BUSI_SRC_M';

DROP TABLE IF EXISTS JCFW.TM_CHRGCARD_CHRG_MO;
CREATE EXTERNAL TABLE JCFW.TM_CHRGCARD_CHRG_MO (
   TM_INTRVL_CD    INT,
   CMCC_BRANCH_CD    STRING,
   BRND_CD    INT,
   PAR_VALUE    DECIMAL(16,2),
   CHRG_CNT    INT,
   CHRG_AMT    DECIMAL(16,2)
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_CHRGCARD_CHRG_MO';

DROP TABLE IF EXISTS JCFW.TW_PERS_ARPUSNAP_USR_Y;
CREATE EXTERNAL TABLE JCFW.TW_PERS_ARPUSNAP_USR_Y (
   STAT_YEAR    INT,
   USR_NBR    STRING,
   USR_ID    STRING,
   BRND_CD    SMALLINT,
   CMCC_BRANCH_CD    STRING,
   ARPU50_SNAP_USR_IND    STRING,
   ARPU120_SNAP_USR_IND    STRING,
   VPMN50_USR_IND    STRING,
   VPMN120_USR_IND    STRING
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/EDS/TW_PERS_ARPUSNAP_USR_Y';

DROP TABLE IF EXISTS JCFW.TW_CORP_M2M_PRDCT_MO;
CREATE EXTERNAL TABLE JCFW.TW_CORP_M2M_PRDCT_MO (
   TM_INTRVL_CD    INT,
   CMCC_BRANCH_CD    STRING,
   APN_NBR    STRING,
   CUST_NAM    STRING,
   GROUP_ID    STRING,
   INDUS_TYP_NAM    STRING,
   APPL_TYP_NAM    STRING,
   CORP_PRDCT_NAM    STRING,
   CORP_PRDCT_NBR    STRING,
   RPT_INDUS_TYP_NAM    STRING
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/EDS/TW_CORP_M2M_PRDCT_MO';

DROP TABLE IF EXISTS JCFW.TM_F_BILL_INCOME_SUM_M;
CREATE EXTERNAL TABLE JCFW.TM_F_BILL_INCOME_SUM_M (
   STAT_MO    INT,
   CMCC_BRANCH_CD    STRING,
   DISTICT_NAM    STRING,
   USR_TYP_NAM    STRING,
   INCM_CLASS_NAM    STRING,
   INCM_DTL_NAM    STRING,
   INCM_FEE    DECIMAL(16,2)
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_F_BILL_INCOME_SUM_M';

DROP TABLE IF EXISTS JCFW.TM_F_BILL_INCOME_FC_M;
CREATE EXTERNAL TABLE JCFW.TM_F_BILL_INCOME_FC_M (
   STAT_MO    INT,
   CMCC_BRANCH_CD    STRING,
   DISTICT_NAM    STRING,
   USR_TYP_NAM    STRING,
   SETL_COMM_NAM    STRING,
   SETL_SCOPE_NAM    STRING,
   BUSI_TYP_NAM    STRING,
   COOPR_DIV_FEE    DECIMAL(16,2),
   SELF_COMP_DIV_FEE    DECIMAL(16,2)
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_F_BILL_INCOME_FC_M';

DROP TABLE IF EXISTS JCFW.TM_F_BOSS_ACCT_CHANGE_M;
CREATE EXTERNAL TABLE JCFW.TM_F_BOSS_ACCT_CHANGE_M (
   STAT_MO    INT,
   CMCC_BRANCH_CD    STRING,
   DISTICT_NAM    STRING,
   USR_TYP_NAM    STRING,
   CHANGE_TYP_NAM    STRING,
   ACCT_CHANGE_RESION    STRING,
   TOTAL_FEE    DECIMAL(16,2)
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_F_BOSS_ACCT_CHANGE_M';

DROP TABLE IF EXISTS JCFW.TM_F_BAD_DEBTS_ACCRUE_M;
CREATE EXTERNAL TABLE JCFW.TM_F_BAD_DEBTS_ACCRUE_M (
   STAT_MO    INT,
   CMCC_BRANCH_CD    STRING,
   DISTICT_NAM    STRING,
   USR_TYP_NAM    STRING,
   ACCT_TYP_NAM    STRING,
   BAD_DEBTS_TYP_NAM    STRING,
   TOTAL_FEE    DECIMAL(16,2)
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_F_BAD_DEBTS_ACCRUE_M';

DROP TABLE IF EXISTS JCFW.TM_F_BAD_DEBTS_REBACK_M;
CREATE EXTERNAL TABLE JCFW.TM_F_BAD_DEBTS_REBACK_M (
   STAT_MO    INT,
   CMCC_BRANCH_CD    STRING,
   DISTICT_NAM    STRING,
   USR_TYP_NAM    STRING,
   ACCT_TYP_NAM    STRING,
   REBACK_TYP_NAM    STRING,
   BAD_DEBTS_DTL_NAM    STRING,
   TOTAL_FEE    DECIMAL(16,2)
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_F_BAD_DEBTS_REBACK_M';

DROP TABLE IF EXISTS JCFW.TM_NET_PLAN_CELL_M;
CREATE EXTERNAL TABLE JCFW.TM_NET_PLAN_CELL_M (
   STAT_MO    INT,
   CMCC_BRANCH_CD    STRING,
   PLANCELL_BUILD_CELLCNT    INT,
   PLANCELL_BUILD_CELLCNT_RATE    DECIMAL(24,4)
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_NET_PLAN_CELL_M';

DROP TABLE IF EXISTS JCFW.TM_NET_NPLAN_ACTVCELL_M;
CREATE EXTERNAL TABLE JCFW.TM_NET_NPLAN_ACTVCELL_M (
   STAT_MO    INT,
   CMCC_BRANCH_CD    STRING,
   LCOVER_ACTV_NPLAN_CELLCNT    INT,
   LCOVER_ACTV_NPLAN_CELLCNT_RATE    DECIMAL(24,4)
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_NET_NPLAN_ACTVCELL_M';

DROP TABLE IF EXISTS JCFW.TM_NET_LCOVER_USR_ACTVCELL_M;
CREATE EXTERNAL TABLE JCFW.TM_NET_LCOVER_USR_ACTVCELL_M (
   STAT_MO    INT,
   CMCC_BRANCH_CD    STRING,
   USR_CNT    INT,
   WHOLE_TD_KEEP_RATE    DECIMAL(24,4),
   AVG_TD_KEEP_RATE    DECIMAL(24,4),
   TOP5_UNIQ_ACTV_CELLCNT    INT
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_NET_LCOVER_USR_ACTVCELL_M';

DROP TABLE IF EXISTS JCFW.TM_NET_HCOVER_MATCH_NETEXCPT_M;
CREATE EXTERNAL TABLE JCFW.TM_NET_HCOVER_MATCH_NETEXCPT_M (
   STAT_MO    INT,
   CMCC_BRANCH_CD    STRING,
   USR_CNT    INT,
   WHOLE_TD_KEEP_RATE    DECIMAL(24,4),
   AVG_TD_KEEP_RATE    DECIMAL(24,4),
   CELL_CNT    INT
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_NET_HCOVER_MATCH_NETEXCPT_M';

DROP TABLE IF EXISTS JCFW.TM_NET_HCOVER_MATCH_NETOK_M;
CREATE EXTERNAL TABLE JCFW.TM_NET_HCOVER_MATCH_NETOK_M (
   STAT_MO    INT,
   CMCC_BRANCH_CD    STRING,
   USR_CNT    INT,
   WHOLE_TD_KEEP_RATE    DECIMAL(24,4),
   AVG_TD_KEEP_RATE    DECIMAL(24,4)
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_NET_HCOVER_MATCH_NETOK_M';

DROP TABLE IF EXISTS JCFW.TM_NET_EXCPT_TDCELL_M;
CREATE EXTERNAL TABLE JCFW.TM_NET_EXCPT_TDCELL_M (
   STAT_MO    INT,
   CMCC_BRANCH_CD    STRING,
   PLANBUILD_EXCPT_TDCELLCNT    INT
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_NET_EXCPT_TDCELL_M';

DROP TABLE IF EXISTS JCFW.TM_NET_NORM_TDCELL_M;
CREATE EXTERNAL TABLE JCFW.TM_NET_NORM_TDCELL_M (
   STAT_MO    INT,
   CMCC_BRANCH_CD    STRING,
   PLANBUILD_NORM_TDCELLCNT    INT,
   HKPR_ACTV_TOP1_TDCELLCNT    INT
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_NET_NORM_TDCELL_M';

DROP TABLE IF EXISTS JCFW.TM_NET_NPLAN_CELL_M;
CREATE EXTERNAL TABLE JCFW.TM_NET_NPLAN_CELL_M (
   STAT_MO    INT,
   CMCC_BRANCH_CD    STRING,
   PLAN_MISSTD_2G_CELLCNT    INT,
   PLAN_SKEWTD_TD_CELLCNT    INT
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_NET_NPLAN_CELL_M';

DROP TABLE IF EXISTS JCFW.TM_NET_PLAN_ACTVCELL_M;
CREATE EXTERNAL TABLE JCFW.TM_NET_PLAN_ACTVCELL_M (
   STAT_MO    INT,
   CMCC_BRANCH_CD    STRING,
   LCOVER_ACTV_PLAN_CELLCNT    INT,
   LCOVER_ACTV_PLAN_CELLCNT_RATE    DECIMAL(24,4)
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_NET_PLAN_ACTVCELL_M';

DROP TABLE IF EXISTS JCFW.TR_IMEI_TAC_BAND;
CREATE EXTERNAL TABLE JCFW.TR_IMEI_TAC_BAND (
   TAC    STRING,
   DATA_DT    INT,
   TAC_CNT    INT,
   TRML_BRND_NAM    STRING,
   TRML_TYP    STRING,
   TRML_RELIA    DECIMAL(10,2)
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/REF/TR_IMEI_TAC_BAND';

ALTER TABLE JCFW.TR_IMEI_TAC_BAND ADD PARTITION (branch='GMCC');

DROP TABLE IF EXISTS JCFW.TO_P_GCUST_M;
CREATE EXTERNAL TABLE JCFW.TO_P_GCUST_M (
   STAT_MO    INT,
   CUST_ID    STRING,
   AREA_CD    STRING,
   CMCC_BRANCH_CD    STRING,
   GROUP_ID    STRING,
   PAR_GROUP_ID    STRING,
   CUST_NAM    STRING,
   CORP_REP    STRING,
   CORP_TYP    STRING,
   INDUS_TYP_CD    STRING,
   INDUS_TYP2_CD    STRING,
   CORP_TYP_CD    STRING,
   CORP_PAY_TYP_CD    STRING,
   SRV_DEPT    STRING,
   MAIN_PRDCT    STRING,
   EMP_CNT    INT,
   MGR_CNT    INT,
   NRML_EMP_CNT    INT,
   REG_NO    STRING,
   AREA_TYP_CD    SMALLINT,
   CORP_SIZE_TYP_CD    STRING,
   INNET_CHNL_CD    STRING,
   INNET_DT    INT,
   BUDGET_AMT    DECIMAL(18,2),
   MBR_LMT    INT,
   CORP_MOB_CNT    INT,
   CORP_CMCC_MOB_CNT    INT,
   CORP_CDMA_CNT    INT,
   CORP_UNICOM_GSM_CNT    INT,
   CORP_PAS_USR_CNT    INT,
   GOTONE_USR_CNT    INT,
   EASYOWN_USR_CNT    INT,
   EASYOWN_PUB_USR_CNT    INT,
   MZONE_USR_CNT    INT,
   REG_FUND    DECIMAL(18,2),
   MNG    STRING,
   SRV_RNK_CD    STRING,
   DIS_SAME_TYP    STRING,
   INVC_PRT_TYP    STRING,
   INVC_NAM    STRING,
   CMPT_STS_CD    STRING,
   CROS_BUSI_TYP    STRING,
   PRE_MGR_NAM    STRING,
   CUST_LVL    STRING,
   COMMEMORATE_DT    INT,
   PROJ_MGR    STRING,
   NO_MOB_USR_CNT    INT,
   CONTR_ID    STRING,
   SMALL_CORP_TYP    STRING,
   CORP_UNIT_CD    STRING,
   CREATE_TM    INT,
   YEAR_SALE_AMT    DECIMAL(18,2),
   YEAR_PROF_AMT    DECIMAL(18,2),
   LAST_YEAR_INC    DECIMAL(18,2),
   VIP_CNT    INT,
   RMRK    STRING,
   FIN_CD    STRING,
   RSPN_PERS_CO    STRING,
   VPMN_CD_CTY    STRING,
   FUND_TYP    STRING,
   FUND_CO    STRING,
   CUST_CHG_DT    INT,
   DEST_CUST_IND    STRING,
   UNIT_ADDR    STRING,
   RESP_MOB_NBR    STRING,
   RESP_WORK_TEL    STRING,
   DEPUTY_EMP_ID    STRING,
   CMCC_CNTRY_CD    STRING,
   CMCC_TOWN_CD    STRING,
   SNAP_CORP_TYP    STRING,
   DVLP_EMP_ID    STRING,
   DVLP_CHNL_TYP_CD    STRING,
   INDUS_TYP    STRING,
   CUSTM_INDUS_TYP    STRING,
   UNIT_KIND_CD    STRING,
   CO_SIZE_CD    STRING,
   DYN_CORP_TYP    STRING,
   HOST_PRVC    STRING,
   HOST_CTY    STRING,
   CROS_PRVC_GROUP_IND    STRING,
   GROUP_CUST_TYP    STRING,
   GROUP_CUST_IMP_TYP    STRING
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/ODS/TO_P_GCUST_M';

DROP TABLE IF EXISTS JCFW.TW_CDR_TD_CNTC_CIRC_M;
CREATE EXTERNAL TABLE JCFW.TW_CDR_TD_CNTC_CIRC_M (
   A_SWITCH_CD    STRING,
   USR_MOB_NBR    STRING,
   A_BRND_CD    SMALLINT,
   A_USR_TYP_CD    STRING,
   ROAM_TYP_CD    SMALLINT,
   VISITED_SWITCH_CD    STRING,
   CARRY_TYP_CD    STRING,
   TOLL_TYP_CD    SMALLINT,
   DIR_TYP_CD    STRING,
   SRV_TYP_CD    STRING,
   SUBSRV_TYP_CD    STRING,
   B_NBR    STRING,
   B_OPER_CD    STRING,
   B_BRND_CD    SMALLINT,
   B_USR_TYP_CD    STRING,
   B_AREA_CD    STRING,
   IMSI    STRING,
   OUT_ROUTE_CD    STRING,
   BILL_TYP_CD    STRING,
   VPMN_IND    STRING,
   FILE_TYP    STRING,
   CALL_DUR    INT,
   DEBET_DUR    INT,
   TOLL_DUR    INT,
   CALL_FLUX    INT,
   CALL_CNT    INT,
   DISC_MOB_FEE    DECIMAL(12,2),
   DISC_TOLL_FEE    DECIMAL(12,2),
   DISC_INF_FEE    DECIMAL(12,2)
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/EDS/TW_CDR_TD_CNTC_CIRC_M';

DROP TABLE IF EXISTS JCFW.TW_NB_WLAN_ACTV_USR_M;
CREATE EXTERNAL TABLE JCFW.TW_NB_WLAN_ACTV_USR_M (
   USR_NBR    STRING,
   BRND_CD    SMALLINT,
   CALL_CNT    INT,
   CALL_DUR    INT,
   CALL_FREE_DUR    INT,
   DEBET_FEE    DECIMAL(12,2),
   CALL_FREE_FLUX    BIGINT,
   CALL_FLUX    BIGINT
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/EDS/TW_NB_WLAN_ACTV_USR_M';

DROP TABLE IF EXISTS JCFW.TM_TDUSE_BUSI_MO;
CREATE EXTERNAL TABLE JCFW.TM_TDUSE_BUSI_MO (
   TM_INTRVL_CD    INT,
   CMCC_BRANCH_CD    STRING,
   BRND_CD    SMALLINT,
   TD_DEBET_DUR    BIGINT,
   TD_GPRS_FLUX    BIGINT
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_TDUSE_BUSI_MO';

DROP TABLE IF EXISTS JCFW.TM_IUSR_DATA_MO;
CREATE EXTERNAL TABLE JCFW.TM_IUSR_DATA_MO (
   TM_INTRVL_CD    INT,
   CMCC_BRANCH_CD    STRING,
   BRND_CD    SMALLINT,
   IUSR_DATA_TYP_CD    SMALLINT,
   USR_CNT    INT
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_IUSR_DATA_MO';

DROP TABLE IF EXISTS JCFW.TM_IDD_ROAM_DATABUSI_MO;
CREATE EXTERNAL TABLE JCFW.TM_IDD_ROAM_DATABUSI_MO (
   TM_INTRVL_CD    INT,
   BRND_CD    SMALLINT,
   CMCC_BRANCH_CD    STRING,
   USR_TYP_CD    SMALLINT,
   PKG_CD    SMALLINT,
   USR_CNT    INT,
   CALL_CNT    BIGINT,
   INCOME_FEE    DECIMAL(12,2),
   GPRS_FLUX    BIGINT
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_IDD_ROAM_DATABUSI_MO';

DROP TABLE IF EXISTS JCFW.TM_ROAMOUT_BUSI_MO;
CREATE EXTERNAL TABLE JCFW.TM_ROAMOUT_BUSI_MO (
   TM_INTRVL_CD    INT,
   CMCC_BRANCH_CD    STRING,
   ROAMOUT_TYP_CD    SMALLINT,
   VOC_CALL_CNT    INT,
   SMS_CALL_CNT    INT,
   GPRS_CALL_CNT    BIGINT
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_ROAMOUT_BUSI_MO';

DROP TABLE IF EXISTS JCFW.TM_OCS_PRE_SINGLE_SEPARATE_MO;
CREATE EXTERNAL TABLE JCFW.TM_OCS_PRE_SINGLE_SEPARATE_MO (
   TM_INTRVL_CD    INT,
   CMCC_BRANCH_CD    STRING,
   PKG_TYP_CD    STRING,
   SUCC_RDUC_USR_CNT    INT
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_OCS_PRE_SINGLE_SEPARATE_MO';

DROP TABLE IF EXISTS JCFW.TM_LOCAL_ROAM_INF_MO;
CREATE EXTERNAL TABLE JCFW.TM_LOCAL_ROAM_INF_MO (
   TM_INTRVL_CD    INT,
   ROAM_TYP_CD    SMALLINT,
   BRND_CD    SMALLINT,
   CMCC_BRANCH_CD    STRING,
   PKG_CD    SMALLINT,
   USR_CNT    INT,
   CALL_CNT    BIGINT,
   DEBET_MOB_DUR    BIGINT,
   DEBET_TOLL_DUR    BIGINT,
   BYCALL_DEBET_MOB_DUR    BIGINT,
   ACTV_DEBET_MOB_DUR    BIGINT,
   MOB_FEE    DECIMAL(12,2),
   TOLL_FEE    DECIMAL(12,2),
   INF_FEE    DECIMAL(12,2),
   ACTV_TOT_FEE    DECIMAL(12,2),
   BYCALL_TOT_FEE    DECIMAL(12,2),
   ACTV_USR_CNT    INT,
   BYCALL_USR_CNT    INT,
   ACTV_CALL_CNT    BIGINT,
   BYCALL_CALL_CNT    BIGINT,
   ACTV_DEBET_TOLL_DUR    BIGINT,
   BYCALL_DEBET_TOLL_DUR    BIGINT,
   ACTV_MOB_FEE    DECIMAL(12,2),
   BYCALL_MOB_FEE    DECIMAL(12,2),
   ACTV_TOLL_FEE    DECIMAL(12,2),
   BYCALL_TOLL_FEE    DECIMAL(12,2),
   TOT_FEE    DECIMAL(12,2)
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_LOCAL_ROAM_INF_MO';

DROP TABLE IF EXISTS JCFW.TM_IDD_TOLL_INF_MO;
CREATE EXTERNAL TABLE JCFW.TM_IDD_TOLL_INF_MO (
   TM_INTRVL_CD    INT,
   BRND_CD    SMALLINT,
   CALL_TYP_CD    SMALLINT,
   CMCC_BRANCH_CD    STRING,
   B_OPER_CD    STRING,
   B_AREA_CD    STRING,
   PKG_CD    SMALLINT,
   USR_CNT    INT,
   CALL_CNT    BIGINT,
   DEBET_MOB_DUR    BIGINT,
   DEBET_TOLL_DUR    BIGINT,
   BYCALL_DEBET_DUR    BIGINT,
   MOB_FEE    DECIMAL(12,2),
   TOLL_FEE    DECIMAL(12,2),
   INF_FEE    DECIMAL(12,2)
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_IDD_TOLL_INF_MO';

DROP TABLE IF EXISTS JCFW.TM_TOLL_INF_MO;
CREATE EXTERNAL TABLE JCFW.TM_TOLL_INF_MO (
   TM_INTRVL_CD    INT,
   TOLL_TYP_CD    SMALLINT,
   BRND_CD    SMALLINT,
   DIAL_TYP_CD    SMALLINT,
   CMCC_BRANCH_CD    STRING,
   PKG_CD    SMALLINT,
   USR_CNT    INT,
   CALL_CNT    BIGINT,
   DEBET_MOB_DUR    BIGINT,
   DEBET_TOLL_DUR    BIGINT,
   BYCALL_DEBET_DUR    BIGINT,
   MOB_FEE    DECIMAL(12,2),
   TOLL_FEE    DECIMAL(12,2),
   INF_FEE    DECIMAL(12,2)
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_TOLL_INF_MO';

DROP TABLE IF EXISTS JCFW.TM_NEW_USR_ARPU_MOU_NET_MO;
CREATE EXTERNAL TABLE JCFW.TM_NEW_USR_ARPU_MOU_NET_MO (
   TM_INTRVL_CD    INT,
   CMCC_BRANCH_CD    STRING,
   BRND_CD    SMALLINT,
   DIR_TYP_IND    STRING,
   NET_IND    STRING,
   USR_CNT    INT,
   DEBET_DUR    BIGINT,
   TOT_FEE    DECIMAL(12,2)
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_NEW_USR_ARPU_MOU_NET_MO';

DROP TABLE IF EXISTS JCFW.TM_VAL10_USR_MO;
CREATE EXTERNAL TABLE JCFW.TM_VAL10_USR_MO (
   TM_INTRVL_CD    INT,
   CMCC_BRANCH_CD    STRING,
   BRND_CD    SMALLINT,
   PKG_CD    SMALLINT,
   VAL10_USR_CNT    INT,
   NEW_VAL20_USR_CNT    INT,
   NETADD_VAL20_USR_CNT    INT,
   VAL20_USR_CNT    INT
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_VAL10_USR_MO';

DROP TABLE IF EXISTS JCFW.TM_INTL_ROAM_OUT_MO;
CREATE EXTERNAL TABLE JCFW.TM_INTL_ROAM_OUT_MO (
   TM_INTRVL_CD    INT,
   CMCC_BRANCH_CD    STRING,
   BRND_CD    SMALLINT,
   USR_CNT    INT,
   DEBET_DUR    BIGINT,
   VOC_FEE    DECIMAL(12,2),
   OTHER_BUSI_FEE    DECIMAL(12,2),
   HK_USR_CNT    INT,
   HK_DEBET_DUR    BIGINT,
   HK_VOC_FEE    DECIMAL(12,2),
   HK_OTHER_BUSI_FEE    DECIMAL(12,2)
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_INTL_ROAM_OUT_MO';

DROP TABLE IF EXISTS JCFW.TM_12593_USE_MO;
CREATE EXTERNAL TABLE JCFW.TM_12593_USE_MO (
   TM_INTRVL_CD    INT,
   CMCC_BRANCH_CD    STRING,
   BRND_CD    SMALLINT,
   HR_IND    STRING,
   USR_CNT    INT,
   LOCAL_DEBET_DUR    INT,
   LOCAL_DEBET_FEE    DECIMAL(12,2),
   PB_DEBET_DUR    INT,
   PB_DEBET_FEE    DECIMAL(12,2),
   GB_DEBET_DUR    INT,
   GB_DEBET_FEE    DECIMAL(12,2),
   HK_DEBET_DUR    INT,
   HK_DEBET_FEE    DECIMAL(12,2),
   OTHER_DEBET_DUR    INT,
   OTHER_DEBET_FEE    DECIMAL(12,2),
   TOT_DEBET_DUR    INT,
   TOT_DEBET_FEE    DECIMAL(12,2)
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES ('field.delim'='\001','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_12593_USE_MO';

DROP TABLE IF EXISTS JCFW.TM_NEWBUSI_USR_MO;
CREATE EXTERNAL TABLE JCFW.TM_NEWBUSI_USR_MO (
   TM_INTRVL_CD    INT,
   BRND_CD    SMALLINT,
   CMCC_BRANCH_CD    STRING,
   NEWBUSI_INUSE_USR_CNT    INT,
   SMS_INUSE_USR_CNT    INT,
   M_MMS_INUSE_USR_CNT    INT,
   GPRS_INUSE_USR_CNT    INT,
   WAP_INUSE_USR_CNT    INT,
   KJAVA_INUSE_USR_CNT    INT,
   COLORRING_INUSE_USR    INT,
   MMS_INUSE_USR_CNT    INT,
   M_SMS_INUSE_USR_CNT    INT,
   MOB_NETUSE_USR_CNT    INT
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_NEWBUSI_USR_MO';

DROP TABLE IF EXISTS JCFW.TM_TD_SMSMMS_AOA_BUSI_MO;
CREATE EXTERNAL TABLE JCFW.TM_TD_SMSMMS_AOA_BUSI_MO (
   TM_INTRVL_CD    INT,
   CMCC_BRANCH_CD    STRING,
   SMSMMS_IND    SMALLINT,
   AOA_IND    SMALLINT,
   SUCSEND_CNT    BIGINT,
   SUCINCEP_CNT    BIGINT
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_TD_SMSMMS_AOA_BUSI_MO';

DROP TABLE IF EXISTS JCFW.TM_GMCC_3G_BUSI_MO;
CREATE EXTERNAL TABLE JCFW.TM_GMCC_3G_BUSI_MO (
   TM_INTRVL_CD    INT,
   CMCC_BRANCH_CD    STRING,
   ROAM_TYP_CD    SMALLINT,
   TOLL_TYP_CD    SMALLINT,
   BRND_CD    SMALLINT,
   DIR_TYP_CD    STRING,
   B_BRND_CD    SMALLINT,
   B_SEG_3G_IND    STRING,
   CALL_CNT    BIGINT,
   CALL_DUR    BIGINT,
   DEBET_DUR    BIGINT,
   MOB_FEE    DECIMAL(12,2),
   TOLL_FEE    DECIMAL(12,2),
   INF_FEE    DECIMAL(12,2),
   TOLL_DUR    BIGINT
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_GMCC_3G_BUSI_MO';

DROP TABLE IF EXISTS JCFW.TM_AOA_CALLINFO_MO;
CREATE EXTERNAL TABLE JCFW.TM_AOA_CALLINFO_MO (
   TM_INTRVL_CD    INT,
   CMCC_BRANCH_CD    INT,
   BRND_CD    SMALLINT,
   PKG_CD    SMALLINT,
   CALL_USR_CNT    INT,
   CMCC_ACTVCALL_DUR    BIGINT,
   CMCC_BYCALL_DUR    BIGINT,
   FIX_ACTVCALL_DUR    BIGINT,
   FIX_BYCALL_DUR    BIGINT,
   UNI_ACTVCALL_DUR    BIGINT,
   UNI_BYCALL_DUR    BIGINT,
   CMCC_ACTVCALL_FEE    DECIMAL(12,2),
   CMCC_BYCALL_FEE    DECIMAL(12,2),
   FIX_ACTVCALL_FEE    DECIMAL(12,2),
   FIX_BYCALL_FEE    DECIMAL(12,2),
   UNI_ACTVCALL_FEE    DECIMAL(12,2),
   UNI_BYCALL_FEE    DECIMAL(12,2)
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_AOA_CALLINFO_MO';

DROP TABLE IF EXISTS JCFW.TM_INTL_TOLL_BUSI_MO;
CREATE EXTERNAL TABLE JCFW.TM_INTL_TOLL_BUSI_MO (
   TM_INTRVL_CD    INT,
   CMCC_BRANCH_CD    STRING,
   BRND_CD    SMALLINT,
   PKG_CD    SMALLINT,
   B_CNTRY_CD    STRING,
   DIR_TYP_CD    STRING,
   CNCT_NBR    STRING,
   B_COOPR_CD    STRING,
   DEBET_DUR    INT,
   CALL_CNT    INT,
   AMT_FEE    DECIMAL(12,2),
   USR_CNT    INT,
   TOLL_DUR    INT,
   MOB_FEE    DECIMAL(12,2),
   TOLL_FEE    DECIMAL(12,2)
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_INTL_TOLL_BUSI_MO';

DROP TABLE IF EXISTS JCFW.TM_SZX_HKCARD_MO;
CREATE EXTERNAL TABLE JCFW.TM_SZX_HKCARD_MO (
   TM_INTRVL_CD    INT,
   CMCC_BRANCH_CD    STRING,
   TOT_USR_CNT    INT,
   NEW_USR_CNT    INT,
   LOST_USR_CNT    INT,
   TOT_FEE    DECIMAL(12,2),
   LOC_ACTVCALL_FEE    DECIMAL(12,2),
   LOC_ACTVCALLHK_FEE    DECIMAL(12,2),
   LOC_BYCALL_FEE    DECIMAL(12,2),
   LOC_SMS_FEE    DECIMAL(12,2),
   LOC_GPRS_FEE    DECIMAL(12,2),
   ROHK_ACTVCALL_FEE    DECIMAL(12,2),
   ROHK_ACTVCALL_DDD_TOLL_FEE    DECIMAL(12,2),
   ROHK_BYCALL_FEE    DECIMAL(12,2),
   ROHK_SMS_FEE    DECIMAL(12,2),
   ROHK_GPRS_FEE    DECIMAL(12,2),
   ACTVCALL_DEBET_DUR    BIGINT,
   BYCALL_DEBET_DUR    BIGINT,
   ROHK_ACTVCALL_DEBET_DUR    BIGINT,
   LOC_ACTVCALL_DEBET_DUR    BIGINT,
   LDP_ACTVCALL_DEBET_DUR    BIGINT,
   DDD_ACTVCALL_DEBET_DUR    BIGINT,
   ACTVCALL_HK_DEBET_DUR    BIGINT,
   ACTVCALL_INNET_DEBET_DUR    BIGINT,
   ACTVCALL_UNI_DEBET_DUR    BIGINT,
   ACTVCALL_TEL_DEBET_DUR    BIGINT,
   ACTVCALL_OTH_DEBET_DUR    BIGINT,
   ROHK_BYCALL_DEBET_DUR    BIGINT,
   LOC_BYCALL_DEBET_DUR    BIGINT,
   LDP_BYCALL_DEBET_DUR    BIGINT,
   DDD_BYCALL_DEBET_DUR    BIGINT
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_SZX_HKCARD_MO';

DROP TABLE IF EXISTS JCFW.TM_NB_GPRS_ROLLOVER_FLUX_M;
CREATE EXTERNAL TABLE JCFW.TM_NB_GPRS_ROLLOVER_FLUX_M (
   STAT_MO    INT,
   CMCC_BRANCH_CD    STRING,
   BASS_PRDCT_CD    STRING,
   BASS_PRDCT_NAM    STRING,
   ROLLOVER_FLUX    BIGINT,
   NO_CLEARE_FLUX    BIGINT
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='&&','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/DM/TM_NB_GPRS_ROLLOVER_FLUX_M';

DROP TABLE IF EXISTS JCFW.TM_FREE_TERM_OTH_M;
CREATE EXTERNAL TABLE JCFW.TM_FREE_TERM_OTH_M (
   STAT_MO    INT,
   CMCC_BRANCH_CD    STRING,
   FREE_DIM_NAM1    STRING,
   FREE_DIM_NAM2    STRING,
   ITEM_CD    STRING,
   ITEM_VALUE    DECIMAL(26,6),
   APPLY_IND    STRING
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='&&','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_MM/REF/TM_FREE_TERM_OTH_M';


