----bd_gddd租户脚本----
DROP TABLE IF EXISTS JCFW.TR_NB_GPRS_FLUX_MARKET_INSTRUCT_PRDCT;
CREATE EXTERNAL TABLE JCFW.TR_NB_GPRS_FLUX_MARKET_INSTRUCT_PRDCT (
   CMCC_BRANCH_CD    STRING,
   INSTRUCT_PRDCT_CD    STRING,
   INSTRUCT_PRDCT_NAM    STRING,
   INSTRUCT_TYP    STRING,
   INSTRUCT_TYP_EXPL    STRING,
   EFF_DTS    STRING,
   INV_DTS    STRING
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/REF/TR_NB_GPRS_FLUX_MARKET_INSTRUCT_PRDCT';

DROP TABLE IF EXISTS JCFW.TR_BASS_USR_STS;
CREATE EXTERNAL TABLE JCFW.TR_BASS_USR_STS (
   USR_STS_CD    STRING,
   USR_STS_NAM    STRING,
   STS_PRIORITY    INT
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/REF/TR_BASS_USR_STS';

ALTER TABLE JCFW.TR_BASS_USR_STS ADD PARTITION (branch='GMCC');

DROP TABLE IF EXISTS JCFW.TR_BASS_OPRTORINFO;
CREATE EXTERNAL TABLE JCFW.TR_BASS_OPRTORINFO (
   OPR_ID    STRING,
   AREA_CD    STRING,
   OPR_NAM    STRING,
   BIRTHDAY    INT,
   WORK_DT    INT,
   GDR_TYP_CD    STRING,
   TRAIN_LVL    STRING,
   ED_TYP_CD    STRING,
   SKILL_LVL    STRING,
   TOT_LVL    STRING,
   COMITY_LVL    STRING,
   ID_NBR    STRING,
   OPR_TYP    STRING,
   NATIVEHOME    STRING,
   GRD_SCHL    STRING,
   GRD_DT    INT,
   MARRY_IND    STRING,
   POLITYFACE    STRING,
   HOME_ADDR    STRING,
   JOB_LIVE    STRING,
   NEW_PST_CD    STRING,
   BLOOD_TYP    STRING,
   HEALTHY    STRING,
   CHARACTER    STRING,
   INTREST    STRING,
   SOC_RELA    STRING,
   FAM_MBR    STRING,
   STAR_LVL    STRING,
   OPR_BUSI    STRING,
   HR_STS    STRING,
   TITLE    STRING,
   CMCC_BRANCH_CD    STRING,
   SPECIALTY    STRING,
   FAX    STRING,
   HOME_TEL    STRING,
   EMAIL    STRING,
   MOB_NBR    STRING,
   STS_CD    SMALLINT,
   CHNL_CD    STRING,
   OPR_STOP_DT    STRING
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/REF/TR_BASS_OPRTORINFO';

DROP TABLE IF EXISTS JCFW.TR_BILL_ACCT;
CREATE EXTERNAL TABLE JCFW.TR_BILL_ACCT (
   BILL_ACCT_CD    STRING,
   BILL_ACCT_NAM    STRING,
   BILL_ACCT_TYP_CD    SMALLINT,
   BILL_ACCT_STS_CD    SMALLINT,
   START_DT    STRING,
   STOP_DT    STRING,
   BILL_ACCT_LVL    SMALLINT,
   LMT_FLAG    STRING,
   WOFF_PRIOR    INT,
   ACCT_TYP    STRING,
   PRINT_NAM    STRING
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/REF/TR_BILL_ACCT';

DROP TABLE IF EXISTS JCFW.TR_SJDCRM_DICT_ITEM;
CREATE EXTERNAL TABLE JCFW.TR_SJDCRM_DICT_ITEM (
   DICT_CD    STRING,
   DICT_GROUP_CD    STRING,
   CMCC_BRANCH_CD    STRING,
   DICT_NAM    STRING,
   SORT_ORDER    INT,
   STATUS    SMALLINT,
   STS_DT    INT,
   STS_TIM    INT,
   DESCRP    STRING
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/REF/TR_SJDCRM_DICT_ITEM';

DROP TABLE IF EXISTS JCFW.TW_CORP_BUSI_DAY;
CREATE EXTERNAL TABLE JCFW.TW_CORP_BUSI_DAY (
   TM_INTRVL_CD    INT,
   CMCC_BRANCH_CD    STRING,
   USR_NBR    STRING,
   B_NBR    STRING,
   CORP_USR_NBR    STRING,
   SP_SUBBUSI_CD    STRING,
   CORP_BUSI_TYP_CD    SMALLINT,
   DIR_TYP_CD    STRING,
   BRND_CD    SMALLINT,
   MOB_FEE    DECIMAL(10,2),
   TOLL_FEE    DECIMAL(10,2),
   INF_FEE    DECIMAL(10,2),
   MON_FEE    DECIMAL(10,2),
   DEBET_MOB_DUR    INT,
   CALL_CNT    INT,
   CALL_FLUX    INT,
   GPRS_DDD_OTC_FLUX    INT,
   GPRS_IDD_FLUX    INT,
   GPRS_IDD_OTC_FLUX    INT,
   GUSR_ID    STRING
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/EDS/TW_CORP_BUSI_DAY';

DROP TABLE IF EXISTS JCFW.TW_APN_USR_DAY;
CREATE EXTERNAL TABLE JCFW.TW_APN_USR_DAY (
   TM_INTRVL_CD    INT,
   CMCC_BRANCH_CD    STRING,
   USR_NBR    STRING,
   APN_NBR    STRING,
   B_NBR    STRING,
   DIR_TYP_CD    STRING,
   BRND_CD    SMALLINT,
   USR_TYP_CD    STRING,
   CALL_CNT    BIGINT,
   CALL_FLUX    BIGINT,
   MOB_FEE    DECIMAL(12,2),
   TOLL_FEE    DECIMAL(12,2),
   INF_FEE    DECIMAL(12,2),
   GPRS_DDD_OTC_FLUX    INT,
   GPRS_IDD_FLUX    INT,
   GPRS_IDD_OTC_FLUX    INT,
   GPRS_LOC_FLUX    BIGINT,
   GPRS_IPR_FLUX    BIGINT,
   GPRS_OPR_FLUX    BIGINT,
   GPAY_FLUX    BIGINT
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/EDS/TW_APN_USR_DAY';

DROP TABLE IF EXISTS JCFW.TR_EBOX_ACCT_TYP;
CREATE EXTERNAL TABLE JCFW.TR_EBOX_ACCT_TYP (
   EBOX_UNIT_CD    STRING,
   EBOX_ACCT_TYP    SMALLINT
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/REF/TR_EBOX_ACCT_TYP';

DROP TABLE IF EXISTS JCFW.TR_WEB_CHL_BUSI;
CREATE EXTERNAL TABLE JCFW.TR_WEB_CHL_BUSI (
   BUSI_CD    STRING,
   BUSI_NAM    STRING
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/REF/TR_WEB_CHL_BUSI';

DROP TABLE IF EXISTS JCFW.TR_MMPLN_AP;
CREATE EXTERNAL TABLE JCFW.TR_MMPLN_AP (
   AP_CD    STRING,
   AP_NAME    STRING,
   AP_KIND1    STRING,
   AP_KIND2    STRING,
   AP_CODE    STRING,
   FEE    DECIMAL(10,2),
   VALID_TIME    STRING,
   INVALID_TIME    STRING,
   AP_TYPE    STRING,
   FEE_TYPE    STRING
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/REF/TR_MMPLN_AP';

DROP TABLE IF EXISTS JCFW.TR_MOBGAME_BUSI_INF;
CREATE EXTERNAL TABLE JCFW.TR_MOBGAME_BUSI_INF (
   BUSI_CD    STRING,
   TM_INTRVL_CD    INT,
   BUSI_NAME    STRING,
   SP_CD    STRING,
   SP_NAME    STRING,
   PRICE    DECIMAL(10,2),
   BUSI_TYP    SMALLINT,
   BUSI_TYP_CD    STRING,
   BUSI_TYP_NAME    STRING,
   BUSI_FLAG    STRING,
   PAY_TYP    STRING,
   FEE_TYP    STRING,
   GAME_TYP    STRING,
   GAME_TYP_NAME    STRING,
   START_DATE    STRING,
   END_DATE    STRING,
   BUSI_STS    STRING,
   PLAT_TYP    INT,
   IS_FLAG    STRING
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/REF/TR_MOBGAME_BUSI_INF';

DROP TABLE IF EXISTS JCFW.TR_SJDCRM_BASS_PRDCT;
CREATE EXTERNAL TABLE JCFW.TR_SJDCRM_BASS_PRDCT (
   BASS_PRDCT_CD    STRING,
   CMCC_BRANCH_CD    STRING,
   STAT_DT    INT,
   BASS_PRDCT_NAME    STRING,
   BASS_PRDCT_CATALOG_CD    STRING,
   BASS_PRDCT_TYP    SMALLINT,
   OVER_REGION_TYP    SMALLINT,
   EFF_DT    INT,
   EFF_TIM    STRING,
   INVALID_DT    INT,
   INVALID_TIM    STRING,
   STS_CD    STRING,
   BASS_PRDCT_DES    STRING,
   REGION_CD    STRING
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/REF/TR_SJDCRM_BASS_PRDCT';

DROP TABLE IF EXISTS JCFW.TR_SJDCRM_OPR_ROLE_INF;
CREATE EXTERNAL TABLE JCFW.TR_SJDCRM_OPR_ROLE_INF (
   OPR_ID    STRING,
   ROLE_ID    STRING,
   STATUS    STRING,
   STATUS_DT    INT,
   STATUS_TIM    STRING,
   CREATE_DT    INT,
   CREATE_TIM    STRING,
   DATA_SOURCE    STRING,
   DATA_DT    INT
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/REF/TR_SJDCRM_OPR_ROLE_INF';

DROP TABLE IF EXISTS JCFW.TR_BASS_GOODS_DATA;
CREATE EXTERNAL TABLE JCFW.TR_BASS_GOODS_DATA (
   GOODS_CD    STRING,
   CMCC_BRANCH_CD    STRING,
   GOODS_PRICE    DECIMAL(14,2),
   GOODS_CLASS_CD    INT,
   GOODS_TYP_CD    INT,
   GOODS_FROZEN_PERIOR    INT,
   GOODS_MEND_PERIOR    INT,
   GOODS_EXPIRE    INT,
   GOODS_NAM    STRING,
   GOODS_SOURCE    STRING,
   COLOR_DESC    STRING,
   ACCESSORY_DESC    STRING,
   PRESENT_DESC    STRING,
   NEED_ACTIVE    SMALLINT,
   LENGTH    SMALLINT,
   FEE_TIEM    STRING,
   CMCC_CODE    STRING,
   GOODS_STS_CD    INT
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/REF/TR_BASS_GOODS_DATA';

DROP TABLE IF EXISTS JCFW.TR_DICT_ITEM;
CREATE EXTERNAL TABLE JCFW.TR_DICT_ITEM (
   DICT_CD    STRING,
   DICT_GROUP_CD    STRING,
   CMCC_BRANCH_CD    STRING,
   DICT_NAM    STRING,
   SORT_ORDER    INT,
   STATUS    SMALLINT,
   STS_DT    INT,
   STS_TIM    INT,
   DESC    STRING
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/REF/TR_DICT_ITEM';

DROP TABLE IF EXISTS JCFW.TR_CTMS_TRML_PRDCT;
CREATE EXTERNAL TABLE JCFW.TR_CTMS_TRML_PRDCT (
   TRML_PRDCT_ID    STRING,
   TRML_PRDCT_NAM    STRING,
   TRML_BRND_CD    STRING,
   TRML_CD    STRING,
   TRML_PRDCT_TYP    STRING,
   AGENT    STRING,
   FD_FLAG_IND    STRING
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES ('field.delim'='\001','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/REF/TR_CTMS_TRML_PRDCT';

DROP TABLE IF EXISTS JCFW.TR_AUTO_OPRRSLT;
CREATE EXTERNAL TABLE JCFW.TR_AUTO_OPRRSLT (
   OPR_RSLT_CD    SMALLINT,
   REGION    STRING,
   OPR_IND    SMALLINT,
   OPR_RSLT_DESC    STRING,
   RTE_TAB    STRING,
   CLLEE_NBR    STRING
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/REF/TR_AUTO_OPRRSLT';

DROP TABLE IF EXISTS JCFW.TM_MRKT_MNTR_10086_ITEM_DATA_DAY;
CREATE EXTERNAL TABLE JCFW.TM_MRKT_MNTR_10086_ITEM_DATA_DAY (
   TM_INTRVL_CD    INT,
   REGION_CD    STRING,
   BRND_CD    SMALLINT,
   USR_GRADE    STRING,
   ARPU_GROUP_CD    STRING,
   WL_GROUP_CD    STRING,
   ITEM_CD    STRING,
   TODAY_VALUE    DECIMAL(20,6)
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/DM/TM_MRKT_MNTR_10086_ITEM_DATA_DAY';

DROP TABLE IF EXISTS JCFW.TM_PERS_FAM_PAY_USR_D;
CREATE EXTERNAL TABLE JCFW.TM_PERS_FAM_PAY_USR_D (
   STAT_DT    INT,
   CMCC_BRANCH_CD    STRING,
   TYP1_USR_CNT    INT,
   TYP2_USR_CNT    INT,
   TYP3_USR_CNT    INT,
   TYP4_USR_CNT    INT,
   TYP5_USR_CNT    INT,
   TYP6_USR_CNT    INT,
   TYP7_USR_CNT    INT,
   TYP8_USR_CNT    INT,
   SUM_USR_CNT    INT
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/DM/TM_PERS_FAM_PAY_USR_D';

DROP TABLE IF EXISTS JCFW.TM_ZNTS_SCESMS_ONTIM_DAY;
CREATE EXTERNAL TABLE JCFW.TM_ZNTS_SCESMS_ONTIM_DAY (
   TM_INTRVL_CD    INT,
   BRND_CD    SMALLINT,
   CMCC_BRANCH_CD    STRING,
   SR_TYP_ID    STRING,
   ORG_ID    STRING,
   CUST_LVL_CD    STRING,
   ORA_CLASS    SMALLINT,
   SUCC_DOWN_SMS_CNT    INT,
   VALID_SMSRTN_CNT    INT,
   FIRST_SMSRTN1_CNT    INT,
   FIRST_SMSRTN2_CNT    INT,
   FIRST_SMSRTN3_CNT    INT,
   FIRST_SMSRTN4_CNT    INT,
   FIRST_SMSRTN5_CNT    INT,
   FIRST_SMSRTNOTH_CNT    INT
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/DM/TM_ZNTS_SCESMS_ONTIM_DAY';

DROP TABLE IF EXISTS JCFW.TM_ZNTS_CMPLN_INTIM_DAY;
CREATE EXTERNAL TABLE JCFW.TM_ZNTS_CMPLN_INTIM_DAY (
   TM_INTRVL_CD    INT,
   BRND_CD    SMALLINT,
   CMCC_BRANCH_CD    STRING,
   SR_TYP_ID    STRING,
   ORG_ID    STRING,
   CUST_LVL_CD    STRING,
   ORA_CLASS    SMALLINT,
   INTIM_SETL_CNT    INT,
   SETL_CNT    INT,
   HNDL_DUR    BIGINT
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/DM/TM_ZNTS_CMPLN_INTIM_DAY';

DROP TABLE IF EXISTS JCFW.TM_NB_CPRINT_BUSI_D;
CREATE EXTERNAL TABLE JCFW.TM_NB_CPRINT_BUSI_D (
   STAT_DT    INT,
   CMCC_BRANCH_CD    STRING,
   BRND_CD    SMALLINT,
   USR_TYP    STRING,
   BUSI_TYP    SMALLINT,
   TOT_USR_CNT    INT,
   NEW_USR_CNT    INT,
   LOST_USR_CNT    INT,
   PAY_USR_CNT    INT,
   FUNC_FEE    DECIMAL(16,2)
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/DM/TM_NB_CPRINT_BUSI_D';

DROP TABLE IF EXISTS JCFW.TM_139_MAIL_USR_AGGR_DAY;
CREATE EXTERNAL TABLE JCFW.TM_139_MAIL_USR_AGGR_DAY (
   TM_INTRVL_CD    INT,
   BRND_CD    SMALLINT,
   CMCC_BRANCH_CD    STRING,
   REACH_USRCNT    INT,
   SILENT_USRCNT    INT,
   LOST_USRCNT    INT,
   TRM_REG_USRCNT    INT,
   INDP_REG_USRCNT    INT,
   PUSHMAIL_USRCNT    INT,
   PAUD_ACT_USRCNT    INT,
   WAP_0FLUX_ACT_USRCNT    INT,
   HI_SAMEIP_WEP_ACTUSR_CNT    INT,
   AUD_UNCN_USRCNT    INT
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/DM/TM_139_MAIL_USR_AGGR_DAY';

DROP TABLE IF EXISTS JCFW.TM_CALL_CMPT_BUSI_DAY;
CREATE EXTERNAL TABLE JCFW.TM_CALL_CMPT_BUSI_DAY (
   TM_INTRVL_CD    INT,
   CMCC_BRANCH_CD    STRING,
   BRND_CD    SMALLINT,
   CNCT_NBR_TYP_CD    SMALLINT,
   CURRDAY_CALL_CNT    INT,
   CURRDAY_USRCNT    INT,
   CURRDAY_DEBET_DUR    INT,
   CURRMON_CALL_CNT    INT,
   CURRMON_USRCNT_ALL    INT,
   CURRMON_USRCNT    INT,
   CURRMON_DEBET_DUR    INT
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/DM/TM_CALL_CMPT_BUSI_DAY';

DROP TABLE IF EXISTS JCFW.TM_SECUR_USR_DAY;
CREATE EXTERNAL TABLE JCFW.TM_SECUR_USR_DAY (
   TM_INTRVL_CD    INT,
   CMCC_BRANCH_CD    STRING,
   BRND_CD    SMALLINT,
   PKG_CD    SMALLINT,
   QUERY_REACH_USRCNT    INT,
   QUERY_NEW_USRCNT    INT,
   QUERY_CANCEL_USRCNT    INT,
   TRADE_REACH_USRCNT    INT,
   TRADE_NEW_USRCNT    INT,
   TRADE_CANCEL_USRCNT    INT,
   ALL_REACH_USRCNT    INT,
   ALL_NEW_USRCNT    INT,
   ALL_CANCEL_USRCNT    INT
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/DM/TM_SECUR_USR_DAY';

DROP TABLE IF EXISTS JCFW.TS_BIXF_CMNCT_USR;
CREATE EXTERNAL TABLE JCFW.TS_BIXF_CMNCT_USR (
   USR_NBR    STRING,
   BRND_CD    SMALLINT,
   PKG_CD    SMALLINT,
   MO_ACT_CALLUSR_IND    STRING,
   MO_CALLUSR_IND    STRING,
   TD_DEBET_DUR    INT,
   TD_GPRS_FLUX    INT,
   CMCC_BRANCH_CD    STRING,
   UPDT_DT    INT,
   NEW_CMNCT_IND    STRING,
   ACTV_USR_IND    STRING,
   FST_ACTV_DT    INT,
   LAST_ACTV_DT    INT,
   SMS_UP_CNT    INT,
   ACTVCALL_CNT    INT,
   BYCALL_CNT    INT,
   GSM_GPRS_FLUX    BIGINT,
   T_GPRS_FLUX    INT,
   CM_ACTV_DAYS    INT,
   CM_SMS_UP_CNT    INT,
   CM_ACTVCALL_CNT    INT,
   CM_BYCALL_CNT    INT,
   CM_GSM_GPRS_FLUX    BIGINT,
   CM_TD_GPRS_FLUX    INT
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/STAGE/TS_BIXF_CMNCT_USR';

DROP TABLE IF EXISTS JCFW.TW_BIXF_MM_BUSI_DAY;
CREATE EXTERNAL TABLE JCFW.TW_BIXF_MM_BUSI_DAY (
   TM_INTRVL_CD    INT,
   USR_NBR    STRING,
   BRND_CD    SMALLINT,
   WWW_REG_USR_IND    STRING,
   WWW_NEW_USR_IND    STRING,
   MT_REG_USR_IND    STRING,
   MT_NEW_USR_IND    STRING,
   MT_LOGIN_USR_IND    STRING,
   RELOGIN_USR_IND    STRING,
   ONE_LOGIN_USR_IND    STRING,
   CM_LOGIN_CNT    INT,
   CM_LOGINT_USR_IND    STRING,
   CM_RELOGINT_USR_IND    STRING,
   CM_ONELOGIN_USR_IND    STRING,
   WWW_LOGIN_CNT    INT,
   MT_LOGIN_CNT    INT,
   WWW_SOFT_DOWN_CNT    INT,
   WWW_GAME_DOWN_CNT    INT,
   WWW_ZT_DOWN_CNT    INT,
   MT_SOFT_DOWN_CNT    INT,
   MT_GAME_DOWN_CNT    INT,
   MT_ZT_DOWN_CNT    INT,
   TOT_APP_DOWN_CNT    INT,
   CMCC_BRANCH_CD    STRING
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/EDS/TW_BIXF_MM_BUSI_DAY';

DROP TABLE IF EXISTS JCFW.TW_BIXF_MOBBUSI_DAY;
CREATE EXTERNAL TABLE JCFW.TW_BIXF_MOBBUSI_DAY (
   TM_INTRVL_CD    INT,
   USR_NBR    STRING,
   BRND_CD    SMALLINT,
   PKG_CD    SMALLINT,
   SHOW_FUNC_FEE    DECIMAL(12,2),
   FWD_FEE    DECIMAL(12,2),
   SECRET_FUNC_FEE    DECIMAL(12,2),
   P2PSMS_UP_FEE    DECIMAL(12,2),
   P2PSMS_MON_FEE    DECIMAL(12,2),
   MWSMS_UP_FEE    DECIMAL(12,2),
   MWSMS_DOWN_FEE    DECIMAL(12,2),
   MWSMS_PER_INF_FEE    DECIMAL(12,2),
   MWSMS_MON_INF_FEE    DECIMAL(12,2),
   MWSMS_DIV_PER_INF_FEE    DECIMAL(12,2),
   MWSMS_DIV_MON_INF_FEE    DECIMAL(12,2),
   P2PMMS_UP_FEE    DECIMAL(12,2),
   P2PMMS_DOWN_FEE    DECIMAL(12,2),
   P2PMMS_MON_FEE    DECIMAL(12,2),
   MWMMS_UP_FEE    DECIMAL(12,2),
   MWMMS_PER_INF_FEE    DECIMAL(12,2),
   MWMMS_MON_INF_FEE    DECIMAL(12,2),
   MWMMS_DIV_PER_INF_FEE    DECIMAL(12,2),
   MWMMS_DIV_MON_INF_FEE    DECIMAL(12,2),
   CMNET_UP_FEE    DECIMAL(12,2),
   CMNET_DOWN_FEE    DECIMAL(12,2),
   CMWAP_UP_FEE    DECIMAL(12,2),
   CMWAP_DOWN_FEE    DECIMAL(12,2),
   GPRS_PKG_FEE    DECIMAL(12,2),
   MWWAP_PER_INF_FEE    DECIMAL(12,2),
   MWWAP_MON_INF_FEE    DECIMAL(12,2),
   MWWAP_DIV_PER_INF_FEE    DECIMAL(12,2),
   MWWAP_DIV_MON_INF_FEE    DECIMAL(12,2),
   IVR_CMNCT_FEE    DECIMAL(12,2),
   IVR_INF_FEE    DECIMAL(12,2),
   IVR_MON_FEE    DECIMAL(12,2),
   IVR_DIV_PER_INF_FEE    DECIMAL(12,2),
   IVR_DIV_MON_INF_FEE    DECIMAL(12,2),
   CR_CMNCT_FEE    DECIMAL(12,2),
   CR_PER_INF_FEE    DECIMAL(12,2),
   CR_MON_INF_FEE    DECIMAL(12,2),
   CR_DIV_PER_INF_FEE    DECIMAL(12,2),
   MOBMAIL_MON_FEE    DECIMAL(12,2),
   MOBMAIL_DIV_MON_FEE    DECIMAL(12,2),
   MOBNEWS_PER_INF_FEE    DECIMAL(12,2),
   MOBNEWS_MON_INF_FEE    DECIMAL(12,2),
   MOBNEWS_DIV_PER_INF_FEE    DECIMAL(12,2),
   MOBNEWS_DIV_MON_INF_FEE    DECIMAL(12,2),
   MOBGAME_PER_INF_FEE    DECIMAL(12,2),
   MOBGAME_MON_INF_FEE    DECIMAL(12,2),
   MOBGAME_DIV_PER_INF_FEE    DECIMAL(12,2),
   MOBGAME_DIV_MON_INF_FEE    DECIMAL(12,2),
   SECUR_QRY_IND    STRING,
   SECUR_QRY_NEW_IND    STRING,
   SECUR_QRY_CANC_IND    STRING,
   SECUR_TRD_IND    STRING,
   SECUR_TRD_NEW_IND    STRING,
   SECUR_TRD_CANC_IND    STRING,
   SECUR_IND    STRING,
   SECUR_NEW_IND    STRING,
   SECUR_CANC_IND    STRING,
   SECUR_CHRG_QRY_IND    STRING,
   SECUR_CHRG_TRD_IND    STRING,
   SECUR_CHRG_COMB_IND    STRING,
   SECUR_CHRG_CNSTR_ND    STRING,
   SECUR_CHRG_IND    STRING,
   CM_SECUR_CHRG_QRY_IND    STRING,
   CM_SECUR_CHRG_TRD_IND    STRING,
   CM_SECUR_CHRG_COMB_IND    STRING,
   CM_SECUR_CHRG_CNSTR_ND    STRING,
   CM_SECUR_CHRG_IND    STRING,
   CALLUSR_IND    STRING,
   GPRS_IND    STRING,
   MO_USE_IND    STRING,
   MO_MW_SUB_IND    STRING,
   MO_MW_CHRG_IND    STRING,
   CM_MO_USE_IND    STRING,
   CM_MO_MW_SUB_IND    STRING,
   CM_MO_MW_CHRG_IND    STRING,
   MO_GPRS_FLUX    INT,
   MO_CSD_DUR    INT,
   MO_MW_BILL_CNT    INT,
   MO_MW_MONBILL_CNT    INT,
   MO_PDP_ACTV_CNT    INT,
   MO_CMNCT_FEE    DECIMAL(12,2),
   MO_GPRS_CMNCT_FEE    DECIMAL(12,2),
   MO_CSD_CMNCT_FEE    DECIMAL(12,2),
   MO_INF_FEE    DECIMAL(12,2),
   CMCC_BRANCH_CD    STRING
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/EDS/TW_BIXF_MOBBUSI_DAY';

DROP TABLE IF EXISTS JCFW.TS_BIXF_JXCX_CUST_DAY;
CREATE EXTERNAL TABLE JCFW.TS_BIXF_JXCX_CUST_DAY (
   TM_INTRVL_CD    INT,
   CUST_ID    STRING,
   CMCC_BRANCH_CD    STRING,
   GDR_TYP_CD    STRING,
   LANG_TYP    STRING,
   PROF_TYP_CD    STRING,
   BIRTH_DT    INT,
   ID_CITY_CD    STRING,
   NBR_CNT    INT
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/STAGE/TS_BIXF_JXCX_CUST_DAY';

DROP TABLE IF EXISTS JCFW.TR_SJDCRM_BASS_GOODS_DATA;
CREATE EXTERNAL TABLE JCFW.TR_SJDCRM_BASS_GOODS_DATA (
   GOODS_CD    STRING,
   CMCC_BRANCH_CD    STRING,
   GOODS_PRICE    DECIMAL(14,2),
   GOODS_CLASS_CD    INT,
   GOODS_TYP_CD    INT,
   GOODS_FROZEN_PERIOR    INT,
   GOODS_MEND_PERIOR    INT,
   GOODS_EXPIRE    INT,
   GOODS_NAM    STRING,
   GOODS_SOURCE    STRING,
   COLOR_DESC    STRING,
   ACCESSORY_DESC    STRING,
   PRESENT_DESC    STRING,
   NEED_ACTIVE    SMALLINT,
   LENGTH    SMALLINT,
   FEE_TIEM    STRING,
   CMCC_CODE    STRING,
   GOODS_STS_CD    INT
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/REF/TR_SJDCRM_BASS_GOODS_DATA';

DROP TABLE IF EXISTS JCFW.TR_RHJF_HSC_MINCONSUME_DAY;
CREATE EXTERNAL TABLE JCFW.TR_RHJF_HSC_MINCONSUME_DAY (
   TARIFF_ID    STRING,
   CONSUME_ID    STRING,
   EFF_INTERVAL    INT,
   SPE_FEE    STRING,
   CONSUME_CYCLE    STRING,
   CYCLE_NUM    INT,
   EFFECTIVE_TYP    STRING,
   VALID_TYPE    SMALLINT,
   MIN_CON_FEE    DECIMAL(10,2),
   CMCC_BRANCH_CD    STRING
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/REF/TR_RHJF_HSC_MINCONSUME_DAY';

DROP TABLE IF EXISTS JCFW.TM_CMNCTUSR_DAY;
CREATE EXTERNAL TABLE JCFW.TM_CMNCTUSR_DAY (
   TM_INTRVL_CD    INT,
   CMCC_BRANCH_CD    STRING,
   BRND_CD    SMALLINT,
   TOWN_CD    STRING,
   BUSI_OFFICE_CD    STRING,
   LOCAL_CD    STRING,
   CELL_CD    STRING,
   PKG_CD    SMALLINT,
   PKG_DTL_CD    INT,
   ACTIVE_3MON_CNT    INT,
   NEW_INVALID_CNT    INT,
   INVALID_USR_CNT    INT,
   NEW_CALLUSR_CNT    INT,
   CURRMO_CALLUSR_CNT    INT
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/DM/TM_CMNCTUSR_DAY';

DROP TABLE IF EXISTS JCFW.TR_RHJF_HSC_PS_RATINGEBOX;
CREATE EXTERNAL TABLE JCFW.TR_RHJF_HSC_PS_RATINGEBOX (
   TARIFF_ID    STRING,
   BOSS_DISC_CD    STRING,
   EBOX_UNIT_CD    STRING,
   IUSR_MARK_PLAN_CD    STRING,
   DISC_EFF_TYP    SMALLINT,
   EFF_DT    INT,
   EFF_TIM    STRING,
   EFF_TIM_INTRVL    INT,
   PST_IND    SMALLINT,
   PAY_TIMES    INT,
   PAY_AMT    DECIMAL(16,2),
   ENTER_UNIT    SMALLINT,
   DISC_TYP    STRING,
   DISC_OVER_TYP    STRING,
   EFF_CYC    INT,
   EXP_CYC    INT,
   DESC_END_DT    INT,
   DISC_END_TIM    STRING,
   GIFT_IND    SMALLINT,
   GIFT_WAY    STRING,
   RELA_DISC_ID    INT,
   AFFIX_CD    STRING,
   FEE_SRC_TYP    STRING,
   FEE_SRC_ID    STRING,
   REMARK    STRING,
   PAY_TIM_INTRVL    INT,
   EFF_DAYS    INT
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/REF/TR_RHJF_HSC_PS_RATINGEBOX';

DROP TABLE IF EXISTS JCFW.TM_MRKT_AIR_PAY_CNTY_DAY;
CREATE EXTERNAL TABLE JCFW.TM_MRKT_AIR_PAY_CNTY_DAY (
   TM_INTRVL_CD    INT,
   CMCC_BRANCH_CD    STRING,
   AIR_PAY_AGENT    STRING,
   AIR_PAY_CNT    INT,
   AIR_PAY_FEE    DECIMAL(14,2)
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/DM/TM_MRKT_AIR_PAY_CNTY_DAY';

DROP TABLE IF EXISTS JCFW.TM_MRKT_AIR_PAY_RECORD_DAY;
CREATE EXTERNAL TABLE JCFW.TM_MRKT_AIR_PAY_RECORD_DAY (
   TM_INTRVL_CD    INT,
   CMCC_BRANCH_CD    STRING,
   FY_FEE    DECIMAL(14,2),
   HC_FEE    DECIMAL(14,2),
   HH_FEE    DECIMAL(14,2),
   LDXW_FEE    DECIMAL(14,2),
   LL_TEC_FEE    DECIMAL(14,2),
   RT_FEE    DECIMAL(14,2),
   YS_FEE    DECIMAL(14,2),
   TOTAL_FEE    DECIMAL(14,2)
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/DM/TM_MRKT_AIR_PAY_RECORD_DAY';

DROP TABLE IF EXISTS JCFW.TR_TERM_MIFI_CARD_TAC_D;
CREATE EXTERNAL TABLE JCFW.TR_TERM_MIFI_CARD_TAC_D (
   STAT_DT    INT,
   NTCARD_BRND_NAM    STRING,
   NTCARD_TRML_NAM    STRING,
   NTCARD_TYP_NAM    STRING,
   TAC    STRING
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/REF/TR_TERM_MIFI_CARD_TAC_D';

DROP TABLE IF EXISTS JCFW.TR_CELL;
CREATE EXTERNAL TABLE JCFW.TR_CELL (
   LOCAL_CD    STRING,
   CELL_CD    STRING,
   CMCC_BRANCH_CD    STRING,
   DISTICT_CD    STRING,
   DISTRICT_NAM    STRING,
   BUSI_OFFICE_CD    STRING,
   BUSI_OFFICE_NAM    STRING,
   TOWN_CD    STRING,
   TOWN_NAM    STRING,
   REGION_CD    STRING,
   REGION_NAM    STRING,
   FAINT_CELL_IND    STRING
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/REF/TR_CELL';

DROP TABLE IF EXISTS JCFW.TR_DAY;
CREATE EXTERNAL TABLE JCFW.TR_DAY (
   TM_INTRVL_CD    INT,
   DAY_CD    SMALLINT,
   WK_CD    SMALLINT,
   MO_CD    SMALLINT,
   QTR_CD    SMALLINT,
   YR_CD    SMALLINT,
   WK_DAY_CD    SMALLINT,
   HOLI_FLAG_IND    SMALLINT
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES ('field.delim'=',','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/REF/TR_DAY';

ALTER TABLE JCFW.TR_DAY ADD PARTITION (branch='GMCC');

DROP TABLE IF EXISTS JCFW.TM_MOB_STOCK;
CREATE EXTERNAL TABLE JCFW.TM_MOB_STOCK (
   CMCC_BRANCH_CD    STRING,
   DATA_DATE    INT,
   CHNL_IND    STRING,
   GOODS_UNIFI_IND    STRING,
   GOODS_PRD_CD    SMALLINT,
   GOODS_PRD_NAM    STRING,
   GOODS_NAM    STRING,
   CHNL_NAM    STRING,
   SELL_CNT    INT,
   CANCEL_SELL_CNT    INT,
   IN_STOCK_CNT    INT,
   OUT_STOCK_CNT    INT,
   CURR_STOCK_CNT    INT
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/DM/TM_MOB_STOCK';

DROP TABLE IF EXISTS JCFW.TM_AOASETL_FIX_MOB_DAY;
CREATE EXTERNAL TABLE JCFW.TM_AOASETL_FIX_MOB_DAY (
   CMCC_BRANCH_CD    STRING,
   SWITCH_NBR    STRING,
   OPER_IND    SMALLINT,
   INT_ROUTEFLAG    SMALLINT,
   SELT_SEQ    STRING,
   DIR_TYP_CD    SMALLINT,
   SETL_CYC_CD    INT,
   BRND_CD    SMALLINT,
   USR_TYP_CD    STRING,
   SELT_TYP_CD    STRING,
   ORIG_BRND    STRING,
   MO_DATA_DT    INT,
   VC_IP_FLAG    STRING,
   CALL_CNT    BIGINT,
   CALL_DUR    BIGINT,
   DEBET_60SEC_DUR    BIGINT,
   DEBET_6SEC_DUR    BIGINT,
   SETL_DUR    BIGINT,
   SETL_FEE    DECIMAL(14,3)
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/DM/TM_AOASETL_FIX_MOB_DAY';

DROP TABLE IF EXISTS JCFW.TM_NB_GPRS_GGSN_D;
CREATE EXTERNAL TABLE JCFW.TM_NB_GPRS_GGSN_D (
   STAT_DT    INT,
   CMCC_BRANCH_CD    STRING,
   NET2G_GPRS_FLUX    BIGINT,
   NET3G_GPRS_FLUX    BIGINT,
   NET4G_GPRS_FLUX    BIGINT,
   G_GPRS_FLUX    BIGINT,
   T_GPRS_FLUX    BIGINT,
   TDLTE_GPRS_FLUX    BIGINT,
   GPRS_FLUX    BIGINT
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/DM/TM_NB_GPRS_GGSN_D';

DROP TABLE IF EXISTS JCFW.TM_MRKT_CHNL_AUDIT_PAY_DAY;
CREATE EXTERNAL TABLE JCFW.TM_MRKT_CHNL_AUDIT_PAY_DAY (
   PAY_BILL_CD    STRING,
   CMCC_BRANCH_CD    STRING,
   PAY_CHNL_CD    STRING,
   CHNL_BUSI_ID    STRING,
   BUSI_DT    INT,
   PAY_DT    INT,
   CHARGE_WAY    STRING,
   CHARGE_SOURCE    STRING,
   TOTAL_PAY_FEE    DECIMAL(16,2),
   PAY_BILL_STS    STRING,
   BANK_NAM    STRING,
   BANK_ACCT_ID    STRING,
   REC_NAM    STRING,
   MEMO    STRING,
   BATCH_NO    STRING,
   CREATE_CD    STRING,
   AUDIT_CD    STRING,
   CHEQUE_NO    STRING,
   IS_DELAY_CD    SMALLINT,
   DATA_DT    INT
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/DM/TM_MRKT_CHNL_AUDIT_PAY_DAY';

DROP TABLE IF EXISTS JCFW.TM_MRKT_CHNL_AUDIT_REC_FACT_DAY;
CREATE EXTERNAL TABLE JCFW.TM_MRKT_CHNL_AUDIT_REC_FACT_DAY (
   CMCC_BRANCH_CD    STRING,
   CHNL_CD    STRING,
   BUSI_DT    INT,
   CHARGE_TYP    STRING,
   AMT    DECIMAL(14,2),
   REC_FEE    DECIMAL(16,2),
   AMTDIF_FEE    DECIMAL(14,2),
   AUDIT_RES    STRING,
   CHNL_AUDIT_NOTE    STRING,
   BRANCH_AUDIT_NOTE    STRING,
   CNTY_AUDIT_NOTE    STRING,
   REP_MEM    STRING,
   DATA_DT    INT
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/DM/TM_MRKT_CHNL_AUDIT_REC_FACT_DAY';

DROP TABLE IF EXISTS JCFW.TM_MRKT_CHNL_AUDIT_AG_DAY;
CREATE EXTERNAL TABLE JCFW.TM_MRKT_CHNL_AUDIT_AG_DAY (
   CHNL_CD    STRING,
   BUSI_DT    INT,
   CHARGE_TYP    STRING,
   CMCC_BRANCH_CD    STRING,
   AMT1    DECIMAL(14,2),
   AMT2    DECIMAL(14,2),
   AMT3    DECIMAL(14,2),
   SND_FEE    DECIMAL(14,2),
   AMTDIF_FEE    DECIMAL(14,2),
   AUDIT_RES    STRING,
   CHNL_AUDIT_NOTE    STRING,
   BRANCH_AUDIT_NOTE    STRING,
   CNTY_AUDIT_NOTE    STRING,
   REP_MEM    STRING,
   DATA_DT    INT
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/DM/TM_MRKT_CHNL_AUDIT_AG_DAY';

DROP TABLE IF EXISTS JCFW.TM_MRKT_CHNL_AUDIT_ET_DAY;
CREATE EXTERNAL TABLE JCFW.TM_MRKT_CHNL_AUDIT_ET_DAY (
   CHNL_CD    STRING,
   BUSI_DT    INT,
   CHARGE_TYP    STRING,
   CMCC_BRANCH_CD    STRING,
   AMT1    DECIMAL(14,2),
   AMT2    DECIMAL(14,2),
   AMT3    DECIMAL(14,2),
   SND_FEE    DECIMAL(14,2),
   AMTDIF_FEE    DECIMAL(14,2),
   AUDIT_RES    STRING,
   CHNL_AUDIT_NOTE    STRING,
   BRANCH_AUDIT_NOTE    STRING,
   CNTY_AUDIT_NOTE    STRING,
   REP_MEM    STRING,
   DATA_DT    INT
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/DM/TM_MRKT_CHNL_AUDIT_ET_DAY';

DROP TABLE IF EXISTS JCFW.TM_NB_CNTN_GPRS_ITEM_D;
CREATE EXTERNAL TABLE JCFW.TM_NB_CNTN_GPRS_ITEM_D (
   STAT_DT    INT,
   CMCC_BRANCH_CD    STRING,
   ITEM_CD    STRING,
   ITEM_VAL    BIGINT
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/DM/TM_NB_CNTN_GPRS_ITEM_D';

DROP TABLE IF EXISTS JCFW.TO_SCANCDR_PROC_REG;
CREATE EXTERNAL TABLE JCFW.TO_SCANCDR_PROC_REG (
   PROC_NAM    STRING,
   REQ_ID    STRING,
   DESCR    STRING
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES ('field.delim'='&','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/ODS/TO_SCANCDR_PROC_REG';

DROP TABLE IF EXISTS JCFW.TO_SHELL_LOG;
CREATE EXTERNAL TABLE JCFW.TO_SHELL_LOG (
   OPR_TM    STRING,
   USER_ID    STRING,
   OPR_TYP_CD    SMALLINT,
   APPLICATION_NAME    STRING,
   TEXT    STRING
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES ('field.delim'='&','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/ODS/TO_SHELL_LOG';

DROP TABLE IF EXISTS JCFW.TM_NEWBUSI_USR_DAY;
CREATE EXTERNAL TABLE JCFW.TM_NEWBUSI_USR_DAY (
   DEBET_DT    INT,
   BRND_CD    SMALLINT,
   CMCC_BRANCH_CD    STRING,
   NEWBUSI_INUSE_USR_CNT    INT,
   SMS_INUSE_USR_CNT    INT,
   M_MMS_INUSE_USR_CNT    INT,
   GPRS_INUSE_USR_CNT    INT,
   WAP_INUSE_USR_CNT    INT,
   KJAVA_INUSE_USR_CNT    INT,
   COLORRING_INUSE_USR    INT,
   MMS_INUSE_USR_CNT    INT,
   M_SMS_INUSE_USR_CNT    INT,
   MOB_NETUSE_USR_CNT    INT
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/DM/TM_NEWBUSI_USR_DAY';

DROP TABLE IF EXISTS JCFW.TW_BIXF_NET_CELL_CDR_BUSI_DAY;
CREATE EXTERNAL TABLE JCFW.TW_BIXF_NET_CELL_CDR_BUSI_DAY (
   TM_INTRVL_CD    INT,
   HR_CD    SMALLINT,
   CMCC_BRANCH_CD    STRING,
   LOCAL_CD    STRING,
   CELL_CD    STRING,
   CALL2_2G_AMT_FEE    DECIMAL(12,2),
   DEBET_2G_DUR    BIGINT,
   CALL_2G_CNT    INT,
   CALL2_3G_AMT_FEE    DECIMAL(12,2),
   DEBET_3G_DUR    BIGINT,
   CALL_3G_CNT    INT,
   CALL2_4G_AMT_FEE    DECIMAL(14,3),
   DEBET_4G_DUR    BIGINT,
   CALL_4G_CNT    INT
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/EDS/TW_BIXF_NET_CELL_CDR_BUSI_DAY';

DROP TABLE IF EXISTS JCFW.TM_CALLBUSI_STAT_DAY;
CREATE EXTERNAL TABLE JCFW.TM_CALLBUSI_STAT_DAY (
   TM_INTRVL_CD    INT,
   CMCC_BRANCH_CD    STRING,
   BRND_CD    SMALLINT,
   TOTAL_CALL_DUR    BIGINT,
   TOTAL_DEBET_DUR    BIGINT,
   NO_DEBET_DUR    BIGINT,
   SPECNBR_DEBET_DUR    BIGINT,
   CHRGNBR_DEBET_DUR    BIGINT,
   CALL_10086_DUR    BIGINT,
   CALL_12580_DUR    BIGINT,
   TOTAL_NOT0_DEBET_DUR    BIGINT,
   FIXFEE_DUR    BIGINT,
   TAOCAN_DEBET_DUR    BIGINT,
   VPMN_DEBET_DUR    BIGINT,
   DZK_IS0_DEBET_DUR    BIGINT,
   CHANGE_DEBET_DUR    BIGINT
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/DM/TM_CALLBUSI_STAT_DAY';

DROP TABLE IF EXISTS JCFW.TM_GMCC_3G_BUSI_MO_TMP_DAY;
CREATE EXTERNAL TABLE JCFW.TM_GMCC_3G_BUSI_MO_TMP_DAY (
   TM_INTRVL_CD    INT,
   CMCC_BRANCH_CD    STRING,
   ROAM_TYP_CD    SMALLINT,
   TOLL_TYP_CD    SMALLINT,
   BRND_CD    SMALLINT,
   DIR_TYP_CD    STRING,
   B_BRND_CD    SMALLINT,
   B_SEG_3G_IND    STRING,
   CALL_CNTBIG    BIGINT,
   CALL_DURBIG    BIGINT,
   DEBET_DURBIG    BIGINT,
   MOB_FEE    DECIMAL(12,2),
   TOLL_FEE    DECIMAL(12,2),
   INF_FEE    DECIMAL(12,2),
   TOLL_DURBIG    BIGINT
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES ('field.delim'='&','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/DM/TM_GMCC_3G_BUSI_MO_TMP_DAY';

DROP TABLE IF EXISTS JCFW.TM_HR_CMNCT_DAY;
CREATE EXTERNAL TABLE JCFW.TM_HR_CMNCT_DAY (
   TM_INTRVL_CD    INT,
   CMCC_BRANCH_CD    STRING,
   BRND_CD    SMALLINT,
   PKG_CD    SMALLINT,
   DIR_TYP_CD    STRING,
   DEBET_DT    INT,
   TOTAL_CALL_FEE    DECIMAL(12,2),
   TOTAL_DEBET_DUR    BIGINT,
   TOTAL_CMNCT_DUR    BIGINT,
   STATIC_BUSY_DEBET_DUR    INT,
   DEBET_DUR_0    INT,
   DEBET_DUR_1    INT,
   DEBET_DUR_2    INT,
   DEBET_DUR_3    INT,
   DEBET_DUR_4    INT,
   DEBET_DUR_5    INT,
   DEBET_DUR_6    INT,
   DEBET_DUR_7    INT,
   DEBET_DUR_8    INT,
   DEBET_DUR_9    INT,
   DEBET_DUR_10    INT,
   DEBET_DUR_11    INT,
   DEBET_DUR_12    INT,
   DEBET_DUR_13    INT,
   DEBET_DUR_14    INT,
   DEBET_DUR_15    INT,
   DEBET_DUR_16    INT,
   DEBET_DUR_17    INT,
   DEBET_DUR_18    INT,
   DEBET_DUR_19    INT,
   DEBET_DUR_20    INT,
   DEBET_DUR_21    INT,
   DEBET_DUR_22    INT,
   DEBET_DUR_23    INT,
   CMNCT_DUR_0    INT,
   CMNCT_DUR_1    INT,
   CMNCT_DUR_2    INT,
   CMNCT_DUR_3    INT,
   CMNCT_DUR_4    INT,
   CMNCT_DUR_5    INT,
   CMNCT_DUR_6    INT,
   CMNCT_DUR_7    INT,
   CMNCT_DUR_8    INT,
   CMNCT_DUR_9    INT,
   CMNCT_DUR_10    INT,
   CMNCT_DUR_11    INT,
   CMNCT_DUR_12    INT,
   CMNCT_DUR_13    INT,
   CMNCT_DUR_14    INT,
   CMNCT_DUR_15    INT,
   CMNCT_DUR_16    INT,
   CMNCT_DUR_17    INT,
   CMNCT_DUR_18    INT,
   CMNCT_DUR_19    INT,
   CMNCT_DUR_20    INT,
   CMNCT_DUR_21    INT,
   CMNCT_DUR_22    INT,
   CMNCT_DUR_23    INT,
   TOT_GPRS_FLUX    BIGINT,
   GPRS_0    BIGINT,
   GPRS_1    BIGINT,
   GPRS_2    BIGINT,
   GPRS_3    BIGINT,
   GPRS_4    BIGINT,
   GPRS_5    BIGINT,
   GPRS_6    BIGINT,
   GPRS_7    BIGINT,
   GPRS_8    BIGINT,
   GPRS_9    BIGINT,
   GPRS_10    BIGINT,
   GPRS_11    BIGINT,
   GPRS_12    BIGINT,
   GPRS_13    BIGINT,
   GPRS_14    BIGINT,
   GPRS_15    BIGINT,
   GPRS_16    BIGINT,
   GPRS_17    BIGINT,
   GPRS_18    BIGINT,
   GPRS_19    BIGINT,
   GPRS_20    BIGINT,
   GPRS_21    BIGINT,
   GPRS_22    BIGINT,
   GPRS_23    BIGINT
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES ('field.delim'='&','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/DM/TM_HR_CMNCT_DAY';

DROP TABLE IF EXISTS JCFW.TS_SJDCRM_CORP_MEMB_MARK_PLAN_IDAY;
CREATE EXTERNAL TABLE JCFW.TS_SJDCRM_CORP_MEMB_MARK_PLAN_IDAY (
   AREA_CD    STRING,
   GRPSUBSMEM_OID    STRING,
   PRIVSET_ID    STRING,
   START_DATE    STRING,
   APPLY_OID    STRING,
   END_DATE    STRING,
   CANCEL_OID    STRING,
   END_DATE_OLD    STRING,
   OID    STRING,
   CMCC_BRANCH_CD    STRING,
   DATA_DT    INT
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/STAGE/TS_SJDCRM_CORP_MEMB_MARK_PLAN_IDAY';

DROP TABLE IF EXISTS JCFW.TM_BOSS_BALTRAN_RPT_DAY;
CREATE EXTERNAL TABLE JCFW.TM_BOSS_BALTRAN_RPT_DAY (
   TM_INTRVL_CD    INT,
   CMCC_BRANCH_CD    STRING,
   BRND_CD    SMALLINT,
   OSS_CD    SMALLINT,
   IN_USR_CNT    INT,
   IN_AMT    DECIMAL(16,2),
   OUT_USR_CNT    INT,
   OUT_AMT    DECIMAL(16,2)
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='&&','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/DM/TM_BOSS_BALTRAN_RPT_DAY';

DROP TABLE IF EXISTS JCFW.TR_BASS_MARK_PLAN_RELA;
CREATE EXTERNAL TABLE JCFW.TR_BASS_MARK_PLAN_RELA (
   OBJ_TYP    STRING,
   MARK_PLAN_CD    STRING,
   AREA_CD    STRING,
   RLT_OBJ_TYP    STRING,
   RLT_MARK_PLAN_CD    STRING,
   RELA_TYP    STRING,
   BASS_PRDCT_CD    STRING,
   CMCC_BRANCH_CD    STRING,
   RLT_CYC_CNT    INT
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/REF/TR_BASS_MARK_PLAN_RELA';

DROP TABLE IF EXISTS JCFW.TO_P_VIRTL_CORP_USR_D;
CREATE EXTERNAL TABLE JCFW.TO_P_VIRTL_CORP_USR_D (
   GUSR_ID    STRING,
   GCUST_ID    STRING,
   GROUP_ID    STRING,
   GUSR_NAM    STRING,
   AREA_CD    STRING,
   BRND_CD    SMALLINT,
   BASS_PRDCT_CD    STRING,
   CORP_PRDCT_CODE    STRING,
   YJ_PRD_CODE    STRING,
   CORP_PRDCT_NBR    STRING,
   EFF_DT    INT,
   USR_STS_CD    STRING,
   STS_DT    INT,
   EBOX_ID    STRING,
   CMCC_BRANCH_CD    STRING,
   USR_TYP_CD    STRING
)
PARTITIONED BY (branch STRING)
STORED AS PARQUET
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/ODS/TO_P_VIRTL_CORP_USR_D'
TBLPROPERTIES ('serialization.null.format' ='NVL','serialization.encoding' ='GBK');

DROP TABLE IF EXISTS JCFW.TM_OTH_D;
CREATE EXTERNAL TABLE JCFW.TM_OTH_D (
   STAT_DT    INT,
   CMCC_BRANCH_CD    STRING,
   BRND_CD    SMALLINT,
   ITEM_CD    STRING,
   ITEM_VALUE    DECIMAL(26,6)
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES ('field.delim'='&','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/GDXQ/GD_DD/DM/TM_OTH_D';


