----bd_gif租户脚本----
DROP TABLE IF EXISTS JCFW.TYJ_USR_FUNC_MO;
CREATE EXTERNAL TABLE JCFW.TYJ_USR_FUNC_MO (
   TM_INTRVL_CD    BIGINT,
   USR_ID    STRING,
   BASSFUNC_CD    STRING,
   BRND_CD    SMALLINT,
   BEGIN_DT    BIGINT,
   END_DT    BIGINT,
   UPD_DT    BIGINT
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_USR_FUNC_MO';

DROP TABLE IF EXISTS JCFW.TYJ_CDR_FILL;
CREATE EXTERNAL TABLE JCFW.TYJ_CDR_FILL (
   A_SWITCH_CD    STRING,
   CMCC_BRANCH_CD    STRING,
   ROLLBACK_ID    STRING,
   ROLLBACK_CNT    SMALLINT,
   USR_MOB_NBR    STRING,
   A_OPER_CD    STRING,
   A_BRND_CD    SMALLINT,
   A_USR_TYP_CD    STRING,
   USR_PKG_TYP    STRING,
   ROAM_TYP_CD    SMALLINT,
   VISITED_SWITCH_CD    STRING,
   CALL_AREA_CD    STRING,
   CALL_DT    BIGINT,
   CALL_TIM    STRING,
   HR_CD    SMALLINT,
   DEBET_DT    BIGINT,
   TM_INTRVL_CD    BIGINT,
   CARRY_TYP_CD    STRING,
   CNCT_NBR    STRING,
   TOLL_TYP_CD    SMALLINT,
   DIR_TYP_CD    STRING,
   SRV_TYP_CD    STRING,
   SUBSRV_TYP_CD    STRING,
   RATE_TYP_CD    STRING,
   B_NBR    STRING,
   B_SWITCH_CD    STRING,
   B_OPER_CD    STRING,
   B_BRND_CD    SMALLINT,
   B_USR_TYP_CD    STRING,
   B_AREA_CD    STRING,
   CALL_DUR    BIGINT,
   TOLL_DUR    BIGINT,
   CALL_FLUX    BIGINT,
   CALL_CNT    SMALLINT,
   MOB_FEE    DECIMAL(7,2),
   TOLL_FEE    DECIMAL(7,2),
   INF_FEE    DECIMAL(7,2),
   IMSI    STRING,
   LOCAL_CD    STRING,
   CELL_CD    STRING,
   OUT_ROUTE_CD    STRING,
   IN_ROUTE_CD    STRING,
   ROUTE_TYP    STRING,
   SWITCH_NBR    STRING,
   ROAM_NBR    STRING,
   IMEI    STRING,
   BILL_TYP_CD    STRING,
   DISC_CD    STRING,
   VPMN_IND    STRING,
   DISC_MOB_FEE    DECIMAL(7,2),
   DISC_TOLL_FEE    DECIMAL(7,2),
   DISC_INF_FEE    DECIMAL(7,2),
   DISC_FEE    DECIMAL(7,2),
   CALL_FREE_DUR    SMALLINT,
   ACCT_BAL    DECIMAL(10,2),
   ICP_STAT_CD    STRING,
   LOAD_ID    BIGINT,
   FILE_TYP    STRING,
   CX_FILE_IND    STRING,
   NET_TYP_CD    STRING
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_CDR_FILL';

DROP TABLE IF EXISTS JCFW.TYJ_CORRECT_USRCALL_MO;
CREATE EXTERNAL TABLE JCFW.TYJ_CORRECT_USRCALL_MO (
   TM_INTRVL_CD    BIGINT,
   CNCT_NBR    STRING,
   HR_SEG_CD    SMALLINT,
   USR_ID    STRING,
   A_USR_NBR    STRING,
   AGGREGATE_SEQ    SMALLINT,
   AGGREGATE_DT    BIGINT,
   DIR_TYP_CD    STRING,
   ROAM_TYP_CD    SMALLINT,
   TOLL_TYP_CD    SMALLINT,
   SRV_TYP_CD    STRING,
   SUBSRV_TYP_CD    STRING,
   RATE_TYP_CD    STRING,
   BILL_TYP_CD    STRING,
   CARRY_TYP_CD    STRING,
   ICP_STAT_CD    STRING,
   B_AREA_CD    STRING,
   B_BRND_CD    SMALLINT,
   B_OPER_CD    STRING,
   CALL_AREA_CD    STRING,
   CX_FILE_IND    STRING,
   BRND_CD    SMALLINT,
   CMCC_BRANCH_CD    STRING,
   CALL_CNT    BIGINT,
   CALL_DUR    BIGINT,
   CALL_FLUX    BIGINT,
   CALL_FREE_DUR    BIGINT,
   DEBET_MOB_DUR    BIGINT,
   DEBET_TOLL_DUR    BIGINT,
   MOB_FEE    DECIMAL(10,2),
   TOLL_FEE    DECIMAL(10,2),
   INF_FEE    DECIMAL(10,2),
   MOB_DEBET1_FEE    DECIMAL(10,2),
   TOLL_DEBET1_FEE    DECIMAL(10,2),
   INF_DEBET1_FEE    DECIMAL(10,2),
   VPMN_IND    STRING,
   FEE_DISCOUNT_TYP_CD    SMALLINT,
   NET_TYP_CD    STRING,
   B_USR_TYP_CD    STRING
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_CORRECT_USRCALL_MO';

DROP TABLE IF EXISTS JCFW.TYJ_MON_USR;
CREATE EXTERNAL TABLE JCFW.TYJ_MON_USR (
   USR_ID    STRING,
   USR_MOB_NBR    STRING,
   BRND_CD    SMALLINT,
   USR_INNET_DT    INT,
   USR_STS_CD    INT,
   USR_CHG_DT    BIGINT,
   SIM_CARD_FLAG    BIGINT,
   CMCC_BRANCH_CD    STRING,
   CELL_TYP_CD    SMALLINT,
   MRKT_CHNL_CD    STRING,
   IMSI    STRING,
   INNET_IND    SMALLINT,
   CUST_ID    STRING
)
PARTITIONED BY (branch STRING,month INT)
STORED AS PARQUET
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_MON_USR'
TBLPROPERTIES ('serialization.null.format' ='NVL','serialization.encoding' ='GBK');

DROP TABLE IF EXISTS JCFW.TYJ_USR;
CREATE EXTERNAL TABLE JCFW.TYJ_USR (
   USR_ID    STRING,
   USR_MOB_NBR    STRING,
   BRND_CD    SMALLINT,
   USR_INNET_DT    INT,
   USR_STS_CD    INT,
   USR_CHG_DT    INT,
   SIM_CARD_FLAG    BIGINT,
   CMCC_BRANCH_CD    STRING,
   CELL_TYP_CD    SMALLINT,
   IMSI    STRING,
   INNET_IND    SMALLINT,
   CUST_ID    STRING
)
PARTITIONED BY (branch STRING)
STORED AS PARQUET
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_USR'
TBLPROPERTIES ('serialization.null.format' ='NVL','serialization.encoding' ='GBK');

DROP TABLE IF EXISTS JCFW.TYJ_TMP_G21009;
CREATE EXTERNAL TABLE JCFW.TYJ_TMP_G21009 (
   DATA_DATE    BIGINT,
   USR_NBR    STRING,
   TOLL_TYPE    SMALLINT,
   ROAM_TYPE    SMALLINT,
   CALL_TYPE    SMALLINT,
   CUST_BRND    SMALLINT,
   HR_CD    SMALLINT,
   CALL_CNT    BIGINT,
   CALL_DUR    BIGINT,
   DEBET_MOB_DUR    BIGINT,
   DEBET_TOLL_DUR    BIGINT,
   MOB_FEE    DECIMAL(16,2),
   TOLL_FEE    DECIMAL(16,2),
   TOTAL_FEE    DECIMAL(16,2),
   CALL_AREA_CD    STRING,
   B_AREA_CD    STRING,
   B_BRND_CD    SMALLINT,
   B_USR_TYP_CD    STRING,
   CARRY_TYP_CD    STRING,
   CNCT_NBR    STRING,
   CMCC_BRANCH_CD    STRING,
   SRV_TYP_CD    STRING,
   RATE_TYP_CD    STRING,
   BILL_TYP_CD    STRING,
   NET_TYP_CD    STRING
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_TMP_G21009';

DROP TABLE IF EXISTS JCFW.TYJ_TMP_G21003;
CREATE EXTERNAL TABLE JCFW.TYJ_TMP_G21003 (
   DATA_DATE    INT,
   USR_NBR    STRING,
   CUST_BRND    STRING,
   VOIC_BUSI_TYPE    STRING,
   TOLL_TYPE    STRING,
   IP_BUSI_TYPE    STRING,
   OPER_CD    STRING,
   ROAM_TYPE    STRING,
   CALL_TYPE    STRING,
   CALL_CNT    BIGINT,
   MOB_DUR    BIGINT,
   TOLL_DUR    BIGINT,
   CALL_DUR    BIGINT,
   DEBET_MOB_FEE    DECIMAL(16,2),
   DEBET_TOLL_FEE    DECIMAL(16,2),
   DEBET_FORWARD_FEE    DECIMAL(16,2),
   DEBET_TOTAL_FEE    DECIMAL(16,2),
   MOB_FEE    DECIMAL(16,2),
   TOLL_FEE    DECIMAL(16,2),
   FORWARD_FEE    DECIMAL(16,2),
   TOTAL_FEE    DECIMAL(16,2),
   FREE_DUR    BIGINT,
   FAVOR_DUR    BIGINT,
   NET_TYP_CD    STRING
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_TMP_G21003';

DROP TABLE IF EXISTS JCFW.TYJ_CONVERT_DEF;
CREATE EXTERNAL TABLE JCFW.TYJ_CONVERT_DEF (
   CON_RELATIVE    BIGINT,
   SOU_TYPE    SMALLINT,
   OBJ_TYPE    SMALLINT,
   OBJ_VALUE    STRING,
   SOU_VALUE    STRING,
   CON_ID    INT,
   SOU_EXPLAIN    STRING
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES ('field.delim'=',','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_CONVERT_DEF';

ALTER TABLE JCFW.TYJ_CONVERT_DEF ADD PARTITION (branch='GMCC');

DROP TABLE IF EXISTS JCFW.TYJ_MON_GCUST;
CREATE EXTERNAL TABLE JCFW.TYJ_MON_GCUST (
   TM_INTRVL_CD    BIGINT,
   GROUP_ID    STRING,
   PARENT_GROUP_ID    STRING,
   CMCC_BRANCH_CD    STRING,
   CUST_NAM    STRING,
   INDUS_TYP_CD    SMALLINT,
   CORP_TYP_CD    SMALLINT,
   CORP_SCOP_TYP_CD    SMALLINT,
   CORP_SIZE_TYP_CD    SMALLINT,
   CORP_PAY_TYP_CD    STRING,
   CORP_ADDR    STRING,
   CORP_URL    STRING,
   CORP_EMP_CNT    INT,
   SOC_PROP_CD    SMALLINT,
   MARK_PLAN_CD    STRING,
   CUST_LEVEL_CD    STRING,
   CNTCT_NAM    STRING,
   CNTCT_TEL_NBR    STRING,
   CNTCT_PCD    STRING,
   MRKT_CHNL_CD    STRING,
   CUST_INNET_DT    BIGINT,
   CUST_OUTNET_DT    BIGINT,
   CUST_INNET_IND    SMALLINT,
   CUST_CHG_DT    BIGINT,
   CORP_SRVC_RNK_CD    STRING,
   STATE_KIND_CD    BIGINT,
   SERV_TYP_CD    SMALLINT,
   SERV_LVL_CD    SMALLINT,
   IS_BCUST_CD    STRING,
   GRPORG_LVL_CD    STRING,
   SNGRP_AB_CD    STRING,
   OUTNET_RSN    SMALLINT,
   ID_TYP_CD    SMALLINT,
   ID_NBR    STRING,
   MAIN_BUS    STRING,
   TRADE_RANK    STRING,
   TRADE_TYP1_CD    SMALLINT,
   TRADE_TYP2_CD    STRING,
   CMPT_STS_CD    STRING,
   IS_ORG    STRING,
   ORG_CUST_CD    STRING,
   ORG_CODE    STRING,
   DTGRP_AB_CD_2016    STRING
)
PARTITIONED BY (branch STRING,month INT)
STORED AS PARQUET
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_MON_GCUST'
TBLPROPERTIES ('serialization.null.format' ='NVL','serialization.encoding' ='GBK');

DROP TABLE IF EXISTS JCFW.TYJ_CHNL_DAY;
CREATE EXTERNAL TABLE JCFW.TYJ_CHNL_DAY (
   CHNL_CD    STRING,
   YJ_CHNL_TYP_CD    SMALLINT,
   YJ_CHNL_SUBTYP_CD    SMALLINT,
   CMCC_BRANCH_CD    STRING,
   CMCC_CNTY_NAM    STRING,
   CMCC_TOWN_NAM    STRING,
   CHNL_NAM    STRING,
   CHNL_ADR    STRING,
   PRT_SOURCE    STRING,
   ADR_TYP_CD    STRING,
   BUZ_TYP_CD    STRING,
   STAR_LVL_CD    SMALLINT,
   CHNL_STS_CD    STRING,
   BUSI_START_TIM    STRING,
   BUSI_END_TIM    STRING,
   OFFIC_LATITUDE    DECIMAL(10,5),
   OFFIC_LONGTITUDE    DECIMAL(10,5),
   BUZ_AREA    BIGINT,
   EMP_NUM    BIGINT,
   CONNECT_TYP_CD    STRING,
   ATM_CHNL_CD    STRING,
   EXC_FLAG    STRING,
   SALE_AREA_FLAG    STRING,
   CONTR_EFF_DT    STRING,
   CONTR_INVALID_DT    STRING,
   CONTR_OVER_YEARS    DECIMAL(4,0),
   DEC_INV_FEE    BIGINT,
   EQIUP_INV_FEE    BIGINT,
   OFFIC_INV_FEE    BIGINT,
   DOOR_SUBSIDY_FEE    BIGINT,
   CHNL_CNTCT_NAM    STRING,
   CNTCT_TEL_NBR    STRING,
   VIP_FLAG    STRING,
   REWARD_TYP    STRING,
   CHNL_CHG_DT    BIGINT,
   AGENT_ID    STRING,
   UNIQUE_CHNL_CD    STRING,
   UNIQUE_CHNL_CD_CHG_DT    BIGINT
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES ('field.delim'='\001','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_CHNL_DAY';

DROP TABLE IF EXISTS JCFW.TYJ_MZONE_USR_LEAK;
CREATE EXTERNAL TABLE JCFW.TYJ_MZONE_USR_LEAK (
   USR_ID    STRING,
   CUST_ID    STRING,
   MOB_USE_TYP_CD    SMALLINT,
   USR_INNET_DT    BIGINT,
   USR_PROP_CD    STRING,
   USR_NBR    STRING,
   IMSI    STRING,
   CMCC_BRANCH_CD    STRING,
   MRKT_CHNL_CD    STRING,
   MPUB_TYP_CD    SMALLINT,
   PAY_TYP_CD    SMALLINT,
   INNET_TYP_CD    STRING,
   BRND_CD    SMALLINT,
   PRDCT_CD    SMALLINT,
   CELL_TYP_CD    SMALLINT,
   USR_STS_CD    STRING,
   USR_CHG_DT    BIGINT
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_MZONE_USR_LEAK';

DROP TABLE IF EXISTS JCFW.TYJ_USR_LEAK;
CREATE EXTERNAL TABLE JCFW.TYJ_USR_LEAK (
   TM_INTRVL_CD    BIGINT,
   USR_ID    STRING,
   LEAK_TYP_CD    SMALLINT,
   CUST_ID    STRING,
   USR_NBR    STRING,
   BRND_CD    SMALLINT,
   USR_INNET_DT    BIGINT,
   CMCC_BRANCH_CD    STRING,
   USR_STS_CD    STRING,
   CELL_TYP_CD    SMALLINT,
   CORRECT_FLAG    SMALLINT,
   INNET_IND    SMALLINT,
   IMSI    STRING
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_USR_LEAK';

DROP TABLE IF EXISTS JCFW.TYJ_LEAK_USR_CORRECT;
CREATE EXTERNAL TABLE JCFW.TYJ_LEAK_USR_CORRECT (
   DATA_DATE    BIGINT,
   USR_ID    STRING,
   LEAK_TYP_CD    SMALLINT,
   CUST_ID    STRING,
   MOB_USE_TYP_CD    SMALLINT,
   USR_INNET_DT    BIGINT,
   USR_PROP_CD    STRING,
   USR_NBR    STRING,
   IMSI    STRING,
   CMCC_BRANCH_CD    STRING,
   MRKT_CHNL_CD    STRING,
   MPUB_TYP_CD    SMALLINT,
   PAY_TYP_CD    SMALLINT,
   INNET_TYP_CD    STRING,
   BRND_CD    SMALLINT,
   PRDCT_CD    SMALLINT,
   CELL_TYP_CD    SMALLINT,
   USR_STS_CD    STRING,
   INNET_IND    SMALLINT
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_LEAK_USR_CORRECT';

DROP TABLE IF EXISTS JCFW.TYJ_TMP_G02004;
CREATE EXTERNAL TABLE JCFW.TYJ_TMP_G02004 (
   USR_ID    STRING,
   CUST_ID    STRING,
   CMCC_BRANCH_CD    STRING,
   USR_NBR    STRING,
   BRND_CD    SMALLINT,
   MOB_USE_TYP_CD    SMALLINT,
   USR_STS_CD    STRING,
   PAY_TYP_CD    SMALLINT,
   MRKT_CHNL_CD    STRING,
   USR_INNET_DT    BIGINT,
   USR_OUTNET_DT    BIGINT,
   USR_CHG_DT    BIGINT,
   CELL_TYP_CD    SMALLINT,
   PRDCT_CD    SMALLINT,
   INNET_IND    SMALLINT,
   IMSI    STRING
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_TMP_G02004';

DROP TABLE IF EXISTS JCFW.TYJ_USR_INC_DAY;
CREATE EXTERNAL TABLE JCFW.TYJ_USR_INC_DAY (
   USR_ID    STRING,
   CUST_ID    STRING,
   MOB_USE_TYP_CD    SMALLINT,
   USR_INNET_DT    BIGINT,
   USR_PROP_CD    STRING,
   USR_NBR    STRING,
   IMSI    STRING,
   CMCC_BRANCH_CD    STRING,
   MRKT_CHNL_CD    STRING,
   MPUB_TYP_CD    SMALLINT,
   PAY_TYP_CD    SMALLINT,
   INNET_TYP_CD    STRING,
   BRND_CD    SMALLINT,
   PRDCT_CD    SMALLINT,
   CELL_TYP_CD    SMALLINT,
   USR_STS_CD    STRING,
   USR_CHG_DT    BIGINT,
   INNET_IND    SMALLINT
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_USR_INC_DAY';

DROP TABLE IF EXISTS JCFW.TYJ_GCUST;
CREATE EXTERNAL TABLE JCFW.TYJ_GCUST (
   GROUP_ID    STRING,
   PARENT_GROUP_ID    STRING,
   CMCC_BRANCH_CD    STRING,
   CUST_NAM    STRING,
   INDUS_TYP_CD    SMALLINT,
   CORP_TYP_CD    SMALLINT,
   CORP_SCOP_TYP_CD    SMALLINT,
   CORP_SIZE_TYP_CD    SMALLINT,
   CORP_PAY_TYP_CD    STRING,
   CORP_ADDR    STRING,
   CORP_URL    STRING,
   CORP_EMP_CNT    INT,
   SOC_PROP_CD    SMALLINT,
   MARK_PLAN_CD    STRING,
   CUST_LEVEL_CD    STRING,
   CNTCT_NAM    STRING,
   CNTCT_TEL_NBR    STRING,
   CNTCT_PCD    STRING,
   MRKT_CHNL_CD    STRING,
   CUST_INNET_DT    BIGINT,
   CUST_OUTNET_DT    BIGINT,
   CUST_INNET_IND    SMALLINT,
   CUST_CHG_DT    BIGINT,
   CORP_SRVC_RNK_CD    STRING,
   STATE_KIND_CD    BIGINT,
   SERV_TYP_CD    SMALLINT,
   SERV_LVL_CD    SMALLINT,
   IS_BCUST_CD    STRING,
   GRPORG_LVL_CD    STRING,
   SNGRP_AB_CD    STRING,
   OUTNET_RSN    SMALLINT,
   ID_TYP_CD    SMALLINT,
   ID_NBR    STRING,
   MAIN_BUS    STRING,
   TRADE_RANK    STRING,
   TRADE_TYP1_CD    SMALLINT,
   TRADE_TYP2_CD    STRING,
   CMPT_STS_CD    STRING,
   UNIT_KIND_CD    SMALLINT,
   KEYUSR_NAM    STRING,
   KEYUSR_NBR    STRING,
   IS_ORG    STRING,
   ORG_CUST_CD    STRING,
   ORG_CODE    STRING,
   DTGRP_AB_CD_2016    STRING
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_GCUST';

DROP TABLE IF EXISTS JCFW.TYJ_USR_EXP;
CREATE EXTERNAL TABLE JCFW.TYJ_USR_EXP (
   TM_INTRVL_CD    INT,
   USR_ID    STRING,
   CUST_ID    STRING,
   MOB_USE_TYP_CD    SMALLINT,
   USR_INNET_DT    BIGINT,
   USR_PROP_CD    STRING,
   USR_NBR    STRING,
   IMSI    STRING,
   CMCC_BRANCH_CD    STRING,
   CHNL_CD    STRING,
   MPUB_TYP_CD    SMALLINT,
   PAY_TYP_CD    SMALLINT,
   INNET_TYP_CD    STRING,
   BRND_CD    SMALLINT,
   SIM_CARD_FLAG    SMALLINT,
   CELL_TYP_CD    SMALLINT,
   USR_STS_CD    STRING,
   USR_CHG_DT    BIGINT,
   INNET_IND    SMALLINT
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_USR_EXP';

DROP TABLE IF EXISTS JCFW.TYJ_CORP_MBR;
CREATE EXTERNAL TABLE JCFW.TYJ_CORP_MBR (
   GROUP_ID    STRING,
   USR_NBR    STRING,
   USR_NAM    STRING,
   IMP_LVL_CD    STRING,
   ROLE_TYP    STRING,
   CREAT_DT    BIGINT,
   STS_DT    BIGINT,
   KEYUSR_NAM    STRING,
   KEYUSR_NBR    STRING
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_CORP_MBR';

ALTER TABLE JCFW.TYJ_CORP_MBR ADD PARTITION (branch='GMCC');

DROP TABLE IF EXISTS JCFW.TYJ_AGENT_CHNL_INFO;
CREATE EXTERNAL TABLE JCFW.TYJ_AGENT_CHNL_INFO (
   CHNL_CD    STRING,
   AGENT_ID    STRING,
   TM_INTRVL_CD    BIGINT
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES ('field.delim'='\001','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_AGENT_CHNL_INFO';

DROP TABLE IF EXISTS JCFW.TYJ_TERM_PROPERTY_91003;
CREATE EXTERNAL TABLE JCFW.TYJ_TERM_PROPERTY_91003 (
   SERIAL_NO    BIGINT,
   TERM_TYP_CD    STRING,
   TERM_BRND    STRING,
   TERM_BRND_CD    STRING,
   TERM_DEVICE_NAM    STRING,
   TERM_NICKNAME    STRING,
   TERM_DEVICE_ID    STRING,
   E2G_TYP    STRING,
   E3G_TYP    STRING,
   E4G_TYP    STRING,
   OS_TYP    STRING,
   OS_TYP_VER    STRING,
   WLAN_FUNC_IND    STRING,
   WAP_SUPPORT    STRING,
   WWW_SUPPORT    STRING,
   GPRS_FUNC_IND    STRING,
   GPS_FUNC_DESC    STRING,
   MMS_FUNC_IND    STRING,
   FRONT_PIXEL    BIGINT,
   BACK_PIXEL    BIGINT,
   SCREEN_PIXEL    STRING,
   SCR_REF    STRING,
   COLOR_DEPTH    BIGINT,
   HANDWRITE_IND    STRING,
   TOUCH_SCREEN_TYP    STRING,
   TERM_STYLE    STRING,
   JAVA_VER    STRING,
   USB_IND    STRING,
   BLUETEETH_IND    STRING,
   INFRARED_IND    STRING,
   BASE_TCTW    STRING,
   SUPPORT_VOLTE_IND    STRING,
   PERMT_DT    INTEGER
)
PARTITIONED BY (branch STRING,month INT)
STORED AS PARQUET
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_TERM_PROPERTY_91003'
TBLPROPERTIES ('serialization.null.format' ='NVL','serialization.encoding' ='GBK');

DROP TABLE IF EXISTS JCFW.TYJ_EBOX_MO;
CREATE EXTERNAL TABLE JCFW.TYJ_EBOX_MO (
   TM_INTRVL_CD    INT,
   EBOX_ID    STRING,
   EBOX_NAME    STRING,
   EBOX_STS_CD    STRING,
   EBOX_CREATE_DT    INT,
   CUST_ID    STRING
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_EBOX_MO';

DROP TABLE IF EXISTS JCFW.TYJ_SAM_VOICE_M;
CREATE EXTERNAL TABLE JCFW.TYJ_SAM_VOICE_M (
   TM_INTRVL_CD    INT,
   USR_ID    STRING,
   USR_MOB_NBR    STRING,
   BRND_CD    SMALLINT,
   DIR_TYP_CD    STRING,
   ROAM_TYP_CD    STRING,
   TOLL_TYP_CD    STRING,
   IP_BUSI_TYPE    STRING,
   START_CALL_DTS    STRING,
   SRV_TYP_CD    STRING,
   SUBSRV_TYP_CD    STRING,
   CALL_CNT    INT,
   CALL_DUR    INT,
   CALL_FREE_DUR    INT,
   DEBET_DUR    INT,
   TOLL_DUR    INT,
   IMEI    STRING,
   IMSI    STRING,
   NET_TYP_CD    STRING,
   VIDEO_IND    STRING,
   CMCC_BRANCH_CD    STRING,
   CALL_AREA_CD    STRING,
   LOCAL_CD    STRING,
   CELL_CD    STRING,
   B_BRANCH_CD    STRING,
   B_AREA_CD    STRING,
   B_NBR    STRING,
   B_BRND_CD    STRING,
   C_NBR    STRING,
   VPMN_IND    STRING,
   DISC_MOB_FEE    INT,
   DISC_TOLL_FEE    INT,
   DISC_INF_FEE    INT,
   MOB_FEE    INT,
   TOLL_FEE    INT,
   FREE_TALK_IND    STRING,
   ROLL_BACK_IND    STRING,
   SUPER_LONG_IND    STRING,
   CMCC_BRANCH_CD_PRE    STRING
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_SAM_VOICE_M';

DROP TABLE IF EXISTS JCFW.TYJ_SAM_NBR;
CREATE EXTERNAL TABLE JCFW.TYJ_SAM_NBR (
   SAM_DATE    INT,
   USR_NBR    STRING,
   USR_ID    STRING,
   VPMN_CORP    STRING,
   VPMN_CORP_INN    STRING
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_SAM_NBR';

DROP TABLE IF EXISTS JCFW.TYJ_CDR_LACK;
CREATE EXTERNAL TABLE JCFW.TYJ_CDR_LACK (
   A_SWITCH_CD    STRING,
   CMCC_BRANCH_CD    STRING,
   ROLLBACK_ID    STRING,
   ROLLBACK_CNT    SMALLINT,
   USR_MOB_NBR    STRING,
   A_OPER_CD    STRING,
   A_BRND_CD    SMALLINT,
   A_USR_TYP_CD    STRING,
   USR_PKG_TYP    STRING,
   ROAM_TYP_CD    SMALLINT,
   VISITED_SWITCH_CD    STRING,
   CALL_AREA_CD    STRING,
   CALL_DT    BIGINT,
   CALL_TIM    STRING,
   HR_CD    SMALLINT,
   DEBET_DT    BIGINT,
   TM_INTRVL_CD    BIGINT,
   CARRY_TYP_CD    STRING,
   CNCT_NBR    STRING,
   TOLL_TYP_CD    SMALLINT,
   DIR_TYP_CD    STRING,
   SRV_TYP_CD    STRING,
   SUBSRV_TYP_CD    STRING,
   RATE_TYP_CD    STRING,
   B_NBR    STRING,
   B_SWITCH_CD    STRING,
   B_OPER_CD    STRING,
   B_BRND_CD    SMALLINT,
   B_USR_TYP_CD    STRING,
   B_AREA_CD    STRING,
   CALL_DUR    BIGINT,
   TOLL_DUR    BIGINT,
   CALL_FLUX    BIGINT,
   CALL_CNT    SMALLINT,
   MOB_FEE    DECIMAL(7,2),
   TOLL_FEE    DECIMAL(7,2),
   INF_FEE    DECIMAL(7,2),
   IMSI    STRING,
   LOCAL_CD    STRING,
   CELL_CD    STRING,
   OUT_ROUTE_CD    STRING,
   IN_ROUTE_CD    STRING,
   ROUTE_TYP    STRING,
   SWITCH_NBR    STRING,
   ROAM_NBR    STRING,
   IMEI    STRING,
   BILL_TYP_CD    STRING,
   DISC_CD    STRING,
   VPMN_IND    STRING,
   DISC_MOB_FEE    DECIMAL(7,2),
   DISC_TOLL_FEE    DECIMAL(7,2),
   DISC_INF_FEE    DECIMAL(7,2),
   DISC_FEE    DECIMAL(7,2),
   CALL_FREE_DUR    SMALLINT,
   ACCT_BAL    DECIMAL(10,2),
   ICP_STAT_CD    STRING,
   LOAD_ID    BIGINT,
   FILE_TYP    STRING,
   CX_FILE_IND    STRING,
   NET_TYP_CD    STRING
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_CDR_LACK';

DROP TABLE IF EXISTS JCFW.TYJ_USR_CELL;
CREATE EXTERNAL TABLE JCFW.TYJ_USR_CELL (
   USR_MOB_NBR    STRING,
   CELL_TYP_CD    SMALLINT,
   UPD_DT    BIGINT
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_USR_CELL';

DROP TABLE IF EXISTS JCFW.TYJ_SMS_CORRECT_TACTIC;
CREATE EXTERNAL TABLE JCFW.TYJ_SMS_CORRECT_TACTIC (
   DATA_DATE    BIGINT,
   DEBET_DT    BIGINT,
   CALL_DT    BIGINT,
   FILE_SEQ    BIGINT,
   CMCC_BRANCH_CD    STRING,
   DATA_SOURCE    BIGINT,
   CORRECT_FLAG    BIGINT,
   CALL_CNT    BIGINT
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_SMS_CORRECT_TACTIC';

DROP TABLE IF EXISTS JCFW.TYJ_USR_FUNC;
CREATE EXTERNAL TABLE JCFW.TYJ_USR_FUNC (
   USR_ID    STRING,
   BASSFUNC_CD    STRING,
   BRND_CD    SMALLINT,
   BEGIN_DT    BIGINT,
   END_DT    BIGINT,
   UPD_DT    BIGINT
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_USR_FUNC';

DROP TABLE IF EXISTS JCFW.TS_TD_CDR_D;
CREATE EXTERNAL TABLE JCFW.TS_TD_CDR_D (
   A_SWITCH_CD    STRING,
   CMCC_BRANCH_CD    STRING,
   ROLLBACK_ID    STRING,
   ROLLBACK_CNT    SMALLINT,
   USR_MOB_NBR    STRING,
   A_OPER_CD    STRING,
   A_BRND_CD    SMALLINT,
   A_USR_TYP_CD    STRING,
   USR_PKG_TYP    STRING,
   ROAM_TYP_CD    SMALLINT,
   VISITED_SWITCH_CD    STRING,
   CALL_AREA_CD    STRING,
   CALL_DT    BIGINT,
   CALL_TIM    STRING,
   HR_CD    SMALLINT,
   DEBET_DT    BIGINT,
   TM_INTRVL_CD    BIGINT,
   CARRY_TYP_CD    STRING,
   CNCT_NBR    STRING,
   TOLL_TYP_CD    SMALLINT,
   DIR_TYP_CD    STRING,
   SRV_TYP_CD    STRING,
   SUBSRV_TYP_CD    STRING,
   RATE_TYP_CD    STRING,
   B_NBR    STRING,
   B_SWITCH_CD    STRING,
   B_OPER_CD    STRING,
   B_BRND_CD    SMALLINT,
   B_USR_TYP_CD    STRING,
   B_AREA_CD    STRING,
   CALL_DUR    BIGINT,
   TOLL_DUR    BIGINT,
   CALL_FLUX    BIGINT,
   CALL_CNT    BIGINT,
   MOB_FEE    DECIMAL(7,2),
   TOLL_FEE    DECIMAL(7,2),
   INF_FEE    DECIMAL(7,2),
   IMSI    STRING,
   LOCAL_CD    STRING,
   CELL_CD    STRING,
   OUT_ROUTE_CD    STRING,
   IN_ROUTE_CD    STRING,
   ROUTE_TYP    STRING,
   SWITCH_NBR    STRING,
   ROAM_NBR    STRING,
   IMEI    STRING,
   BILL_TYP_CD    STRING,
   DISC_CD    STRING,
   VPMN_IND    STRING,
   DISC_MOB_FEE    DECIMAL(7,2),
   DISC_TOLL_FEE    DECIMAL(7,2),
   DISC_INF_FEE    DECIMAL(7,2),
   DISC_FEE    DECIMAL(7,2),
   CALL_FREE_DUR    INT,
   ACCT_BAL    DECIMAL(10,2),
   ICP_STAT_CD    STRING,
   LOAD_ID    BIGINT,
   FILE_TYP    STRING,
   CX_FILE_IND    STRING,
   NET_TYP_CD    STRING,
   FLAG_IND    STRING
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/STAGE/TS_TD_CDR_D';

DROP TABLE IF EXISTS JCFW.TYJ_CDR_POOL;
CREATE EXTERNAL TABLE JCFW.TYJ_CDR_POOL (
   A_SWITCH_CD    STRING,
   CMCC_BRANCH_CD    STRING,
   ROLLBACK_ID    STRING,
   ROLLBACK_CNT    SMALLINT,
   USR_MOB_NBR    STRING,
   A_OPER_CD    STRING,
   A_BRND_CD    SMALLINT,
   A_USR_TYP_CD    STRING,
   USR_PKG_TYP    STRING,
   ROAM_TYP_CD    SMALLINT,
   VISITED_SWITCH_CD    STRING,
   CALL_AREA_CD    STRING,
   CALL_DT    INT,
   CALL_TIM    STRING,
   HR_CD    SMALLINT,
   DEBET_DT    INT,
   TM_INTRVL_CD    INT,
   CARRY_TYP_CD    STRING,
   CNCT_NBR    STRING,
   TOLL_TYP_CD    SMALLINT,
   DIR_TYP_CD    STRING,
   SRV_TYP_CD    STRING,
   SUBSRV_TYP_CD    STRING,
   RATE_TYP_CD    STRING,
   B_NBR    STRING,
   B_SWITCH_CD    STRING,
   B_OPER_CD    STRING,
   B_BRND_CD    SMALLINT,
   B_USR_TYP_CD    STRING,
   B_AREA_CD    STRING,
   CALL_DUR    INT,
   TOLL_DUR    INT,
   CALL_FLUX    INT,
   CALL_CNT    SMALLINT,
   MOB_FEE    DECIMAL(7,2),
   TOLL_FEE    DECIMAL(7,2),
   INF_FEE    DECIMAL(7,2),
   IMSI    STRING,
   LOCAL_CD    STRING,
   CELL_CD    STRING,
   OUT_ROUTE_CD    STRING,
   IN_ROUTE_CD    STRING,
   ROUTE_TYP    STRING,
   SWITCH_NBR    STRING,
   ROAM_NBR    STRING,
   IMEI    STRING,
   BILL_TYP_CD    STRING,
   DISC_CD    STRING,
   VPMN_IND    STRING,
   DISC_MOB_FEE    DECIMAL(7,2),
   DISC_TOLL_FEE    DECIMAL(7,2),
   DISC_INF_FEE    DECIMAL(7,2),
   DISC_FEE    DECIMAL(7,2),
   CALL_FREE_DUR    SMALLINT,
   ACCT_BAL    DECIMAL(10,2),
   ICP_STAT_CD    STRING,
   LOAD_ID    INT,
   FILE_TYP    STRING,
   CX_FILE_IND    STRING
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_CDR_POOL';

DROP TABLE IF EXISTS JCFW.TYJ_TMP_SMSBUSI;
CREATE EXTERNAL TABLE JCFW.TYJ_TMP_SMSBUSI (
   DATA_DATE    INT,
   CALL_DT    BIGINT,
   DEBET_DT    BIGINT,
   CMCC_BRANCH_CD    STRING,
   IMEI    STRING,
   CUST_BRND    STRING,
   SMS_BUSI_TYPE    STRING,
   SMS_CALL_TYPE    STRING,
   SMS_STAT_CD    STRING,
   OPER_CD    STRING,
   CALL_CNT    BIGINT,
   MOB_FEE    DECIMAL(16,2),
   INF_FEE    DECIMAL(16,2),
   MONTH_FEE    DECIMAL(16,2)
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_TMP_SMSBUSI';

DROP TABLE IF EXISTS JCFW.TYJ_TMP_G21007;
CREATE EXTERNAL TABLE JCFW.TYJ_TMP_G21007 (
   DATA_DATE    INT,
   CUST_BRND    STRING,
   SMS_BUSI_TYPE    STRING,
   SMS_CALL_TYPE    STRING,
   SMS_STAT_CD    STRING,
   OPER_CD    STRING,
   CALL_CNT    BIGINT,
   MOB_FEE    DECIMAL(16,2),
   INF_FEE    DECIMAL(16,2),
   MONTH_FEE    DECIMAL(16,2)
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_TMP_G21007';

DROP TABLE IF EXISTS JCFW.TYJ_VOC_CORRECT_TACTIC;
CREATE EXTERNAL TABLE JCFW.TYJ_VOC_CORRECT_TACTIC (
   DATA_DATE    BIGINT,
   BRND_CD    SMALLINT,
   HR_CD    STRING,
   CMCC_BRANCH_CD    STRING,
   BUSY_TYP    BIGINT,
   CALL_DT    BIGINT,
   CELL_TYP_CD    SMALLINT,
   CORRECT_FLAG    SMALLINT,
   CALL_CNT    BIGINT,
   MOB_DUR    BIGINT,
   TOLL_DUR    BIGINT,
   CALL_DUR    BIGINT,
   MOB_FEE    DECIMAL(16,2),
   TOLL_FEE    DECIMAL(16,2),
   TOTAL_FEE    DECIMAL(16,2)
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_VOC_CORRECT_TACTIC';

DROP TABLE IF EXISTS JCFW.TYJ_USR_FUNC_DAY;
CREATE EXTERNAL TABLE JCFW.TYJ_USR_FUNC_DAY (
   USR_ID    STRING,
   BASSFUNC_CD    STRING,
   UPD_DT    BIGINT,
   USR_NBR    STRING,
   BRND_CD    SMALLINT,
   BEGIN_DT    BIGINT,
   END_DT    BIGINT,
   DATA_SOURCE    STRING
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_USR_FUNC_DAY';

DROP TABLE IF EXISTS JCFW.TYJ_TMP_G03004;
CREATE EXTERNAL TABLE JCFW.TYJ_TMP_G03004 (
   USR_ID    STRING,
   USR_NBR    STRING,
   EBOX_ID    STRING,
   CUST_ID    STRING,
   FEE_ITEM_CD    STRING,
   FEE_ITEM_CD2    STRING,
   FEE_ITEM_CD3    STRING,
   REC_FEE    INT,
   ACT_FEE    BIGINT
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_TMP_G03004';

DROP TABLE IF EXISTS JCFW.TYJ_SAM_VOICE_D;
CREATE EXTERNAL TABLE JCFW.TYJ_SAM_VOICE_D (
   USR_ID    STRING,
   USR_MOB_NBR    STRING,
   BRND_CD    SMALLINT,
   ROLLBACK_ID    STRING,
   DIR_TYP_CD    STRING,
   ROAM_TYP_CD    SMALLINT,
   TOLL_TYP_CD    SMALLINT,
   CALL_DT    INT,
   CALL_TIM    STRING,
   CALL_CNT    INT,
   CALL_DUR    INT,
   CALL_FREE_DUR    INT,
   SRV_TYP_CD    STRING,
   SUBSRV_TYP_CD    STRING,
   CARRY_TYP_CD    STRING,
   TOLL_DUR    INT,
   IMEI    STRING,
   IMSI    STRING,
   NET_TYP_CD    STRING,
   CMCC_BRANCH_CD    STRING,
   CALL_AREA_CD    STRING,
   LOCAL_CD    STRING,
   CELL_CD    STRING,
   B_NBR    STRING,
   B_AREA_CD    STRING,
   B_BRND_CD    SMALLINT,
   DISC_MOB_FEE    DECIMAL(7,2),
   DISC_TOLL_FEE    DECIMAL(7,2),
   DISC_INF_FEE    DECIMAL(7,2),
   MOB_FEE    DECIMAL(7,2),
   TOLL_FEE    DECIMAL(7,2)
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_SAM_VOICE_D';

DROP TABLE IF EXISTS JCFW.TYJ_G3_USR_MO;
CREATE EXTERNAL TABLE JCFW.TYJ_G3_USR_MO (
   USR_ID    STRING,
   CYCLE_FLAG    SMALLINT,
   USR_MOB_NBR    STRING,
   CMCC_BRANCH_CD    STRING,
   SIM_CARD_FLAG    SMALLINT,
   BRND_CD    SMALLINT,
   USR_INNET_DT    BIGINT,
   USR_STS_CD    BIGINT,
   TD_INFOPHONE_FLG    SMALLINT,
   TD_MOBILE_FLG    SMALLINT,
   TD_CRD_FLG    SMALLINT,
   TD_BOOK_FLG    SMALLINT,
   SPE_TRMNL_FLG    SMALLINT,
   TD_TRMNL_CUST_FLG    SMALLINT,
   USDTD_NTWK_CUST_FLG    SMALLINT,
   USD_VOICTD_NTWK_CUST_FLG    SMALLINT,
   USD_GPRSTD_NTWK_CUST_FLG    SMALLINT,
   USD_NTBKTD_NTWK_CUST_FLG    SMALLINT,
   FINAL_NON_TRMNL_USDT_CUST_FLG    SMALLINT,
   IMEI_NBR    STRING,
   LTE_4G_TERM_IND    SMALLINT,
   LTE_4G_NET_IND    SMALLINT
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_G3_USR_MO';

DROP TABLE IF EXISTS JCFW.TYJ_SCHOOL_AREA_USR;
CREATE EXTERNAL TABLE JCFW.TYJ_SCHOOL_AREA_USR (
   USR_ID    STRING,
   SCHOOL_CD    STRING,
   STUDENT_FLAG    SMALLINT,
   DIS_TYP_CD    SMALLINT
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_SCHOOL_AREA_USR';

DROP TABLE IF EXISTS JCFW.TYJ_SCHOOL_BASE_INF;
CREATE EXTERNAL TABLE JCFW.TYJ_SCHOOL_BASE_INF (
   TM_INTRVL_CD    BIGINT,
   SCHOOL_CD    STRING,
   SCHOOL_NAM    STRING,
   CMCC_BRANCH_CD    INT,
   SCH_ADDR    STRING,
   LONGITUDE    STRING,
   LATITUDE    STRING,
   SCH_HOME    STRING,
   SCH_PER    STRING,
   CHARGE_DEP    STRING,
   STUDENT_CNT    BIGINT,
   NEW_STUDENT_CNT    BIGINT,
   TEACHER_NUM    BIGINT,
   MOB_MARKET    STRING,
   GROUP_ID    STRING,
   AGREEMENT_IND    STRING,
   CHNL_IND    STRING,
   LINE_IND    STRING,
   WLAN_IND    STRING,
   VPMN_IND    STRING,
   MAS_IND    STRING,
   SMS_IND    STRING,
   MAIL_IND    STRING,
   CARD_IND    STRING,
   OTHER_IND    STRING,
   OTHER_MEMO    STRING,
   SPOT_IND    STRING
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_SCHOOL_BASE_INF';

DROP TABLE IF EXISTS JCFW.TYJ_GUSR_M2M_BND;
CREATE EXTERNAL TABLE JCFW.TYJ_GUSR_M2M_BND (
   GROUP_ID    STRING,
   USR_ID    STRING,
   CORP_BUSI_TYP    STRING,
   FLAT_TYP_CD    SMALLINT,
   PKG_CD    STRING,
   PKG_START_DT    INT,
   PKG_END_DT    INT,
   PKG_FLUX    BIGINT,
   USR_NBR    STRING,
   OPEN_4G_FLAG    SMALLINT,
   INDUSTRY_TYP_CD    STRING,
   GPRS_CNCT_TYP_CD    STRING,
   DATA_SOURCE    STRING,
   CARD_OPEN_DT    BIGINT,
   ORD_TYP_CD    SMALLINT,
   USR_CHG_DT    BIGINT,
   VALID_DT    BIGINT,
   INVALID_DT    BIGINT
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_GUSR_M2M_BND';

DROP TABLE IF EXISTS JCFW.TYJ_GCUST_DL100_ORD_MO;
CREATE EXTERNAL TABLE JCFW.TYJ_GCUST_DL100_ORD_MO (
   GROUP_ID    STRING,
   CORP_BUSI_TYP    STRING,
   CORP_PRDCT_CODE    STRING,
   DL_TYP_CD    STRING,
   PRDCT_PKG_ID    STRING,
   FLAT_TYP_CD    SMALLINT,
   EFF_DT    INT,
   ORD_TYP_CD    SMALLINT,
   CUST_CHG_DT    BIGINT
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_GCUST_DL100_ORD_MO';

DROP TABLE IF EXISTS JCFW.TYJ_GUSR_BND;
CREATE EXTERNAL TABLE JCFW.TYJ_GUSR_BND (
   GROUP_ID    STRING,
   USR_ID    STRING,
   CORP_BUSI_TYP    STRING,
   FLAT_TYP_CD    SMALLINT,
   CORP_PRDCT_CODE    STRING,
   USR_NBR    STRING,
   EFF_DT    INT,
   ORD_TYP_CD    SMALLINT,
   END_DT    BIGINT,
   FEE_TYP_CD    SMALLINT,
   CUST_CHG_DT    BIGINT,
   VALID_DT    BIGINT,
   INVALID_DT    BIGINT,
   PRDCT_SOURCE    SMALLINT
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_GUSR_BND';

DROP TABLE IF EXISTS JCFW.TYJ_GCUST_ORD;
CREATE EXTERNAL TABLE JCFW.TYJ_GCUST_ORD (
   GROUP_ID    STRING,
   CORP_BUSI_TYP    STRING,
   CORP_PRDCT_CODE    STRING,
   BASS_PRDCT_CD    STRING,
   FLAT_TYP_CD    SMALLINT,
   EFF_DT    INT,
   ORD_TYP_CD    SMALLINT,
   FEE_TYP_CD    SMALLINT,
   WEB_TYP_CD    SMALLINT,
   PRDCT_SOURCE    SMALLINT,
   PORTCOUNT    INT,
   WIDTH    BIGINT,
   TOT_CNT    INT,
   CUST_CHG_DT    BIGINT,
   VALID_DT    BIGINT,
   INVALID_DT    BIGINT
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_GCUST_ORD';

DROP TABLE IF EXISTS JCFW.TYJ_IMEI_USRCALL_MO;
CREATE EXTERNAL TABLE JCFW.TYJ_IMEI_USRCALL_MO (
   USR_ID    STRING,
   IMEI    STRING,
   USR_MOB_NBR    STRING,
   CMCC_BRANCH_CD    STRING,
   BRND_CD    SMALLINT,
   CALL_CNT    INT,
   PRVC_ACT_CALL_DAYS    BIGINT,
   ACT_CALL_DAYS    BIGINT,
   PRVC_ACT_CALL_CNT    BIGINT,
   ACT_CALL_CNT    BIGINT,
   CALL_DUR    INT
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_IMEI_USRCALL_MO';

DROP TABLE IF EXISTS JCFW.TYJ_DUR_DAY;
CREATE EXTERNAL TABLE JCFW.TYJ_DUR_DAY (
   DATA_DATE    BIGINT,
   BRND_CD    SMALLINT,
   HR_CD    STRING,
   CMCC_BRANCH_CD    STRING,
   DATA_SOURCE    SMALLINT,
   CALL_DT    BIGINT,
   CALL_CNT    BIGINT,
   MOB_DUR    BIGINT,
   TOLL_DUR    BIGINT,
   CALL_DUR    BIGINT,
   MOB_FEE    DECIMAL(16,2),
   TOLL_FEE    DECIMAL(16,2),
   TOTAL_FEE    DECIMAL(16,2)
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_DUR_DAY';

DROP TABLE IF EXISTS JCFW.TYJ_SMS_DAY;
CREATE EXTERNAL TABLE JCFW.TYJ_SMS_DAY (
   DATA_DATE    BIGINT,
   DEBET_DT    BIGINT,
   CALL_DT    BIGINT,
   FILE_SEQ    BIGINT,
   CMCC_BRANCH_CD    STRING,
   DATA_SOURCE    BIGINT,
   CALL_CNT    BIGINT
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_SMS_DAY';

DROP TABLE IF EXISTS JCFW.TYJ_SAM_USR_C;
CREATE EXTERNAL TABLE JCFW.TYJ_SAM_USR_C (
   CUST_ID    STRING
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_SAM_USR_C';

DROP TABLE IF EXISTS JCFW.TYJ_BUSY_DAY;
CREATE EXTERNAL TABLE JCFW.TYJ_BUSY_DAY (
   DATA_DATE    BIGINT,
   BRND_CD    SMALLINT,
   HR_CD    STRING,
   CMCC_BRANCH_CD    STRING,
   BUSY_TYP    BIGINT,
   CALL_DT    BIGINT,
   CELL_TYP_CD    SMALLINT,
   CALL_CNT    BIGINT,
   MOB_DUR    BIGINT,
   TOLL_DUR    BIGINT,
   CALL_DUR    BIGINT,
   MOB_FEE    DECIMAL(16,2),
   TOLL_FEE    DECIMAL(16,2),
   TOTAL_FEE    DECIMAL(16,2)
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_BUSY_DAY';

DROP TABLE IF EXISTS JCFW.TYJ_KPI_BRND_DAY;
CREATE EXTERNAL TABLE JCFW.TYJ_KPI_BRND_DAY (
   TM_INTRVL_CD    BIGINT,
   CMCC_BRANCH_CD    STRING,
   BRND_CD    SMALLINT,
   KPI_ID    BIGINT,
   USR_CNT    BIGINT,
   BASE_INCOME    DECIMAL(16,2)
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_KPI_BRND_DAY';

DROP TABLE IF EXISTS JCFW.TYJ_TD_USRCALL_DAY;
CREATE EXTERNAL TABLE JCFW.TYJ_TD_USRCALL_DAY (
   TM_INTRVL_CD    BIGINT,
   CNCT_NBR    STRING,
   HR_SEG_CD    SMALLINT,
   USR_ID    STRING,
   A_USR_NBR    STRING,
   AGGREGATE_SEQ    SMALLINT,
   AGGREGATE_DT    BIGINT,
   DIR_TYP_CD    STRING,
   ROAM_TYP_CD    SMALLINT,
   TOLL_TYP_CD    SMALLINT,
   SRV_TYP_CD    STRING,
   SUBSRV_TYP_CD    STRING,
   RATE_TYP_CD    STRING,
   BILL_TYP_CD    STRING,
   CARRY_TYP_CD    STRING,
   ICP_STAT_CD    STRING,
   B_AREA_CD    STRING,
   B_BRND_CD    SMALLINT,
   B_OPER_CD    STRING,
   CALL_AREA_CD    STRING,
   FILE_TYP    STRING,
   CX_FILE_IND    STRING,
   NET_TYP_CD    STRING,
   BRND_CD    SMALLINT,
   CMCC_BRANCH_CD    STRING,
   CALL_CNT    BIGINT,
   CALL_DUR    BIGINT,
   CALL_FLUX    BIGINT,
   CALL_FREE_DUR    BIGINT,
   DEBET_MOB_DUR    BIGINT,
   DEBET_TOLL_DUR    BIGINT,
   MOB_FEE    DECIMAL(10,2),
   TOLL_FEE    DECIMAL(10,2),
   INF_FEE    DECIMAL(10,2),
   MOB_DEBET1_FEE    DECIMAL(10,2),
   TOLL_DEBET1_FEE    DECIMAL(10,2),
   INF_DEBET1_FEE    DECIMAL(10,2),
   VPMN_IND    STRING,
   FEE_DISCOUNT_TYP_CD    SMALLINT
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_TD_USRCALL_DAY';

DROP TABLE IF EXISTS JCFW.TYJ_TD_USR_DAY;
CREATE EXTERNAL TABLE JCFW.TYJ_TD_USR_DAY (
   TM_INTRVL_CD    BIGINT,
   USR_ID    STRING,
   USR_NBR    STRING,
   CMCC_BRANCH_CD    STRING,
   BRND_CD    SMALLINT,
   PKG_CD    SMALLINT,
   DATA_IND    SMALLINT,
   VIDEO_IND    SMALLINT,
   TD_IND    SMALLINT,
   USR_INNET_IND    SMALLINT,
   NTBK_IND    SMALLINT,
   LTE_USED_IND    SMALLINT
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_TD_USR_DAY';

DROP TABLE IF EXISTS JCFW.TYJ_NBRSEG_SORT;
CREATE EXTERNAL TABLE JCFW.TYJ_NBRSEG_SORT (
   BEGIN_NBR    STRING,
   END_NBR    STRING,
   TELCOM_CPY    STRING,
   BRND_CD    SMALLINT,
   VALID_IND    SMALLINT,
   COOPER_CD    STRING,
   DATA_DATE    BIGINT
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES ('field.delim'='\001','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_NBRSEG_SORT';

DROP TABLE IF EXISTS JCFW.TYJ_NBRSEG_SPLIT;
CREATE EXTERNAL TABLE JCFW.TYJ_NBRSEG_SPLIT (
   BEGIN_NBR    STRING,
   END_NBR    STRING,
   TELCOM_CPY    STRING,
   BRND_CD    SMALLINT,
   VALID_IND    SMALLINT,
   COOPER_CD    STRING,
   DATA_DATE    BIGINT
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_NBRSEG_SPLIT';

DROP TABLE IF EXISTS JCFW.TYJ_NBRSEG_SPLIT_FINAL;
CREATE EXTERNAL TABLE JCFW.TYJ_NBRSEG_SPLIT_FINAL (
   BEGIN_NBR    STRING,
   END_NBR    STRING,
   TELCOM_CPY    STRING,
   BRND_CD    SMALLINT,
   VALID_IND    SMALLINT,
   COOPER_CD    STRING,
   DATA_DATE    BIGINT
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_NBRSEG_SPLIT_FINAL';

DROP TABLE IF EXISTS JCFW.TYJ_USR_FLOW;
CREATE EXTERNAL TABLE JCFW.TYJ_USR_FLOW (
   USR_ID    STRING,
   USR_MOB_NBR    STRING,
   BRND_CD    INT,
   USR_INNET_DT    INT,
   USR_STS_CD    INT,
   USR_CHG_DT    INT,
   SIM_CARD_FLAG    INT,
   CMCC_BRANCH_CD    STRING,
   VALID_DT    INT,
   INVALID_DT    INT,
   MRKT_CHNL_CD    STRING,
   IMSI    STRING,
   INNET_IND    SMALLINT,
   CUST_ID    STRING,
   CELL_TYP_CD    SMALLINT
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_USR_FLOW';

DROP TABLE IF EXISTS JCFW.TYJ_CORP_BUSI_DAY;
CREATE EXTERNAL TABLE JCFW.TYJ_CORP_BUSI_DAY (
   TM_INTRVL_CD    BIGINT,
   GROUP_ID    STRING,
   GUSR_ID    STRING,
   CORP_PRDCT_CODE    STRING,
   USR_CNT    INT,
   SMS_CNT    INT,
   MMS_CNT    INT,
   CALL_FLUX    BIGINT,
   WAP_CNT    INT,
   WEB_CNT    BIGINT,
   MAIL_CNT    BIGINT,
   MOB_DUR    INT
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_CORP_BUSI_DAY';

DROP TABLE IF EXISTS JCFW.TYJ_GCUST_DL100_ORD;
CREATE EXTERNAL TABLE JCFW.TYJ_GCUST_DL100_ORD (
   GROUP_ID    STRING,
   CORP_BUSI_TYP    STRING,
   CORP_PRDCT_CODE    STRING,
   DL_TYP_CD    STRING,
   PRDCT_PKG_ID    STRING,
   FLAT_TYP_CD    SMALLINT,
   EFF_DT    INT,
   ORD_TYP_CD    SMALLINT,
   CUST_CHG_DT    BIGINT
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES ('field.delim'='\001','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_GCUST_DL100_ORD';

DROP TABLE IF EXISTS JCFW.TYJ_INDAPPLY_CODE_USR_DAY;
CREATE EXTERNAL TABLE JCFW.TYJ_INDAPPLY_CODE_USR_DAY (
   TM_INTRVL_CD    BIGINT,
   USR_NBR    STRING,
   CMCC_BRANCH_CD    STRING,
   SP_SERV_CD    STRING,
   SP_SUBBUSI_CD    STRING,
   SOURCE    STRING,
   UP_CALL_CNT    BIGINT,
   DOWN_CALL_CNT    BIGINT,
   MOB_FEE    DECIMAL(10,2),
   TOLL_FEE    DECIMAL(10,2),
   INF_FEE    DECIMAL(10,2)
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_INDAPPLY_CODE_USR_DAY';

DROP TABLE IF EXISTS JCFW.TYJ_INDAPPLY_BND_USR;
CREATE EXTERNAL TABLE JCFW.TYJ_INDAPPLY_BND_USR (
   CORP_PRDCT_CODE    STRING,
   USR_ID    STRING,
   EFF_DT    BIGINT,
   INVALID_DT    BIGINT,
   VALID_IND    SMALLINT,
   LAST_CALL_DT    BIGINT,
   SP_SERV_CD    STRING,
   SP_SUBBUSI_CD    STRING,
   SP_CODE    STRING
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_INDAPPLY_BND_USR';

DROP TABLE IF EXISTS JCFW.TYJ_JF_CHRG_USR;
CREATE EXTERNAL TABLE JCFW.TYJ_JF_CHRG_USR (
   SERIAL_NO    STRING,
   CMCC_BRANCH_CD    STRING,
   AGENT_CD    STRING,
   USR_NBR    STRING,
   AIR_CHRG_PLACE    STRING,
   BRND_CD    SMALLINT,
   CHRG_DT    BIGINT,
   CHRG_TIM    STRING,
   AGENT_AMT    BIGINT,
   GMCC_AMT    BIGINT,
   CHECK_FLAG    BIGINT,
   TRADE_TYP    SMALLINT,
   TM_INTRVL_CD    BIGINT
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_JF_CHRG_USR';

DROP TABLE IF EXISTS JCFW.TYJ_P_4G_USR;
CREATE EXTERNAL TABLE JCFW.TYJ_P_4G_USR (
   STAT_DT    BIGINT,
   USR_ID    STRING,
   USR_MOB_NBR    STRING,
   START_DT    STRING,
   END_DT    STRING,
   CHNL_CD    STRING
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_P_4G_USR';

DROP TABLE IF EXISTS JCFW.TYJ_4G_USR_M;
CREATE EXTERNAL TABLE JCFW.TYJ_4G_USR_M (
   STAT_MO    BIGINT,
   USR_ID    STRING,
   USR_NBR    STRING,
   SIM_CARD_FLAG    BIGINT,
   BRND_CD    SMALLINT,
   CMCC_BRANCH_CD    STRING,
   USR_STS_CD    BIGINT,
   USR_INNET_DT    BIGINT,
   IMEI    STRING,
   TERM_DEVICE_ID    STRING,
   LTE_CRD_IND    SMALLINT,
   LTE_MOBILE_IND    SMALLINT,
   LTE_MIFI_IND    SMALLINT,
   LTE_CPE_IND    SMALLINT,
   LTE_4G_TERM_IND    SMALLINT,
   LTE_4G_NET_IND    SMALLINT,
   SWTON_4G_USR_IND    SMALLINT
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_4G_USR_M';

DROP TABLE IF EXISTS JCFW.TYJ_GCUST_SPECIALLINE_ORD;
CREATE EXTERNAL TABLE JCFW.TYJ_GCUST_SPECIALLINE_ORD (
   GUSR_ID    STRING,
   YJ_PRD_CODE    STRING,
   GROUP_ID    STRING,
   CORP_PRDCT_CODE    STRING,
   BASS_PRDCT_CD    STRING,
   DISCOUNT    DECIMAL(3,2),
   PORTCOUNT    INT,
   WIDTH    BIGINT,
   TOT_CNT    INT,
   EFF_DT    INT,
   ORD_TYP_CD    SMALLINT,
   CUST_CHG_DT    INT,
   VALID_DT    INT,
   INVALID_DT    INT
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_GCUST_SPECIALLINE_ORD';

DROP TABLE IF EXISTS JCFW.TYJ_VPMN_MEMBER;
CREATE EXTERNAL TABLE JCFW.TYJ_VPMN_MEMBER (
   TM_INTRVL_CD    BIGINT,
   CORP_ID    STRING,
   USR_NBR    STRING,
   CORP_INN_ID    STRING,
   CMCC_BRANCH_CD    STRING
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_VPMN_MEMBER';

DROP TABLE IF EXISTS JCFW.TYJ_TD_CDR;
CREATE EXTERNAL TABLE JCFW.TYJ_TD_CDR (
   A_SWITCH_CD    STRING,
   CMCC_BRANCH_CD    STRING,
   ROLLBACK_ID    STRING,
   ROLLBACK_CNT    SMALLINT,
   USR_MOB_NBR    STRING,
   A_OPER_CD    STRING,
   A_BRND_CD    SMALLINT,
   A_USR_TYP_CD    STRING,
   USR_PKG_TYP    STRING,
   ROAM_TYP_CD    SMALLINT,
   VISITED_SWITCH_CD    STRING,
   CALL_AREA_CD    STRING,
   CALL_DT    INT,
   CALL_TIM    STRING,
   HR_CD    SMALLINT,
   DEBET_DT    INT,
   TM_INTRVL_CD    INT,
   CARRY_TYP_CD    STRING,
   CNCT_NBR    STRING,
   TOLL_TYP_CD    SMALLINT,
   DIR_TYP_CD    STRING,
   SRV_TYP_CD    STRING,
   SUBSRV_TYP_CD    STRING,
   RATE_TYP_CD    STRING,
   B_NBR    STRING,
   B_SWITCH_CD    STRING,
   B_OPER_CD    STRING,
   B_BRND_CD    SMALLINT,
   B_USR_TYP_CD    STRING,
   B_AREA_CD    STRING,
   CALL_DUR    INT,
   TOLL_DUR    INT,
   CALL_FLUX    INT,
   CALL_CNT    SMALLINT,
   MOB_FEE    DECIMAL(7,2),
   TOLL_FEE    DECIMAL(7,2),
   INF_FEE    DECIMAL(7,2),
   IMSI    STRING,
   LOCAL_CD    STRING,
   CELL_CD    STRING,
   OUT_ROUTE_CD    STRING,
   IN_ROUTE_CD    STRING,
   ROUTE_TYP    STRING,
   SWITCH_NBR    STRING,
   ROAM_NBR    STRING,
   IMEI    STRING,
   BILL_TYP_CD    STRING,
   DISC_CD    STRING,
   VPMN_IND    STRING,
   DISC_MOB_FEE    DECIMAL(7,2),
   DISC_TOLL_FEE    DECIMAL(7,2),
   DISC_INF_FEE    DECIMAL(7,2),
   DISC_FEE    DECIMAL(7,2),
   CALL_FREE_DUR    INT,
   ACCT_BAL    DECIMAL(10,2),
   ICP_STAT_CD    STRING,
   LOAD_ID    INT,
   FILE_TYP    STRING,
   CX_FILE_IND    STRING,
   NET_TYP_CD    STRING,
   FLAG_IND    STRING
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_TD_CDR';

DROP TABLE IF EXISTS JCFW.TYJ_TMP_G04017;
CREATE EXTERNAL TABLE JCFW.TYJ_TMP_G04017 (
   A_SWITCH_CD    STRING,
   CMCC_BRANCH_CD    STRING,
   ROLLBACK_ID    STRING,
   ROLLBACK_CNT    SMALLINT,
   USR_MOB_NBR    STRING,
   A_OPER_CD    STRING,
   A_BRND_CD    SMALLINT,
   A_USR_TYP_CD    STRING,
   USR_PKG_TYP    STRING,
   ROAM_TYP_CD    SMALLINT,
   VISITED_SWITCH_CD    STRING,
   CALL_AREA_CD    STRING,
   CALL_DT    BIGINT,
   CALL_TIM    STRING,
   HR_CD    SMALLINT,
   DEBET_DT    BIGINT,
   TM_INTRVL_CD    BIGINT,
   CARRY_TYP_CD    STRING,
   CNCT_NBR    STRING,
   TOLL_TYP_CD    SMALLINT,
   DIR_TYP_CD    STRING,
   SRV_TYP_CD    STRING,
   SUBSRV_TYP_CD    STRING,
   RATE_TYP_CD    STRING,
   B_NBR    STRING,
   B_SWITCH_CD    STRING,
   B_OPER_CD    STRING,
   B_BRND_CD    SMALLINT,
   B_USR_TYP_CD    STRING,
   B_AREA_CD    STRING,
   CALL_DUR    BIGINT,
   TOLL_DUR    BIGINT,
   CALL_FLUX    BIGINT,
   CALL_CNT    SMALLINT,
   MOB_FEE    DECIMAL(7,2),
   TOLL_FEE    DECIMAL(7,2),
   INF_FEE    DECIMAL(7,2),
   IMSI    STRING,
   LOCAL_CD    STRING,
   CELL_CD    STRING,
   OUT_ROUTE_CD    STRING,
   IN_ROUTE_CD    STRING,
   ROUTE_TYP    STRING,
   SWITCH_NBR    STRING,
   ROAM_NBR    STRING,
   IMEI    STRING,
   BILL_TYP_CD    STRING,
   DISC_CD    STRING,
   VPMN_IND    STRING,
   DISC_MOB_FEE    DECIMAL(7,2),
   DISC_TOLL_FEE    DECIMAL(7,2),
   DISC_INF_FEE    DECIMAL(7,2),
   DISC_FEE    DECIMAL(7,2),
   CALL_FREE_DUR    SMALLINT,
   ACCT_BAL    DECIMAL(10,2),
   ICP_STAT_CD    STRING,
   LOAD_ID    BIGINT,
   NET_TYP_CD    STRING,
   VIDEO_TYP_CD    STRING
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_TMP_G04017';

DROP TABLE IF EXISTS JCFW.TYJ_DUR_LACK;
CREATE EXTERNAL TABLE JCFW.TYJ_DUR_LACK (
   A_SWITCH_CD    STRING,
   CMCC_BRANCH_CD    STRING,
   ROLLBACK_ID    STRING,
   ROLLBACK_CNT    SMALLINT,
   USR_MOB_NBR    STRING,
   A_OPER_CD    STRING,
   A_BRND_CD    SMALLINT,
   A_USR_TYP_CD    STRING,
   USR_PKG_TYP    STRING,
   ROAM_TYP_CD    SMALLINT,
   VISITED_SWITCH_CD    STRING,
   CALL_AREA_CD    STRING,
   CALL_DT    BIGINT,
   CALL_TIM    STRING,
   HR_CD    SMALLINT,
   DEBET_DT    BIGINT,
   TM_INTRVL_CD    BIGINT,
   CARRY_TYP_CD    STRING,
   CNCT_NBR    STRING,
   TOLL_TYP_CD    SMALLINT,
   DIR_TYP_CD    STRING,
   SRV_TYP_CD    STRING,
   SUBSRV_TYP_CD    STRING,
   RATE_TYP_CD    STRING,
   B_NBR    STRING,
   B_SWITCH_CD    STRING,
   B_OPER_CD    STRING,
   B_BRND_CD    SMALLINT,
   B_USR_TYP_CD    STRING,
   B_AREA_CD    STRING,
   CALL_DUR    BIGINT,
   TOLL_DUR    BIGINT,
   CALL_FLUX    BIGINT,
   CALL_CNT    SMALLINT,
   MOB_FEE    DECIMAL(7,2),
   TOLL_FEE    DECIMAL(7,2),
   INF_FEE    DECIMAL(7,2),
   IMSI    STRING,
   LOCAL_CD    STRING,
   CELL_CD    STRING,
   OUT_ROUTE_CD    STRING,
   IN_ROUTE_CD    STRING,
   ROUTE_TYP    STRING,
   SWITCH_NBR    STRING,
   ROAM_NBR    STRING,
   IMEI    STRING,
   BILL_TYP_CD    STRING,
   DISC_CD    STRING,
   VPMN_IND    STRING,
   DISC_MOB_FEE    DECIMAL(7,2),
   DISC_TOLL_FEE    DECIMAL(7,2),
   DISC_INF_FEE    DECIMAL(7,2),
   DISC_FEE    DECIMAL(7,2),
   CALL_FREE_DUR    SMALLINT,
   ACCT_BAL    DECIMAL(10,2),
   ICP_STAT_CD    STRING,
   LOAD_ID    STRING,
   FILE_TYP    STRING,
   CX_FILE_IND    STRING
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_DUR_LACK';

DROP TABLE IF EXISTS JCFW.TYJ_M2M_TERM_USR;
CREATE EXTERNAL TABLE JCFW.TYJ_M2M_TERM_USR (
   USR_NBR    STRING,
   GROUP_NAM    STRING,
   GROUP_ID    STRING,
   INDUSTRY_TYP_CD    STRING,
   GPRS_CNCT_TYP_CD    STRING,
   DATA_SOURCE    STRING,
   CARD_OPEN_DT    BIGINT,
   BUSI_STS_CD    STRING,
   USR_CHG_DT    BIGINT,
   TOTAL_INCOME    DECIMAL(12,2)
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_M2M_TERM_USR';

DROP TABLE IF EXISTS JCFW.TYJ_TMP_G02047;
CREATE EXTERNAL TABLE JCFW.TYJ_TMP_G02047 (
   USR_ID    STRING,
   IMEI    STRING,
   USR_MOB_NBR    STRING,
   CALL_CNT    INT,
   CALL_DUR    INT
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_TMP_G02047';

DROP TABLE IF EXISTS JCFW.TYJ_BUSI_REP_MO;
CREATE EXTERNAL TABLE JCFW.TYJ_BUSI_REP_MO (
   TM_INTRVL_CD    BIGINT,
   ITEM_CD    STRING,
   ITEM_VALUE    DECIMAL(14,2)
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES ('field.delim'='|','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_BUSI_REP_MO';

DROP TABLE IF EXISTS JCFW.TYJ_SP_SETL;
CREATE EXTERNAL TABLE JCFW.TYJ_SP_SETL (
   TM_INTRVL_CD    BIGINT,
   SP_SERV_CD    STRING,
   SP_CODE    STRING,
   SP_BUSICLASS_CD    STRING,
   CMCC_BRANCH_CD    STRING,
   SERVICE_FEE    DECIMAL(16,2),
   ADDRESS_FEE    DECIMAL(16,2),
   SETL_TOTAL_FEE    DECIMAL(16,2)
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_SP_SETL';

DROP TABLE IF EXISTS JCFW.TYJ_TMP_G04018;
CREATE EXTERNAL TABLE JCFW.TYJ_TMP_G04018 (
   TM_INTRVL_CD    BIGINT,
   USR_NBR    STRING,
   BND_USR_NBR    STRING,
   APN    STRING,
   CHRG_ID    STRING,
   IDLE_UP_FLUX    BIGINT,
   IDLE_DOWN_FLUX    BIGINT,
   BUSY_UP_FLUX    BIGINT,
   BUSY_DOWN_FLUX    BIGINT,
   IDLE_DUR    BIGINT,
   BUSY_DUR    BIGINT,
   CALL_TIM    STRING,
   CALL_DUR    BIGINT,
   SP_SUBBUSI_CD    STRING,
   BUSI_UP_FLUX    BIGINT,
   BUSI_DOWN_FLUX    BIGINT,
   BUSI_CALL_DUR    DECIMAL(12,2),
   NET_TYP_CD    STRING,
   IMEI    STRING,
   VST_PRVC_CD    STRING
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_TMP_G04018';

DROP TABLE IF EXISTS JCFW.TYJ_LACK_DUR_CORRECT;
CREATE EXTERNAL TABLE JCFW.TYJ_LACK_DUR_CORRECT (
   DATA_DATE    BIGINT,
   BRND_CD    SMALLINT,
   HR_CD    STRING,
   CMCC_BRANCH_CD    STRING,
   CORRECT_FLAG    BIGINT,
   CALL_DT    BIGINT,
   CALL_CNT    BIGINT,
   MOB_DUR    BIGINT,
   TOLL_DUR    BIGINT,
   CALL_DUR    BIGINT,
   MOB_FEE    DECIMAL(16,2),
   TOLL_FEE    DECIMAL(16,2),
   TOTAL_FEE    DECIMAL(16,2)
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_LACK_DUR_CORRECT';

DROP TABLE IF EXISTS JCFW.TYJ_VOC_USRCALL_DAY_FIRST;
CREATE EXTERNAL TABLE JCFW.TYJ_VOC_USRCALL_DAY_FIRST (
   CALL_DT    INT,
   BRND_CD    SMALLINT,
   CMCC_BRANCH_CD    STRING,
   CNCT_NBR    STRING,
   HR_CD    SMALLINT,
   AGGREGATE_SEQ    SMALLINT,
   AGGREGATE_DT    INT,
   DIR_TYP_CD    STRING,
   ROAM_TYP_CD    SMALLINT,
   TOLL_TYP_CD    SMALLINT,
   SRV_TYP_CD    STRING,
   SUBSRV_TYP_CD    STRING,
   RATE_TYP_CD    STRING,
   BILL_TYP_CD    STRING,
   CARRY_TYP_CD    STRING,
   ICP_STAT_CD    STRING,
   B_AREA_CD    STRING,
   B_BRND_CD    SMALLINT,
   B_OPER_CD    STRING,
   DEBET_DT    INT,
   CALL_AREA_CD    STRING,
   PKG_CD    SMALLINT,
   CELL_TYP_CD    SMALLINT,
   TM_INTRVL_CD    INT,
   CALL_CNT    INT,
   CALL_DUR    BIGINT,
   CALL_FLUX    BIGINT,
   CALL_FREE_DUR    INT,
   DEBET_MOB_DUR    INT,
   DEBET_TOLL_DUR    INT,
   MOB_FEE    DECIMAL(10,2),
   TOLL_FEE    DECIMAL(10,2),
   INF_FEE    DECIMAL(10,2),
   MOB_DEBET1_FEE    DECIMAL(10,2),
   TOLL_DEBET1_FEE    DECIMAL(10,2),
   INF_DEBET1_FEE    DECIMAL(10,2),
   USR_CNT    INT,
   VPMN_IND    STRING,
   FEE_DISCOUNT_TYP_CD    SMALLINT,
   NET_TYP_CD    STRING
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_VOC_USRCALL_DAY_FIRST';

DROP TABLE IF EXISTS JCFW.TYJ_KPI_LOG_CLOUD;
CREATE EXTERNAL TABLE JCFW.TYJ_KPI_LOG_CLOUD (
   STAT_DT    INT,
   FILE_NAM    STRING,
   SOURCE_ID    STRING,
   REC_CNT    BIGINT,
   REC_CNT_2G    BIGINT,
   REC_CNT_3G    BIGINT,
   UP_FLUX    BIGINT,
   DOWN_FLUX    BIGINT,
   T_UP_FLUX    BIGINT,
   T_DOWN_FLUX    BIGINT
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES ('field.delim'='&','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_KPI_LOG_CLOUD';

DROP TABLE IF EXISTS JCFW.TYJ_ECHNL_TERM_SELL_D;
CREATE EXTERNAL TABLE JCFW.TYJ_ECHNL_TERM_SELL_D (
   TM_INTRVL_CD    BIGINT,
   SRC_TYP_CD    STRING,
   PROVINCE_TYP    STRING,
   CONTRACT_TERM_CNT    BIGINT,
   BARE_TERM_CNT    BIGINT,
   ORDER_TERM_CNT    BIGINT,
   ORDER_MOB_TERM_CNT    BIGINT,
   C_TERM_CNT    BIGINT
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_ECHNL_TERM_SELL_D';

DROP TABLE IF EXISTS JCFW.TYJ_B_AREA_CD_04022;
CREATE EXTERNAL TABLE JCFW.TYJ_B_AREA_CD_04022 (
   B_NBR    STRING,
   B_AREA_CD    STRING,
   B_BRND_CD    STRING
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_B_AREA_CD_04022';

DROP TABLE IF EXISTS JCFW.TO_CORP_MBR;
CREATE EXTERNAL TABLE JCFW.TO_CORP_MBR (
   ORDER_SEQ    STRING,
   AREA_CD    STRING,
   GCUST_ID    STRING,
   USR_ID    STRING,
   USR_NBR    STRING,
   USR_NAM    STRING,
   IMP_LVL_CD    STRING,
   ROLE_TYP    STRING,
   WRN_BAL    STRING,
   WRN_INF    STRING,
   CREAT_DT    INT,
   MBR_STS_CD    STRING,
   STS_DT    INT,
   CMCC_BRANCH_CD    STRING
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/ODS/TO_CORP_MBR';

DROP TABLE IF EXISTS JCFW.TYJ_CMNCT_USR;
CREATE EXTERNAL TABLE JCFW.TYJ_CMNCT_USR (
   USR_MOB_NBR    STRING,
   CMCC_BRANCH_CD    STRING,
   BRND_CD    SMALLINT,
   PKG_CD    SMALLINT,
   MUM_3MON_IND    STRING,
   FIRST_CALL_DT    INT,
   LAST_CALL_DT    INT,
   FIRST_LOCAL_CD    STRING,
   FIRST_CELL_CD    STRING
)
PARTITIONED BY (branch STRING)
STORED AS PARQUET
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_CMNCT_USR'
TBLPROPERTIES ('serialization.null.format' ='NVL','serialization.encoding' ='GBK');

DROP TABLE IF EXISTS JCFW.TYJ_VOC_USRCALL_DAY;
CREATE EXTERNAL TABLE JCFW.TYJ_VOC_USRCALL_DAY (
   CALL_DT    INT,
   BRND_CD    SMALLINT,
   CMCC_BRANCH_CD    STRING,
   CNCT_NBR    STRING,
   HR_CD    SMALLINT,
   AGGREGATE_SEQ    SMALLINT,
   AGGREGATE_DT    INT,
   DIR_TYP_CD    STRING,
   ROAM_TYP_CD    SMALLINT,
   TOLL_TYP_CD    SMALLINT,
   SRV_TYP_CD    STRING,
   SUBSRV_TYP_CD    STRING,
   RATE_TYP_CD    STRING,
   BILL_TYP_CD    STRING,
   CARRY_TYP_CD    STRING,
   ICP_STAT_CD    STRING,
   B_AREA_CD    STRING,
   B_BRND_CD    SMALLINT,
   B_OPER_CD    STRING,
   DEBET_DT    INT,
   CALL_AREA_CD    STRING,
   PKG_CD    SMALLINT,
   CELL_TYP_CD    SMALLINT,
   TM_INTRVL_CD    INT,
   CALL_CNT    INT,
   CALL_DUR    BIGINT,
   CALL_FLUX    BIGINT,
   CALL_FREE_DUR    INT,
   DEBET_MOB_DUR    INT,
   DEBET_TOLL_DUR    INT,
   MOB_FEE    DECIMAL(10,2),
   TOLL_FEE    DECIMAL(10,2),
   INF_FEE    DECIMAL(10,2),
   MOB_DEBET1_FEE    DECIMAL(10,2),
   TOLL_DEBET1_FEE    DECIMAL(10,2),
   INF_DEBET1_FEE    DECIMAL(10,2),
   USR_CNT    INT,
   VPMN_IND    STRING,
   FEE_DISCOUNT_TYP_CD    SMALLINT,
   NET_TYP_CD    STRING
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_VOC_USRCALL_DAY';

DROP TABLE IF EXISTS JCFW.TYJ_BUSI_FLUCT_CTRL;
CREATE EXTERNAL TABLE JCFW.TYJ_BUSI_FLUCT_CTRL (
   DATA_DATE    INT,
   BUSI_CLASS    INT,
   EXPECT_LOWER_LINE    DECIMAL(7,4),
   EXPECT_UPPER_LINE    DECIMAL(7,4),
   TRUST_LOWER_LINE    DECIMAL(7,4),
   TRUST_UPPER_LINE    DECIMAL(7,4),
   VALID_FLAG    INT,
   MODF_TIME    STRING,
   COMMENTS    STRING
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES ('field.delim'='\001','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_BUSI_FLUCT_CTRL';

ALTER TABLE JCFW.TYJ_BUSI_FLUCT_CTRL ADD PARTITION (branch='GMCC');

DROP TABLE IF EXISTS JCFW.FEE_CHAFEN_2016;
CREATE EXTERNAL TABLE JCFW.FEE_CHAFEN_2016 (
   BILL_ACCT_CD    STRING,
   CANFEN_BILI    DECIMAL(12,7),
   FEE_ITEM_CD3    STRING,
   FEE_ITEM_NAM    STRING
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES ('field.delim'='&','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/FEE_CHAFEN_2016';

ALTER TABLE JCFW.FEE_CHAFEN_2016 ADD PARTITION (branch='GMCC');

DROP TABLE IF EXISTS JCFW.LXZ_G03004_INF_CUST_FINAL;
CREATE EXTERNAL TABLE JCFW.LXZ_G03004_INF_CUST_FINAL (
   USR_ID    STRING,
   USR_MOB_NBR    STRING,
   CUST_ID    STRING,
   EBOX_ID    STRING,
   PRICE_FEE    INT
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES ('field.delim'='&','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/LXZ_G03004_INF_CUST_FINAL';

ALTER TABLE JCFW.LXZ_G03004_INF_CUST_FINAL ADD PARTITION (branch='GMCC');

DROP TABLE IF EXISTS JCFW.TYJ_USR_INTEGRAL;
CREATE EXTERNAL TABLE JCFW.TYJ_USR_INTEGRAL (
   TM_INTRVL_CD    BIGINT,
   USR_ID    STRING,
   CMCC_BRANCH_CD    STRING,
   BRND_CD    SMALLINT,
   CONSUME_INTEGRAL    BIGINT,
   PRMT_INTEGRAL    BIGINT,
   CREDIT_INTEGRAL    BIGINT,
   INNET_INTEGRAL    BIGINT,
   AWARD_INTEGRAL    BIGINT,
   XST_CONSUME_INTEGRAL    BIGINT,
   XST_PRMT_INTEGRAL    BIGINT,
   USR_CAN_CHG_INTEGRAL    BIGINT,
   ACCUM_USR_INTEGRAL_AMT    BIGINT,
   CONSUME_INTEGRAL_AMT    BIGINT,
   CURRY_HAVECHG_INTEGRAL    BIGINT,
   TERM_CAN_CHG_INTEGRAL    BIGINT,
   T_CAN_CHG_INTEGRAL    BIGINT,
   T1_CAN_CHG_INTEGRAL    BIGINT,
   T2_CAN_CHG_INTEGRAL    BIGINT,
   HIS_CAN_CHG_INTEGRAL    BIGINT,
   END_CLEAR_INTEGRAL    BIGINT,
   CONSUME_OUTCLEAR_INTEGRAL    BIGINT,
   PRMT_OUTCLEAR_INTEGRAL    BIGINT,
   CHGNET_CLEAR_INTEGRAL    BIGINT
)
PARTITIONED BY (branch STRING,month INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES ('field.delim'='\001','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_USR_INTEGRAL';

DROP TABLE IF EXISTS JCFW.TYJ_PERS_IMS_USR_INF_D;
CREATE EXTERNAL TABLE JCFW.TYJ_PERS_IMS_USR_INF_D (
   IMS_USR_ID    STRING,
   IMS_CUST_ID    STRING,
   USR_INNET_DT    INT,
   FIX_PHONE_NBR    STRING,
   CMCC_BRANCH_CD    STRING,
   USR_STS_CD    STRING,
   VALID_DT    INT,
   INVALID_DT    INT
)
PARTITIONED BY (branch STRING,month INT,day INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES ('field.delim'='\001','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/TYJ/GIF/GIF/TYJ_PERS_IMS_USR_INF_D';


