----bd_o租户脚本----
DROP TABLE IF EXISTS JCFW.TR_INDUSTRIAL_PARK;
CREATE EXTERNAL TABLE JCFW.TR_INDUSTRIAL_PARK (
   STD_AREA_ID    STRING,
   AREA_NAM    STRING,
   INDUSTRIAL_PARK_TYP    STRING,
   COORDINATE_POINTS    STRING,
   DESCRIPTION    STRING,
   COORDINATE_SYSTEM    STRING
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='UTF-8')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/JRCL/BD_O/REF/TR_INDUSTRIAL_PARK';

ALTER TABLE JCFW.TR_INDUSTRIAL_PARK ADD PARTITION (branch='GMCC');

DROP TABLE IF EXISTS JCFW.TR_BUSINESS_ZONE;
CREATE EXTERNAL TABLE JCFW.TR_BUSINESS_ZONE (
   STD_AREA_ID    STRING,
   AREA_NAM    STRING,
   COORDINATE_POINTS    STRING,
   DESCRIPTION    STRING,
   COORDINATE_SYSTEM    STRING
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='UTF-8')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/JRCL/BD_O/REF/TR_BUSINESS_ZONE';

ALTER TABLE JCFW.TR_BUSINESS_ZONE ADD PARTITION (branch='GMCC');

DROP TABLE IF EXISTS JCFW.TR_DORMITORY_AREA;
CREATE EXTERNAL TABLE JCFW.TR_DORMITORY_AREA (
   STD_AREA_ID    STRING,
   AREA_NAM    STRING,
   COORDINATE_POINTS    STRING,
   DESCRIPTION    STRING,
   COORDINATE_SYSTEM    STRING
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES ('field.delim'='@#$','serialization.null.format' ='NVL','serialization.encoding' ='UTF-8')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/JRCL/BD_O/REF/TR_DORMITORY_AREA';

ALTER TABLE JCFW.TR_DORMITORY_AREA ADD PARTITION (branch='GMCC');

DROP TABLE IF EXISTS JCFW.TR_HOT_AREA_CELL;
CREATE EXTERNAL TABLE JCFW.TR_HOT_AREA_CELL (
   CGI    STRING,
   CMCC_BRANCH_CD    STRING,
   CITY_NAM    STRING,
   AREA_NAM    STRING,
   AREA_TYP    STRING
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES ('field.delim'=',','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/JRCL/BD_O/REF/TR_HOT_AREA_CELL';

ALTER TABLE JCFW.TR_HOT_AREA_CELL ADD PARTITION (branch='GMCC');

DROP TABLE IF EXISTS JCFW.TR_APP_TYP;
CREATE EXTERNAL TABLE JCFW.TR_APP_TYP (
   STAT_DT    STRING,
   APP_TYP_ID    STRING,
   APP_TYP_NAM    STRING,
   APP_ID    STRING,
   APP_NAME    STRING
)
PARTITIONED BY (branch STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES ('field.delim'=',','serialization.null.format' ='NVL','serialization.encoding' ='GBK')
STORED AS TEXTFILE
LOCATION '/tenant/BIGDATA/JCFW/JRCL/BD_O/REF/TR_APP_TYP';

ALTER TABLE JCFW.TR_APP_TYP ADD PARTITION (branch='GMCC');


