"TO_BASS_VIPCARD_RES_DAY","PK_CHK",1,"PK","TM_INTRVL_CD,VIPCARD_SERIAL_NO","branch,month,day",1.00,0.1,"N"
"TO_BASS_SERVE_TEAM_DAY","PK_CHK",1,"PK","TM_INTRVL_CD,ORDER_SEQ,AREA_CD,CUST_ID,TEAM_ID,CUST_MGR","branch,month,day",1.00,0.1,"N"

