INSERT INTO IMP_TABLE_LIST VALUES ('TW_PERS_LAB_OPENTODMP','TW_PERS_LAB_OPENTODMP');

insert into tablefile (xmlid, dbname, dataname, datacnname, state, cycletype, topiccode, extend_cfg, rightlevel, creater, curdutyer, eff_date, state_date, team_code, open_state, remark) values ('TW_PERS_LAB_OPENTODMP','DAY','TW_PERS_LAB_OPENTODMP','EDS_用户标签库DMP开放数据月表','NEW','day','LAYERH_HPERS_HPERS12','{"EXTERNAL":"y","LOCATION":"/tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_PERS_LAB_OPENTODMP","FILEFORMAT":"PARQUET","DELIMITER":"\001"}','其他','谢英俊','谢英俊', TIMESTAMP '0008-02-17 12:00:00', TIMESTAMP '0008-02-17 12:00:00','5875519a-8ee1-4eb7-825b-ef1135513f02','','汇总层-用户-移动个人用户');
insert into column_val (xmlid, col_xmlid, dataname, col_seq, colname, colcnname, datatype, length, precision_val, party_seq, isprimarykey, isnullable, remark, filed_type_child, sensitive_level, policyid) values ('TW_PERS_LAB_OPENTODMP','TW_PERS_LAB_OPENTODMP_2017071','TW_PERS_LAB_OPENTODMP','1','STAT_MO','统计月份','INT','','','','1','N','','C1-1','1','');
insert into column_val (xmlid, col_xmlid, dataname, col_seq, colname, colcnname, datatype, length, precision_val, party_seq, isprimarykey, isnullable, remark, filed_type_child, sensitive_level, policyid) values ('TW_PERS_LAB_OPENTODMP','TW_PERS_LAB_OPENTODMP_2017072','TW_PERS_LAB_OPENTODMP','2','USR_NBR','用户号码','STRING','','','','1','N','','A1-2','3','PID_all');
insert into column_val (xmlid, col_xmlid, dataname, col_seq, colname, colcnname, datatype, length, precision_val, party_seq, isprimarykey, isnullable, remark, filed_type_child, sensitive_level, policyid) values ('TW_PERS_LAB_OPENTODMP','TW_PERS_LAB_OPENTODMP_2017073','TW_PERS_LAB_OPENTODMP','3','LAB_CD','标签编码','STRING','','','','1','N','','C1-1','1','');
insert into column_val (xmlid, col_xmlid, dataname, col_seq, colname, colcnname, datatype, length, precision_val, party_seq, isprimarykey, isnullable, remark, filed_type_child, sensitive_level, policyid) values ('TW_PERS_LAB_OPENTODMP','TW_PERS_LAB_OPENTODMP_2017074','TW_PERS_LAB_OPENTODMP','4','CMCC_BRANCH_CD','移动分公司编码','STRING','','','','','N','','C1-1','1','');
insert into column_val (xmlid, col_xmlid, dataname, col_seq, colname, colcnname, datatype, length, precision_val, party_seq, isprimarykey, isnullable, remark, filed_type_child, sensitive_level, policyid) values ('TW_PERS_LAB_OPENTODMP','TW_PERS_LAB_OPENTODMP_2017075','TW_PERS_LAB_OPENTODMP','5','LAB_SRC_CD','标签来源编码','STRING','','','','','N','集市，该字段值为：1
数据挖掘，该字段值为：2
BI，该字段值为：4
收集类，该字段值为：5
','C1-1','1','');
insert into column_val (xmlid, col_xmlid, dataname, col_seq, colname, colcnname, datatype, length, precision_val, party_seq, isprimarykey, isnullable, remark, filed_type_child, sensitive_level, policyid) values ('TW_PERS_LAB_OPENTODMP','TW_PERS_LAB_OPENTODMP_2017076','TW_PERS_LAB_OPENTODMP','6','BRND_CD','品牌编码','SMALLINT','','','','','N','1、 全球通
2、 神州行
3、 动感地带','C1-1','1','');
insert into column_val (xmlid, col_xmlid, dataname, col_seq, colname, colcnname, datatype, length, precision_val, party_seq, isprimarykey, isnullable, remark, filed_type_child, sensitive_level, policyid) values ('TW_PERS_LAB_OPENTODMP','TW_PERS_LAB_OPENTODMP_2017077','TW_PERS_LAB_OPENTODMP','7','UPDT_TYP_CD','更新方式编码','STRING','','','','','N','','C1-1','1','');
insert into column_val (xmlid, col_xmlid, dataname, col_seq, colname, colcnname, datatype, length, precision_val, party_seq, isprimarykey, isnullable, remark, filed_type_child, sensitive_level, policyid) values ('TW_PERS_LAB_OPENTODMP','TW_PERS_LAB_OPENTODMP_2017078','TW_PERS_LAB_OPENTODMP','8','UPDT_DT','更新日期','INT','','','','','N','','C1-1','1','');
insert into column_val (xmlid, col_xmlid, dataname, col_seq, colname, colcnname, datatype, length, precision_val, party_seq, isprimarykey, isnullable, remark, filed_type_child, sensitive_level, policyid) values ('TW_PERS_LAB_OPENTODMP','TW_PERS_LAB_OPENTODMP_2017079','TW_PERS_LAB_OPENTODMP','9','RESERVED_FIELD_1','预留字段一','STRING','','','','','N','','C1-1','1','');
insert into column_val (xmlid, col_xmlid, dataname, col_seq, colname, colcnname, datatype, length, precision_val, party_seq, isprimarykey, isnullable, remark, filed_type_child, sensitive_level, policyid) values ('TW_PERS_LAB_OPENTODMP','TW_PERS_LAB_OPENTODMP_20170710','TW_PERS_LAB_OPENTODMP','10','RESERVED_FIELD_2','预留字段二','STRING','','','','','N','','C1-1','1','');
insert into column_val (xmlid, col_xmlid, dataname, col_seq, colname, colcnname, datatype, length, precision_val, party_seq, isprimarykey, isnullable, remark, filed_type_child, sensitive_level, policyid) values ('TW_PERS_LAB_OPENTODMP','TW_PERS_LAB_OPENTODMP_20170711','TW_PERS_LAB_OPENTODMP','11','RESERVED_FIELD_3','预留字段三','STRING','','','','','N','','C1-1','1','');
insert into column_val (xmlid, col_xmlid, dataname, col_seq, colname, colcnname, datatype, length, precision_val, party_seq, isprimarykey, isnullable, remark, filed_type_child, sensitive_level, policyid) values ('TW_PERS_LAB_OPENTODMP','TW_PERS_LAB_OPENTODMP_20170712','TW_PERS_LAB_OPENTODMP','12','RESERVED_FIELD_4','预留字段四','STRING','','','','','N','','C1-1','1','');
insert into column_val (xmlid, col_xmlid, dataname, col_seq, colname, colcnname, datatype, length, precision_val, party_seq, isprimarykey, isnullable, remark, filed_type_child, sensitive_level, policyid) values ('TW_PERS_LAB_OPENTODMP','TW_PERS_LAB_OPENTODMP_20170713','TW_PERS_LAB_OPENTODMP','13','MD5_IMEI','IMEI','STRING','','','','','N','','C2-1','2','PID_9star');
insert into column_val (xmlid, col_xmlid, dataname, col_seq, colname, colcnname, datatype, length, precision_val, party_seq, isprimarykey, isnullable, remark, filed_type_child, sensitive_level, policyid) values ('TW_PERS_LAB_OPENTODMP','TW_PERS_LAB_OPENTODMP_20161014','TW_PERS_LAB_OPENTODMP','14','branch','地市','STRING','','','1','','N','','C1-1','','');




