-------------------------------------------------------
-- 模型名：STAGE_融合计费集团业务标准GPRS清单(TS_E_FRHD_CORP_GPRS_CDR_D)
-- 表模式：STAGE
-- 分表方式：PUBLISHED
-- 数据库：GDDW
-- 创建日期：罗涛
-- 需求编号及说明：不分表
-------------------------------------------------------
CREATE TABLE STAGE.TS_E_FRHD_CORP_GPRS_CDR_D (
    EVENT_FORMAT_YTP_CD CHAR(2) NOT NULL ,
    ROLLBACK_ID CHAR(1),
    ROLLBACK_CNT SMALLINT,
    FILE_ID VARCHAR(10),
    SWITCH_NBR CHAR(4),
    FILE_TYP CHAR(2),
    USR_MOB_NBR VARCHAR(24),
    IMSI VARCHAR(32),
    IMEI VARCHAR(15),
    CALL_DT INTEGER,
    CALL_TIM CHAR(6),
    GUSR_NBR VARCHAR(24),
    SPECIAL_TYP_CD CHAR(2),
    DEBET_DT INTEGER,
    EVENT_TYP_CD VARCHAR(20),
    A_SWITCH_CD CHAR(2),
    CMCC_BRANCH_CD CHAR(4),
    A_BRND_CD SMALLINT,
    A_USR_TYP_CD CHAR(2),
    CALL_AREA_CD VARCHAR(8),
    B_NBR VARCHAR(24),
    BILL_TYP_CD CHAR(2),
    MOB_BILL_ACCT_CD VARCHAR(14),
    TOLL_BILL_ACCT_CD VARCHAR(14),
    INF_ACCT_CD VARCHAR(14),
    DISC_MOB_FEE DECIMAL(8,3),
    DISC_TOLL_FEE DECIMAL(8,3),
    DISC_INF_FEE DECIMAL(8,3),
    PAY_TYP_CD CHAR(1),
    DISC_BASS_PRDCT_CD1 VARCHAR(64),
    DEDUCTION1 BIGINT,
    DISC_BASS_PRDCT_CD2 VARCHAR(64),
    DEDUCTION2 BIGINT,
    RESERVE VARCHAR(36),
    CBE_TYP_CD CHAR(1),
    PERIOD_TYP_CD CHAR(1),
    USR_ID VARCHAR(20),
    A_PAY_TYP_CD CHAR(1),
    A_PAY_USR_NBR VARCHAR(24),
    A_PAY_SWITCH_CD CHAR(2),
    A_PAY_CMCC_BRANCH_CD CHAR(4),
    A_PAY_BRND_CD SMALLINT,
    A_PAY_USR_TYP_CD VARCHAR(2),
    A_PAY_EBOX_ID VARCHAR(32),
    A_PAY_DEDUCTED_CD CHAR(1),
    A_PAY_ACCT_AMT DECIMAL(12,3),
    A_PAY_ACCT_ID1 VARCHAR(18),
    A_PAY_ACCT_AMT1 DECIMAL(8,3),
    A_PAY_ACCT_ID2 VARCHAR(18),
    A_PAY_ACCT_AMT2 DECIMAL(8,3),
    A_PAY_ACCT_ID3 VARCHAR(18),
    A_PAY_ACCT_AMT3 DECIMAL(8,3),
    A_PAY_ACCT_ID4 VARCHAR(18),
    A_PAY_ACCT_AMT4 DECIMAL(8,3),
    B_PAY_TYP_CD CHAR(1),
    B_PAY_USR_NBR VARCHAR(24),
    B_PAY_SWITCH_CD CHAR(2),
    B_PAY_CMCC_BRANCH_CD CHAR(4),
    B_PAY_BRND_CD SMALLINT,
    B_PAY_USR_TYP_CD VARCHAR(2),
    B_PAY_EBOX_ID VARCHAR(32),
    B_PAY_DEDUCTED_CD CHAR(1),
    B_PAY_ACCT_AMT DECIMAL(12,3),
    B_PAY_ACCT_ID1 VARCHAR(18),
    B_PAY_ACCT_AMT1 DECIMAL(8,3),
    B_PAY_ACCT_ID2 VARCHAR(18),
    B_PAY_ACCT_AMT2 DECIMAL(8,3),
    B_PAY_ACCT_ID3 VARCHAR(18),
    B_PAY_ACCT_AMT3 DECIMAL(8,3),
    XD_TYP_CD CHAR(1),
    BUSI_CD VARCHAR(15),
    SRV_TYP_CD CHAR(2),
    SUBSRV_TYP_CD CHAR(2),
    RATE_TYP_CD CHAR(1),
    DISC_CD VARCHAR(32),
    VISITED_SWITCH_CD CHAR(2),
    ROAM_TYP_CD SMALLINT,
    B_OPER_CD CHAR(2),
    CALL_FREE_DUR INTEGER,
    DISC_FEE DECIMAL(8,3),
    RESERVE2 VARCHAR(30),
    B_SWITCH_CD CHAR(2),
    RG_CODE VARCHAR(10),
    DUR_VOL_TYP_CD CHAR(1),
    B_USR_TYP_CD CHAR(2),
    B_BRND_CD SMALLINT,
    TOP_TYP_CD CHAR(1),
    CHARGING_ID VARCHAR(10),
    REAL_USR_NBR VARCHAR(24),
    APN_NAM VARCHAR(64),
    GGSN VARCHAR(32),
    SGSN VARCHAR(32),
    CALL_DUR INTEGER,
    CDR_SEQ VARCHAR(64),
    SP_SUBBUSI_CD VARCHAR(30),
    GPRS_UP_FLUX BIGINT,
    GPRS_DOWN_FLUX BIGINT,
    FEE DECIMAL(12,3),
    NET_TYP_CD CHAR(1),
    VISIT_AREA_CD VARCHAR(9),
    INTNTL_OPER_CD VARCHAR(5),
    PARTIAL_CDR_ID CHAR(1),
    RESERVE3 VARCHAR(30),
    USR_PKG_TYP CHAR(1),
    HR_CD SMALLINT,
    CALL_CNT SMALLINT,
    INTRS_DEBET_DT INTEGER,
    INTRS_DEBET_TIM CHAR(6),
    TOLL_DUR INTEGER,
    CNCT_NBR VARCHAR(24),
    B_AREA_CD CHAR(8),
    TOLL_TYP_CD SMALLINT,
    ICP_STAT_CD CHAR(2),
    LOAD_ID INTEGER,
    CX_FILE_IND CHAR(1),
    A_LOCAL_CD CHAR(4),
    A_CELL_CD VARCHAR(8),
    GPRS_UP_KB_FLUX BIGINT,
    GPRS_DOWN_KB_FLUX BIGINT
)
 PARTITIONING KEY (USR_MOB_NBR);
COMMENT ON TABLE STAGE.TS_E_FRHD_CORP_GPRS_CDR_D IS 'STAGE_融合计费集团业务标准GPRS清单';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.EVENT_FORMAT_YTP_CD IS '标准事件格式类型';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.ROLLBACK_ID IS '冲销标志';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.ROLLBACK_CNT IS '冲销计数';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.FILE_ID IS '文件ID';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.SWITCH_NBR IS '交换机代码';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.FILE_TYP IS '文件类型';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.USR_MOB_NBR IS '用户号码';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.IMSI IS 'IMSI';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.IMEI IS 'IMEI';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.CALL_DT IS '日期';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.CALL_TIM IS '时间';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.GUSR_NBR IS '集团号码';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.SPECIAL_TYP_CD IS '特殊业务类型';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.DEBET_DT IS '批价处理日期';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.EVENT_TYP_CD IS '计费事件类型';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.A_SWITCH_CD IS '归属局';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.CMCC_BRANCH_CD IS '移动分公司编码';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.A_BRND_CD IS '计费方品牌编码';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.A_USR_TYP_CD IS '计费方用户类型';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.CALL_AREA_CD IS '呼叫发生地';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.B_NBR IS '对方号码';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.BILL_TYP_CD IS '帐单类型编码';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.MOB_BILL_ACCT_CD IS '移动费帐单科目编码';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.TOLL_BILL_ACCT_CD IS '长途费帐单科目编码';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.INF_ACCT_CD IS '信息费帐单科目编码';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.DISC_MOB_FEE IS '移动话费';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.DISC_TOLL_FEE IS '长途话费';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.DISC_INF_FEE IS '信息费';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.PAY_TYP_CD IS '付费方式';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.DISC_BASS_PRDCT_CD1 IS '优惠的产品ID1';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.DEDUCTION1 IS '扣减量1';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.DISC_BASS_PRDCT_CD2 IS '优惠的产品ID2';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.DEDUCTION2 IS '扣减量2';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.RESERVE IS '保留';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.CBE_TYP_CD IS '在线离线标识';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.PERIOD_TYP_CD IS '动态月标识';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.USR_ID IS '用户编码';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.A_PAY_TYP_CD IS '付费A的付费类型';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.A_PAY_USR_NBR IS '付费A号码';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.A_PAY_SWITCH_CD IS '付费A号码归属局';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.A_PAY_CMCC_BRANCH_CD IS '付费A号码移动分公司编码';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.A_PAY_BRND_CD IS '付费A号码品牌编码';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.A_PAY_USR_TYP_CD IS '付费A号码用户类型';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.A_PAY_EBOX_ID IS '付费A号码帐户编码';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.A_PAY_DEDUCTED_CD IS '付费A账户已扣标识';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.A_PAY_ACCT_AMT IS '付费A账户可用余额';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.A_PAY_ACCT_ID1 IS '付费A账本余额唯一标识1';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.A_PAY_ACCT_AMT1 IS '付费A账本余额唯一标识1金额';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.A_PAY_ACCT_ID2 IS '付费A账本余额唯一标识2';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.A_PAY_ACCT_AMT2 IS '付费A账本余额唯一标识2金额';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.A_PAY_ACCT_ID3 IS '付费A账本余额唯一标识3';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.A_PAY_ACCT_AMT3 IS '付费A账本余额唯一标识3金额';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.A_PAY_ACCT_ID4 IS '付费A账本余额唯一标识4';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.A_PAY_ACCT_AMT4 IS '付费A账本余额唯一标识4金额';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.B_PAY_TYP_CD IS '付费B的付费类型';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.B_PAY_USR_NBR IS '付费B号码';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.B_PAY_SWITCH_CD IS '付费B号码归属局';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.B_PAY_CMCC_BRANCH_CD IS '付费B号码移动分公司编码';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.B_PAY_BRND_CD IS '付费B号码品牌编码';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.B_PAY_USR_TYP_CD IS '付费B号码用户类型';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.B_PAY_EBOX_ID IS '付费B号码帐户编码';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.B_PAY_DEDUCTED_CD IS '付费B账户已扣标识';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.B_PAY_ACCT_AMT IS '付费B账户可用余额';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.B_PAY_ACCT_ID1 IS '付费B账本余额唯一标识1';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.B_PAY_ACCT_AMT1 IS '付费B账本余额唯一标识1金额';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.B_PAY_ACCT_ID2 IS '付费B账本余额唯一标识2';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.B_PAY_ACCT_AMT2 IS '付费B账本余额唯一标识2金额';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.B_PAY_ACCT_ID3 IS '付费B账本余额唯一标识3';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.B_PAY_ACCT_AMT3 IS '付费B账本余额唯一标识3金额';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.XD_TYP_CD IS '详单分类';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.BUSI_CD IS '业务编码';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.SRV_TYP_CD IS '通信业务类型编码';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.SUBSRV_TYP_CD IS '通信子业务类型编码';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.RATE_TYP_CD IS '计费类型编码';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.DISC_CD IS '优惠代码';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.VISITED_SWITCH_CD IS '被访局';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.ROAM_TYP_CD IS '漫游类型编码';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.B_OPER_CD IS '对方运营商编码';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.CALL_FREE_DUR IS '优惠分钟数';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.DISC_FEE IS '帐单优惠减免金额';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.RESERVE2 IS '保留2';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.B_SWITCH_CD IS '对方用户归属局';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.RG_CODE IS 'Rg代码';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.DUR_VOL_TYP_CD IS '按时长流量计费标识';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.B_USR_TYP_CD IS '对方用户类型';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.B_BRND_CD IS '对方品牌编码';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.TOP_TYP_CD IS '费用封顶标志';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.CHARGING_ID IS '会话Id';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.REAL_USR_NBR IS '真实号码';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.APN_NAM IS 'APN名称';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.GGSN IS 'GGSN地址';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.SGSN IS 'SGSN地址';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.CALL_DUR IS '时长';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.CDR_SEQ IS '序列号';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.SP_SUBBUSI_CD IS '业务代码';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.GPRS_UP_FLUX IS '上行流量';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.GPRS_DOWN_FLUX IS '下行流量';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.FEE IS '统一批价费用';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.NET_TYP_CD IS '网络类型编码';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.VISIT_AREA_CD IS '到访地费率区号';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.INTNTL_OPER_CD IS '国际运营商标识';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.PARTIAL_CDR_ID IS '分话单标识';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.RESERVE3 IS '保留3';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.USR_PKG_TYP IS '用户套餐分类';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.HR_CD IS '时段编码';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.CALL_CNT IS '次数';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.INTRS_DEBET_DT IS '接口批价处理日期';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.INTRS_DEBET_TIM IS '接口批价处理时间';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.TOLL_DUR IS '长途计费时长';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.CNCT_NBR IS '接入号码';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.B_AREA_CD IS '对方归属地';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.TOLL_TYP_CD IS '长途类型编码';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.ICP_STAT_CD IS '数据业务统计类型编码';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.LOAD_ID IS '数据加载编号';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.CX_FILE_IND IS '冲销文件标志';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.A_LOCAL_CD IS '计费方位置代码';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.A_CELL_CD IS '计费方小区代码';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.GPRS_UP_KB_FLUX IS '上行流量(KB)';
COMMENT ON COLUMN STAGE.TS_E_FRHD_CORP_GPRS_CDR_D.GPRS_DOWN_KB_FLUX IS '下行流量(KB)';



