-------------------------------------------------------
-- 模型名：ODS_CRM省节点用户定购产品日增量表(TO_SJDCRM_BASS_CUST_ORDR_DAY)
-- 表模式：ODS
-- 分表方式：按月分表
-- 数据库：GDDW
-- 创建日期：2012/9/11
-- 需求编号及说明：
-------------------------------------------------------
CREATE TABLE ODS.TO_SJDCRM_BASS_CUST_ORDR_DAY (
    ORDER_SEQ CHAR(20) NOT NULL ,
    SUBSPROD_ID VARCHAR(20) NOT NULL ,
    USR_ID CHAR(20),
    AREA_CD CHAR(8),
    BASS_PRDCT_CD VARCHAR(32),
    PKG_PRDCT_CD VARCHAR(32),
    REG_TYP VARCHAR(32),
    POST_CD INTEGER,
    GRP_SUB_ID CHAR(14),
    VERSION VARCHAR(32),
    APPLY_SEQ VARCHAR(32),
    START_DT INTEGER,
    START_TIM CHAR(6),
    CANC_SEQ VARCHAR(32),
    END_DT INTEGER,
    END_TIM CHAR(6),
    REF_GRP_SUB_ID CHAR(14),
    TYP_CD SMALLINT,
    DATA_DT INTEGER
)
 PARTITIONING KEY (ORDER_SEQ);
COMMENT ON TABLE ODS.TO_SJDCRM_BASS_CUST_ORDR_DAY IS 'ODS_CRM省节点用户定购产品日增量表';
COMMENT ON COLUMN ODS.TO_SJDCRM_BASS_CUST_ORDR_DAY.ORDER_SEQ IS '订单编码';
COMMENT ON COLUMN ODS.TO_SJDCRM_BASS_CUST_ORDR_DAY.SUBSPROD_ID IS '用户产品实例编号';
COMMENT ON COLUMN ODS.TO_SJDCRM_BASS_CUST_ORDR_DAY.USR_ID IS '用户编码';
COMMENT ON COLUMN ODS.TO_SJDCRM_BASS_CUST_ORDR_DAY.AREA_CD IS '地区编码';
COMMENT ON COLUMN ODS.TO_SJDCRM_BASS_CUST_ORDR_DAY.BASS_PRDCT_CD IS 'BASS产品编码';
COMMENT ON COLUMN ODS.TO_SJDCRM_BASS_CUST_ORDR_DAY.PKG_PRDCT_CD IS '产品包编码';
COMMENT ON COLUMN ODS.TO_SJDCRM_BASS_CUST_ORDR_DAY.REG_TYP IS '注册类型';
COMMENT ON COLUMN ODS.TO_SJDCRM_BASS_CUST_ORDR_DAY.POST_CD IS '顺延产品编码';
COMMENT ON COLUMN ODS.TO_SJDCRM_BASS_CUST_ORDR_DAY.GRP_SUB_ID IS '用户群编码';
COMMENT ON COLUMN ODS.TO_SJDCRM_BASS_CUST_ORDR_DAY.VERSION IS '产品版本';
COMMENT ON COLUMN ODS.TO_SJDCRM_BASS_CUST_ORDR_DAY.APPLY_SEQ IS '申请流水号';
COMMENT ON COLUMN ODS.TO_SJDCRM_BASS_CUST_ORDR_DAY.START_DT IS '开始日期';
COMMENT ON COLUMN ODS.TO_SJDCRM_BASS_CUST_ORDR_DAY.START_TIM IS '开始时间';
COMMENT ON COLUMN ODS.TO_SJDCRM_BASS_CUST_ORDR_DAY.CANC_SEQ IS '取消流水号';
COMMENT ON COLUMN ODS.TO_SJDCRM_BASS_CUST_ORDR_DAY.END_DT IS '结束日期';
COMMENT ON COLUMN ODS.TO_SJDCRM_BASS_CUST_ORDR_DAY.END_TIM IS '结束时间';
COMMENT ON COLUMN ODS.TO_SJDCRM_BASS_CUST_ORDR_DAY.REF_GRP_SUB_ID IS '参考用户群编号';
COMMENT ON COLUMN ODS.TO_SJDCRM_BASS_CUST_ORDR_DAY.TYP_CD IS '类型编码';
COMMENT ON COLUMN ODS.TO_SJDCRM_BASS_CUST_ORDR_DAY.DATA_DT IS '数据日期';

ALTER TABLE ODS.TO_SJDCRM_BASS_CUST_ORDR_DAY ADD PRIMARY KEY (ORDER_SEQ,SUBSPROD_ID);


