-------------------------------------------------------
-- 模型名：REF_M_GPRS产品信息维表(TR_NB_GPRS_PRDCT)
-- 表模式：REF
-- 分表方式：不分表
-- 数据库：GDDW
-- 创建日期：2013/9/16
-- 需求编号及说明：
-------------------------------------------------------
CREATE TABLE REF.TR_NB_GPRS_PRDCT (
    BASS_PRDCT_CD VARCHAR(32) NOT NULL ,
    BASS_PRDCT_NAM VARCHAR(128),
    PKG_KIND_CD SMALLINT,
    GPRS_PKG_TYP_CD SMALLINT,
    GPRS_PKG_TYP_DTL_CD INTEGER,
    GPRS_PKG_TM_TYP_CD SMALLINT,
    GPRS_PKG_TYP_NAM VARCHAR(128),
    GPRS_PKG_TYP_DTL_NAM VARCHAR(128),
    GPRS_PKG_COMMON_FLUX BIGINT,
    GPRS_PKG_TD_FLUX BIGINT,
    GPRS_PKG_TDLTE_FLUX BIGINT,
    GPRS_PKG_IDLE_FLUX BIGINT,
    GPRS_PKG_FEE DECIMAL(12,2),
    PRDCT_FEE DECIMAL(16,2),
    FLUX_MAIN_PKG_IND SMALLINT,
    PKG_SUPL_TYP_CD SMALLINT,
    PKG_SUPL_TYP_NAM VARCHAR(128),
    V_TYP_CD_1 SMALLINT,
    V_TYP_NAM_1 VARCHAR(64),
    MIX_PKG_IND CHAR(1),
    A4G_PKG_IND CHAR(1),
    A4G_MIX_PKG_IND CHAR(1),
    A4G_FLUX_PKG_IND CHAR(1),
    C_FLUX_PKG_IND CHAR(1),
    V_TYP_CD_2 SMALLINT,
    V_TYP_NAM_2 VARCHAR(64),
    LC_FLUX_PKG_IND CHAR(1),
    PM_PKG_IND CHAR(1),
    SWYH_PRDCT_CD VARCHAR(32),
    CORP_PKG_IND CHAR(1),
    YEAR_PKG_IND CHAR(1),
    YEAR_PKG_NAM VARCHAR(64),
    WHPKG_CD CHAR(1),
    V_TYP_CD_3 SMALLINT,
    V_TYP_NAM_3 VARCHAR(64),
    GIF_PRDCT_CD VARCHAR(32),
    GIF_PRDCT_NAM VARCHAR(128),
    GIF2_PRDCT_CD VARCHAR(32),
    V_TYP_CD_4 SMALLINT,
    V_TYP_NAM_4 VARCHAR(64),
    SNACK_PKG_IND CHAR(1),
    EQUITY_PKG_IND CHAR(1),
    A4G_TK_PKG_IND CHAR(1),
    CHNL_MNTR_FLUX_PKG_IND CHAR(1),
    MON_FLUX_PKG_IND CHAR(1),
    TIM_LIMIT_PKG_IND CHAR(1),
    SR201708210015001_IND CHAR(1)
)
 PARTITIONING KEY (BASS_PRDCT_CD);
COMMENT ON TABLE REF.TR_NB_GPRS_PRDCT IS 'REF_M_GPRS产品信息维表';
COMMENT ON COLUMN REF.TR_NB_GPRS_PRDCT.BASS_PRDCT_CD IS '产品编码';
COMMENT ON COLUMN REF.TR_NB_GPRS_PRDCT.BASS_PRDCT_NAM IS '产品名称';
COMMENT ON COLUMN REF.TR_NB_GPRS_PRDCT.PKG_KIND_CD IS '流量套餐分类编码';
COMMENT ON COLUMN REF.TR_NB_GPRS_PRDCT.GPRS_PKG_TYP_CD IS 'GPRS套餐分类编码';
COMMENT ON COLUMN REF.TR_NB_GPRS_PRDCT.GPRS_PKG_TYP_DTL_CD IS 'GPRS套餐分类明细编码';
COMMENT ON COLUMN REF.TR_NB_GPRS_PRDCT.GPRS_PKG_TM_TYP_CD IS 'GPRS套餐时间段编码';
COMMENT ON COLUMN REF.TR_NB_GPRS_PRDCT.GPRS_PKG_TYP_NAM IS 'GPRS套餐分类名称';
COMMENT ON COLUMN REF.TR_NB_GPRS_PRDCT.GPRS_PKG_TYP_DTL_NAM IS 'GPRS套餐分类明细名称';
COMMENT ON COLUMN REF.TR_NB_GPRS_PRDCT.GPRS_PKG_COMMON_FLUX IS 'GPRS套餐包含通用流量';
COMMENT ON COLUMN REF.TR_NB_GPRS_PRDCT.GPRS_PKG_TD_FLUX IS 'GPRS套餐包含TD流量';
COMMENT ON COLUMN REF.TR_NB_GPRS_PRDCT.GPRS_PKG_TDLTE_FLUX IS 'GPRS套餐包含TDLTE流量';
COMMENT ON COLUMN REF.TR_NB_GPRS_PRDCT.GPRS_PKG_IDLE_FLUX IS 'GPRS套餐包含闲时流量';
COMMENT ON COLUMN REF.TR_NB_GPRS_PRDCT.GPRS_PKG_FEE IS 'GPRS套餐费用';
COMMENT ON COLUMN REF.TR_NB_GPRS_PRDCT.PRDCT_FEE IS '产品费用';
COMMENT ON COLUMN REF.TR_NB_GPRS_PRDCT.FLUX_MAIN_PKG_IND IS '流量主套餐标识';
COMMENT ON COLUMN REF.TR_NB_GPRS_PRDCT.PKG_SUPL_TYP_CD IS '流量套餐补充类别编码';
COMMENT ON COLUMN REF.TR_NB_GPRS_PRDCT.PKG_SUPL_TYP_NAM IS '流量套餐补充类别名称';
COMMENT ON COLUMN REF.TR_NB_GPRS_PRDCT.V_TYP_CD_1 IS '展现分类1';
COMMENT ON COLUMN REF.TR_NB_GPRS_PRDCT.V_TYP_NAM_1 IS '展现分类名称1';
COMMENT ON COLUMN REF.TR_NB_GPRS_PRDCT.MIX_PKG_IND IS '省级融合套餐标识';
COMMENT ON COLUMN REF.TR_NB_GPRS_PRDCT.A4G_PKG_IND IS '4G套餐标识';
COMMENT ON COLUMN REF.TR_NB_GPRS_PRDCT.A4G_MIX_PKG_IND IS '4G融合套餐标识';
COMMENT ON COLUMN REF.TR_NB_GPRS_PRDCT.A4G_FLUX_PKG_IND IS '含4G流量套餐标识';
COMMENT ON COLUMN REF.TR_NB_GPRS_PRDCT.C_FLUX_PKG_IND IS '省级纯流量套餐标识';
COMMENT ON COLUMN REF.TR_NB_GPRS_PRDCT.V_TYP_CD_2 IS '展现分类2';
COMMENT ON COLUMN REF.TR_NB_GPRS_PRDCT.V_TYP_NAM_2 IS '展现分类名称2';
COMMENT ON COLUMN REF.TR_NB_GPRS_PRDCT.LC_FLUX_PKG_IND IS '领导短信纯流量套餐标识';
COMMENT ON COLUMN REF.TR_NB_GPRS_PRDCT.PM_PKG_IND IS '精确营销套餐标识';
COMMENT ON COLUMN REF.TR_NB_GPRS_PRDCT.SWYH_PRDCT_CD IS '加量不加价产品编码';
COMMENT ON COLUMN REF.TR_NB_GPRS_PRDCT.CORP_PKG_IND IS '领导短信集团统一套餐标识';
COMMENT ON COLUMN REF.TR_NB_GPRS_PRDCT.YEAR_PKG_IND IS '领导短信年包标识';
COMMENT ON COLUMN REF.TR_NB_GPRS_PRDCT.YEAR_PKG_NAM IS '领导短信年包名称';
COMMENT ON COLUMN REF.TR_NB_GPRS_PRDCT.WHPKG_CD IS '全网统一套餐标识';
COMMENT ON COLUMN REF.TR_NB_GPRS_PRDCT.V_TYP_CD_3 IS '展现分类3';
COMMENT ON COLUMN REF.TR_NB_GPRS_PRDCT.V_TYP_NAM_3 IS '展现分类名称3';
COMMENT ON COLUMN REF.TR_NB_GPRS_PRDCT.GIF_PRDCT_CD IS '一经编码';
COMMENT ON COLUMN REF.TR_NB_GPRS_PRDCT.GIF_PRDCT_NAM IS '一经套餐名称';
COMMENT ON COLUMN REF.TR_NB_GPRS_PRDCT.GIF2_PRDCT_CD IS '一经编码2';
COMMENT ON COLUMN REF.TR_NB_GPRS_PRDCT.V_TYP_CD_4 IS '展现分类4';
COMMENT ON COLUMN REF.TR_NB_GPRS_PRDCT.V_TYP_NAM_4 IS '展现分类名称4';
COMMENT ON COLUMN REF.TR_NB_GPRS_PRDCT.SNACK_PKG_IND IS '领导短信快餐包标识';
COMMENT ON COLUMN REF.TR_NB_GPRS_PRDCT.EQUITY_PKG_IND IS '领导短信权益包标识';
COMMENT ON COLUMN REF.TR_NB_GPRS_PRDCT.A4G_TK_PKG_IND IS '是否4G套卡';
COMMENT ON COLUMN REF.TR_NB_GPRS_PRDCT.CHNL_MNTR_FLUX_PKG_IND IS '是否渠道监控流量套餐';
COMMENT ON COLUMN REF.TR_NB_GPRS_PRDCT.MON_FLUX_PKG_IND IS '是否流量月包';
COMMENT ON COLUMN REF.TR_NB_GPRS_PRDCT.TIM_LIMIT_PKG_IND IS '是否限时流量包';
COMMENT ON COLUMN REF.TR_NB_GPRS_PRDCT.SR201708210015001_IND IS '是否SR201708210015001产品';

ALTER TABLE REF.TR_NB_GPRS_PRDCT ADD PRIMARY KEY (BASS_PRDCT_CD);


