 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -rm /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_TXT/branch=GMCC/month=201704/day=20170403//*
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -mv /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=GZ/month=201704/day=20170403/ /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_TXT/branch=GMCC/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day use jcfw;INSERT INTO JCFW.TW_CDR_USR_GPRS_BUSI_D_PAQ PARTITION(branch='GZ',month=201704,day=20170403) SELECT     DEBET_DT,    CALL_DT,    USR_NBR,    EVENT_FORMAT_YTP_CD,    SRV_TYP_CD,    SUBSRV_TYP_CD,    CX_FILE_IND,    BILL_TYP_CD,    CALL_AREA_CD,  DISC_BASS_PRDCT_CD1,    DISC_BASS_PRDCT_CD2,    XD_TYP_CD,    RESERVE,    RESERVE2,    RESERVE3,    DUR_VOL_TYP_CD,    ROAM_TYP_CD,    EVENT_TYP_CD,    SPECIAL_TYP_CD,    FILE_TYP,    IMEI,    NET_TYP_CD,    A_USR_TYP_CD,    CMCC_BRANCH_CD,    BRND_CD,    MOB_FEE,    TOLL_FEE,    INF_FEE,    CALL_DUR,    DEBET_MOB_DUR,    CALL_CNT,    UP_CALL_FLUX,    DOWN_CALL_FLUX,    INTR_UP_FLUX,    INTR_DOWN_FLUX,    CALL_FREE_DUR,DEDUCTION1,DEDUCTION2 FROM JCFW.TW_CDR_USR_GPRS_BUSI_D_TXT;"
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -rm /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=GZ/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -mv  /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_PAQ/branch=GZ/month=201704/day=20170403/* /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=GZ/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -rm /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_TXT/branch=GMCC/month=201704/day=20170403//*
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -mv /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=SZ/month=201704/day=20170403/ /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_TXT/branch=GMCC/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day use jcfw;INSERT INTO JCFW.TW_CDR_USR_GPRS_BUSI_D_PAQ PARTITION(branch='SZ',month=201704,day=20170403) SELECT     DEBET_DT,    CALL_DT,    USR_NBR,    EVENT_FORMAT_YTP_CD,    SRV_TYP_CD,    SUBSRV_TYP_CD,    CX_FILE_IND,    BILL_TYP_CD,    CALL_AREA_CD,  DISC_BASS_PRDCT_CD1,    DISC_BASS_PRDCT_CD2,    XD_TYP_CD,    RESERVE,    RESERVE2,    RESERVE3,    DUR_VOL_TYP_CD,    ROAM_TYP_CD,    EVENT_TYP_CD,    SPECIAL_TYP_CD,    FILE_TYP,    IMEI,    NET_TYP_CD,    A_USR_TYP_CD,    CMCC_BRANCH_CD,    BRND_CD,    MOB_FEE,    TOLL_FEE,    INF_FEE,    CALL_DUR,    DEBET_MOB_DUR,    CALL_CNT,    UP_CALL_FLUX,    DOWN_CALL_FLUX,    INTR_UP_FLUX,    INTR_DOWN_FLUX,    CALL_FREE_DUR,DEDUCTION1,DEDUCTION2 FROM JCFW.TW_CDR_USR_GPRS_BUSI_D_TXT;"
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -rm /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=SZ/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -mv  /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_PAQ/branch=SZ/month=201704/day=20170403/* /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=SZ/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -rm /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_TXT/branch=GMCC/month=201704/day=20170403//*
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -mv /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=DG/month=201704/day=20170403/ /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_TXT/branch=GMCC/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day use jcfw;INSERT INTO JCFW.TW_CDR_USR_GPRS_BUSI_D_PAQ PARTITION(branch='DG',month=201704,day=20170403) SELECT     DEBET_DT,    CALL_DT,    USR_NBR,    EVENT_FORMAT_YTP_CD,    SRV_TYP_CD,    SUBSRV_TYP_CD,    CX_FILE_IND,    BILL_TYP_CD,    CALL_AREA_CD,  DISC_BASS_PRDCT_CD1,    DISC_BASS_PRDCT_CD2,    XD_TYP_CD,    RESERVE,    RESERVE2,    RESERVE3,    DUR_VOL_TYP_CD,    ROAM_TYP_CD,    EVENT_TYP_CD,    SPECIAL_TYP_CD,    FILE_TYP,    IMEI,    NET_TYP_CD,    A_USR_TYP_CD,    CMCC_BRANCH_CD,    BRND_CD,    MOB_FEE,    TOLL_FEE,    INF_FEE,    CALL_DUR,    DEBET_MOB_DUR,    CALL_CNT,    UP_CALL_FLUX,    DOWN_CALL_FLUX,    INTR_UP_FLUX,    INTR_DOWN_FLUX,    CALL_FREE_DUR,DEDUCTION1,DEDUCTION2 FROM JCFW.TW_CDR_USR_GPRS_BUSI_D_TXT;"
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -rm /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=DG/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -mv  /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_PAQ/branch=DG/month=201704/day=20170403/* /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=DG/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -rm /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_TXT/branch=GMCC/month=201704/day=20170403//*
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -mv /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=FS/month=201704/day=20170403/ /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_TXT/branch=GMCC/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day use jcfw;INSERT INTO JCFW.TW_CDR_USR_GPRS_BUSI_D_PAQ PARTITION(branch='FS',month=201704,day=20170403) SELECT     DEBET_DT,    CALL_DT,    USR_NBR,    EVENT_FORMAT_YTP_CD,    SRV_TYP_CD,    SUBSRV_TYP_CD,    CX_FILE_IND,    BILL_TYP_CD,    CALL_AREA_CD,  DISC_BASS_PRDCT_CD1,    DISC_BASS_PRDCT_CD2,    XD_TYP_CD,    RESERVE,    RESERVE2,    RESERVE3,    DUR_VOL_TYP_CD,    ROAM_TYP_CD,    EVENT_TYP_CD,    SPECIAL_TYP_CD,    FILE_TYP,    IMEI,    NET_TYP_CD,    A_USR_TYP_CD,    CMCC_BRANCH_CD,    BRND_CD,    MOB_FEE,    TOLL_FEE,    INF_FEE,    CALL_DUR,    DEBET_MOB_DUR,    CALL_CNT,    UP_CALL_FLUX,    DOWN_CALL_FLUX,    INTR_UP_FLUX,    INTR_DOWN_FLUX,    CALL_FREE_DUR,DEDUCTION1,DEDUCTION2 FROM JCFW.TW_CDR_USR_GPRS_BUSI_D_TXT;"
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -rm /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=FS/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -mv  /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_PAQ/branch=FS/month=201704/day=20170403/* /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=FS/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -rm /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_TXT/branch=GMCC/month=201704/day=20170403//*
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -mv /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=ST/month=201704/day=20170403/ /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_TXT/branch=GMCC/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day use jcfw;INSERT INTO JCFW.TW_CDR_USR_GPRS_BUSI_D_PAQ PARTITION(branch='ST',month=201704,day=20170403) SELECT     DEBET_DT,    CALL_DT,    USR_NBR,    EVENT_FORMAT_YTP_CD,    SRV_TYP_CD,    SUBSRV_TYP_CD,    CX_FILE_IND,    BILL_TYP_CD,    CALL_AREA_CD,  DISC_BASS_PRDCT_CD1,    DISC_BASS_PRDCT_CD2,    XD_TYP_CD,    RESERVE,    RESERVE2,    RESERVE3,    DUR_VOL_TYP_CD,    ROAM_TYP_CD,    EVENT_TYP_CD,    SPECIAL_TYP_CD,    FILE_TYP,    IMEI,    NET_TYP_CD,    A_USR_TYP_CD,    CMCC_BRANCH_CD,    BRND_CD,    MOB_FEE,    TOLL_FEE,    INF_FEE,    CALL_DUR,    DEBET_MOB_DUR,    CALL_CNT,    UP_CALL_FLUX,    DOWN_CALL_FLUX,    INTR_UP_FLUX,    INTR_DOWN_FLUX,    CALL_FREE_DUR,DEDUCTION1,DEDUCTION2 FROM JCFW.TW_CDR_USR_GPRS_BUSI_D_TXT;"
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -rm /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=ST/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -mv  /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_PAQ/branch=ST/month=201704/day=20170403/* /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=ST/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -rm /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_TXT/branch=GMCC/month=201704/day=20170403//*
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -mv /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=ZH/month=201704/day=20170403/ /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_TXT/branch=GMCC/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day use jcfw;INSERT INTO JCFW.TW_CDR_USR_GPRS_BUSI_D_PAQ PARTITION(branch='ZH',month=201704,day=20170403) SELECT     DEBET_DT,    CALL_DT,    USR_NBR,    EVENT_FORMAT_YTP_CD,    SRV_TYP_CD,    SUBSRV_TYP_CD,    CX_FILE_IND,    BILL_TYP_CD,    CALL_AREA_CD,  DISC_BASS_PRDCT_CD1,    DISC_BASS_PRDCT_CD2,    XD_TYP_CD,    RESERVE,    RESERVE2,    RESERVE3,    DUR_VOL_TYP_CD,    ROAM_TYP_CD,    EVENT_TYP_CD,    SPECIAL_TYP_CD,    FILE_TYP,    IMEI,    NET_TYP_CD,    A_USR_TYP_CD,    CMCC_BRANCH_CD,    BRND_CD,    MOB_FEE,    TOLL_FEE,    INF_FEE,    CALL_DUR,    DEBET_MOB_DUR,    CALL_CNT,    UP_CALL_FLUX,    DOWN_CALL_FLUX,    INTR_UP_FLUX,    INTR_DOWN_FLUX,    CALL_FREE_DUR,DEDUCTION1,DEDUCTION2 FROM JCFW.TW_CDR_USR_GPRS_BUSI_D_TXT;"
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -rm /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=ZH/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -mv  /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_PAQ/branch=ZH/month=201704/day=20170403/* /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=ZH/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -rm /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_TXT/branch=GMCC/month=201704/day=20170403//*
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -mv /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=HZ/month=201704/day=20170403/ /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_TXT/branch=GMCC/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day use jcfw;INSERT INTO JCFW.TW_CDR_USR_GPRS_BUSI_D_PAQ PARTITION(branch='HZ',month=201704,day=20170403) SELECT     DEBET_DT,    CALL_DT,    USR_NBR,    EVENT_FORMAT_YTP_CD,    SRV_TYP_CD,    SUBSRV_TYP_CD,    CX_FILE_IND,    BILL_TYP_CD,    CALL_AREA_CD,  DISC_BASS_PRDCT_CD1,    DISC_BASS_PRDCT_CD2,    XD_TYP_CD,    RESERVE,    RESERVE2,    RESERVE3,    DUR_VOL_TYP_CD,    ROAM_TYP_CD,    EVENT_TYP_CD,    SPECIAL_TYP_CD,    FILE_TYP,    IMEI,    NET_TYP_CD,    A_USR_TYP_CD,    CMCC_BRANCH_CD,    BRND_CD,    MOB_FEE,    TOLL_FEE,    INF_FEE,    CALL_DUR,    DEBET_MOB_DUR,    CALL_CNT,    UP_CALL_FLUX,    DOWN_CALL_FLUX,    INTR_UP_FLUX,    INTR_DOWN_FLUX,    CALL_FREE_DUR,DEDUCTION1,DEDUCTION2 FROM JCFW.TW_CDR_USR_GPRS_BUSI_D_TXT;"
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -rm /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=HZ/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -mv  /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_PAQ/branch=HZ/month=201704/day=20170403/* /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=HZ/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -rm /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_TXT/branch=GMCC/month=201704/day=20170403//*
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -mv /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=ZS/month=201704/day=20170403/ /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_TXT/branch=GMCC/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day use jcfw;INSERT INTO JCFW.TW_CDR_USR_GPRS_BUSI_D_PAQ PARTITION(branch='ZS',month=201704,day=20170403) SELECT     DEBET_DT,    CALL_DT,    USR_NBR,    EVENT_FORMAT_YTP_CD,    SRV_TYP_CD,    SUBSRV_TYP_CD,    CX_FILE_IND,    BILL_TYP_CD,    CALL_AREA_CD,  DISC_BASS_PRDCT_CD1,    DISC_BASS_PRDCT_CD2,    XD_TYP_CD,    RESERVE,    RESERVE2,    RESERVE3,    DUR_VOL_TYP_CD,    ROAM_TYP_CD,    EVENT_TYP_CD,    SPECIAL_TYP_CD,    FILE_TYP,    IMEI,    NET_TYP_CD,    A_USR_TYP_CD,    CMCC_BRANCH_CD,    BRND_CD,    MOB_FEE,    TOLL_FEE,    INF_FEE,    CALL_DUR,    DEBET_MOB_DUR,    CALL_CNT,    UP_CALL_FLUX,    DOWN_CALL_FLUX,    INTR_UP_FLUX,    INTR_DOWN_FLUX,    CALL_FREE_DUR,DEDUCTION1,DEDUCTION2 FROM JCFW.TW_CDR_USR_GPRS_BUSI_D_TXT;"
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -rm /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=ZS/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -mv  /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_PAQ/branch=ZS/month=201704/day=20170403/* /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=ZS/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -rm /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_TXT/branch=GMCC/month=201704/day=20170403//*
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -mv /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=JM/month=201704/day=20170403/ /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_TXT/branch=GMCC/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day use jcfw;INSERT INTO JCFW.TW_CDR_USR_GPRS_BUSI_D_PAQ PARTITION(branch='JM',month=201704,day=20170403) SELECT     DEBET_DT,    CALL_DT,    USR_NBR,    EVENT_FORMAT_YTP_CD,    SRV_TYP_CD,    SUBSRV_TYP_CD,    CX_FILE_IND,    BILL_TYP_CD,    CALL_AREA_CD,  DISC_BASS_PRDCT_CD1,    DISC_BASS_PRDCT_CD2,    XD_TYP_CD,    RESERVE,    RESERVE2,    RESERVE3,    DUR_VOL_TYP_CD,    ROAM_TYP_CD,    EVENT_TYP_CD,    SPECIAL_TYP_CD,    FILE_TYP,    IMEI,    NET_TYP_CD,    A_USR_TYP_CD,    CMCC_BRANCH_CD,    BRND_CD,    MOB_FEE,    TOLL_FEE,    INF_FEE,    CALL_DUR,    DEBET_MOB_DUR,    CALL_CNT,    UP_CALL_FLUX,    DOWN_CALL_FLUX,    INTR_UP_FLUX,    INTR_DOWN_FLUX,    CALL_FREE_DUR,DEDUCTION1,DEDUCTION2 FROM JCFW.TW_CDR_USR_GPRS_BUSI_D_TXT;"
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -rm /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=JM/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -mv  /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_PAQ/branch=JM/month=201704/day=20170403/* /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=JM/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -rm /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_TXT/branch=GMCC/month=201704/day=20170403//*
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -mv /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=ZJ/month=201704/day=20170403/ /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_TXT/branch=GMCC/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day use jcfw;INSERT INTO JCFW.TW_CDR_USR_GPRS_BUSI_D_PAQ PARTITION(branch='ZJ',month=201704,day=20170403) SELECT     DEBET_DT,    CALL_DT,    USR_NBR,    EVENT_FORMAT_YTP_CD,    SRV_TYP_CD,    SUBSRV_TYP_CD,    CX_FILE_IND,    BILL_TYP_CD,    CALL_AREA_CD,  DISC_BASS_PRDCT_CD1,    DISC_BASS_PRDCT_CD2,    XD_TYP_CD,    RESERVE,    RESERVE2,    RESERVE3,    DUR_VOL_TYP_CD,    ROAM_TYP_CD,    EVENT_TYP_CD,    SPECIAL_TYP_CD,    FILE_TYP,    IMEI,    NET_TYP_CD,    A_USR_TYP_CD,    CMCC_BRANCH_CD,    BRND_CD,    MOB_FEE,    TOLL_FEE,    INF_FEE,    CALL_DUR,    DEBET_MOB_DUR,    CALL_CNT,    UP_CALL_FLUX,    DOWN_CALL_FLUX,    INTR_UP_FLUX,    INTR_DOWN_FLUX,    CALL_FREE_DUR,DEDUCTION1,DEDUCTION2 FROM JCFW.TW_CDR_USR_GPRS_BUSI_D_TXT;"
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -rm /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=ZJ/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -mv  /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_PAQ/branch=ZJ/month=201704/day=20170403/* /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=ZJ/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -rm /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_TXT/branch=GMCC/month=201704/day=20170403//*
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -mv /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=SG/month=201704/day=20170403/ /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_TXT/branch=GMCC/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day use jcfw;INSERT INTO JCFW.TW_CDR_USR_GPRS_BUSI_D_PAQ PARTITION(branch='SG',month=201704,day=20170403) SELECT     DEBET_DT,    CALL_DT,    USR_NBR,    EVENT_FORMAT_YTP_CD,    SRV_TYP_CD,    SUBSRV_TYP_CD,    CX_FILE_IND,    BILL_TYP_CD,    CALL_AREA_CD,  DISC_BASS_PRDCT_CD1,    DISC_BASS_PRDCT_CD2,    XD_TYP_CD,    RESERVE,    RESERVE2,    RESERVE3,    DUR_VOL_TYP_CD,    ROAM_TYP_CD,    EVENT_TYP_CD,    SPECIAL_TYP_CD,    FILE_TYP,    IMEI,    NET_TYP_CD,    A_USR_TYP_CD,    CMCC_BRANCH_CD,    BRND_CD,    MOB_FEE,    TOLL_FEE,    INF_FEE,    CALL_DUR,    DEBET_MOB_DUR,    CALL_CNT,    UP_CALL_FLUX,    DOWN_CALL_FLUX,    INTR_UP_FLUX,    INTR_DOWN_FLUX,    CALL_FREE_DUR,DEDUCTION1,DEDUCTION2 FROM JCFW.TW_CDR_USR_GPRS_BUSI_D_TXT;"
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -rm /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=SG/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -mv  /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_PAQ/branch=SG/month=201704/day=20170403/* /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=SG/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -rm /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_TXT/branch=GMCC/month=201704/day=20170403//*
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -mv /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=HY/month=201704/day=20170403/ /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_TXT/branch=GMCC/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day use jcfw;INSERT INTO JCFW.TW_CDR_USR_GPRS_BUSI_D_PAQ PARTITION(branch='HY',month=201704,day=20170403) SELECT     DEBET_DT,    CALL_DT,    USR_NBR,    EVENT_FORMAT_YTP_CD,    SRV_TYP_CD,    SUBSRV_TYP_CD,    CX_FILE_IND,    BILL_TYP_CD,    CALL_AREA_CD,  DISC_BASS_PRDCT_CD1,    DISC_BASS_PRDCT_CD2,    XD_TYP_CD,    RESERVE,    RESERVE2,    RESERVE3,    DUR_VOL_TYP_CD,    ROAM_TYP_CD,    EVENT_TYP_CD,    SPECIAL_TYP_CD,    FILE_TYP,    IMEI,    NET_TYP_CD,    A_USR_TYP_CD,    CMCC_BRANCH_CD,    BRND_CD,    MOB_FEE,    TOLL_FEE,    INF_FEE,    CALL_DUR,    DEBET_MOB_DUR,    CALL_CNT,    UP_CALL_FLUX,    DOWN_CALL_FLUX,    INTR_UP_FLUX,    INTR_DOWN_FLUX,    CALL_FREE_DUR,DEDUCTION1,DEDUCTION2 FROM JCFW.TW_CDR_USR_GPRS_BUSI_D_TXT;"
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -rm /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=HY/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -mv  /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_PAQ/branch=HY/month=201704/day=20170403/* /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=HY/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -rm /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_TXT/branch=GMCC/month=201704/day=20170403//*
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -mv /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=MZ/month=201704/day=20170403/ /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_TXT/branch=GMCC/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day use jcfw;INSERT INTO JCFW.TW_CDR_USR_GPRS_BUSI_D_PAQ PARTITION(branch='MZ',month=201704,day=20170403) SELECT     DEBET_DT,    CALL_DT,    USR_NBR,    EVENT_FORMAT_YTP_CD,    SRV_TYP_CD,    SUBSRV_TYP_CD,    CX_FILE_IND,    BILL_TYP_CD,    CALL_AREA_CD,  DISC_BASS_PRDCT_CD1,    DISC_BASS_PRDCT_CD2,    XD_TYP_CD,    RESERVE,    RESERVE2,    RESERVE3,    DUR_VOL_TYP_CD,    ROAM_TYP_CD,    EVENT_TYP_CD,    SPECIAL_TYP_CD,    FILE_TYP,    IMEI,    NET_TYP_CD,    A_USR_TYP_CD,    CMCC_BRANCH_CD,    BRND_CD,    MOB_FEE,    TOLL_FEE,    INF_FEE,    CALL_DUR,    DEBET_MOB_DUR,    CALL_CNT,    UP_CALL_FLUX,    DOWN_CALL_FLUX,    INTR_UP_FLUX,    INTR_DOWN_FLUX,    CALL_FREE_DUR,DEDUCTION1,DEDUCTION2 FROM JCFW.TW_CDR_USR_GPRS_BUSI_D_TXT;"
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -rm /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=MZ/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -mv  /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_PAQ/branch=MZ/month=201704/day=20170403/* /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=MZ/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -rm /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_TXT/branch=GMCC/month=201704/day=20170403//*
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -mv /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=SW/month=201704/day=20170403/ /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_TXT/branch=GMCC/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day use jcfw;INSERT INTO JCFW.TW_CDR_USR_GPRS_BUSI_D_PAQ PARTITION(branch='SW',month=201704,day=20170403) SELECT     DEBET_DT,    CALL_DT,    USR_NBR,    EVENT_FORMAT_YTP_CD,    SRV_TYP_CD,    SUBSRV_TYP_CD,    CX_FILE_IND,    BILL_TYP_CD,    CALL_AREA_CD,  DISC_BASS_PRDCT_CD1,    DISC_BASS_PRDCT_CD2,    XD_TYP_CD,    RESERVE,    RESERVE2,    RESERVE3,    DUR_VOL_TYP_CD,    ROAM_TYP_CD,    EVENT_TYP_CD,    SPECIAL_TYP_CD,    FILE_TYP,    IMEI,    NET_TYP_CD,    A_USR_TYP_CD,    CMCC_BRANCH_CD,    BRND_CD,    MOB_FEE,    TOLL_FEE,    INF_FEE,    CALL_DUR,    DEBET_MOB_DUR,    CALL_CNT,    UP_CALL_FLUX,    DOWN_CALL_FLUX,    INTR_UP_FLUX,    INTR_DOWN_FLUX,    CALL_FREE_DUR,DEDUCTION1,DEDUCTION2 FROM JCFW.TW_CDR_USR_GPRS_BUSI_D_TXT;"
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -rm /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=SW/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -mv  /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_PAQ/branch=SW/month=201704/day=20170403/* /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=SW/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -rm /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_TXT/branch=GMCC/month=201704/day=20170403//*
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -mv /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=YJ/month=201704/day=20170403/ /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_TXT/branch=GMCC/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day use jcfw;INSERT INTO JCFW.TW_CDR_USR_GPRS_BUSI_D_PAQ PARTITION(branch='YJ',month=201704,day=20170403) SELECT     DEBET_DT,    CALL_DT,    USR_NBR,    EVENT_FORMAT_YTP_CD,    SRV_TYP_CD,    SUBSRV_TYP_CD,    CX_FILE_IND,    BILL_TYP_CD,    CALL_AREA_CD,  DISC_BASS_PRDCT_CD1,    DISC_BASS_PRDCT_CD2,    XD_TYP_CD,    RESERVE,    RESERVE2,    RESERVE3,    DUR_VOL_TYP_CD,    ROAM_TYP_CD,    EVENT_TYP_CD,    SPECIAL_TYP_CD,    FILE_TYP,    IMEI,    NET_TYP_CD,    A_USR_TYP_CD,    CMCC_BRANCH_CD,    BRND_CD,    MOB_FEE,    TOLL_FEE,    INF_FEE,    CALL_DUR,    DEBET_MOB_DUR,    CALL_CNT,    UP_CALL_FLUX,    DOWN_CALL_FLUX,    INTR_UP_FLUX,    INTR_DOWN_FLUX,    CALL_FREE_DUR,DEDUCTION1,DEDUCTION2 FROM JCFW.TW_CDR_USR_GPRS_BUSI_D_TXT;"
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -rm /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=YJ/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -mv  /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_PAQ/branch=YJ/month=201704/day=20170403/* /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=YJ/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -rm /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_TXT/branch=GMCC/month=201704/day=20170403//*
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -mv /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=MM/month=201704/day=20170403/ /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_TXT/branch=GMCC/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day use jcfw;INSERT INTO JCFW.TW_CDR_USR_GPRS_BUSI_D_PAQ PARTITION(branch='MM',month=201704,day=20170403) SELECT     DEBET_DT,    CALL_DT,    USR_NBR,    EVENT_FORMAT_YTP_CD,    SRV_TYP_CD,    SUBSRV_TYP_CD,    CX_FILE_IND,    BILL_TYP_CD,    CALL_AREA_CD,  DISC_BASS_PRDCT_CD1,    DISC_BASS_PRDCT_CD2,    XD_TYP_CD,    RESERVE,    RESERVE2,    RESERVE3,    DUR_VOL_TYP_CD,    ROAM_TYP_CD,    EVENT_TYP_CD,    SPECIAL_TYP_CD,    FILE_TYP,    IMEI,    NET_TYP_CD,    A_USR_TYP_CD,    CMCC_BRANCH_CD,    BRND_CD,    MOB_FEE,    TOLL_FEE,    INF_FEE,    CALL_DUR,    DEBET_MOB_DUR,    CALL_CNT,    UP_CALL_FLUX,    DOWN_CALL_FLUX,    INTR_UP_FLUX,    INTR_DOWN_FLUX,    CALL_FREE_DUR,DEDUCTION1,DEDUCTION2 FROM JCFW.TW_CDR_USR_GPRS_BUSI_D_TXT;"
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -rm /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=MM/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -mv  /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_PAQ/branch=MM/month=201704/day=20170403/* /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=MM/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -rm /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_TXT/branch=GMCC/month=201704/day=20170403//*
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -mv /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=ZQ/month=201704/day=20170403/ /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_TXT/branch=GMCC/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day use jcfw;INSERT INTO JCFW.TW_CDR_USR_GPRS_BUSI_D_PAQ PARTITION(branch='ZQ',month=201704,day=20170403) SELECT     DEBET_DT,    CALL_DT,    USR_NBR,    EVENT_FORMAT_YTP_CD,    SRV_TYP_CD,    SUBSRV_TYP_CD,    CX_FILE_IND,    BILL_TYP_CD,    CALL_AREA_CD,  DISC_BASS_PRDCT_CD1,    DISC_BASS_PRDCT_CD2,    XD_TYP_CD,    RESERVE,    RESERVE2,    RESERVE3,    DUR_VOL_TYP_CD,    ROAM_TYP_CD,    EVENT_TYP_CD,    SPECIAL_TYP_CD,    FILE_TYP,    IMEI,    NET_TYP_CD,    A_USR_TYP_CD,    CMCC_BRANCH_CD,    BRND_CD,    MOB_FEE,    TOLL_FEE,    INF_FEE,    CALL_DUR,    DEBET_MOB_DUR,    CALL_CNT,    UP_CALL_FLUX,    DOWN_CALL_FLUX,    INTR_UP_FLUX,    INTR_DOWN_FLUX,    CALL_FREE_DUR,DEDUCTION1,DEDUCTION2 FROM JCFW.TW_CDR_USR_GPRS_BUSI_D_TXT;"
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -rm /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=ZQ/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -mv  /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_PAQ/branch=ZQ/month=201704/day=20170403/* /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=ZQ/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -rm /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_TXT/branch=GMCC/month=201704/day=20170403//*
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -mv /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=QY/month=201704/day=20170403/ /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_TXT/branch=GMCC/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day use jcfw;INSERT INTO JCFW.TW_CDR_USR_GPRS_BUSI_D_PAQ PARTITION(branch='QY',month=201704,day=20170403) SELECT     DEBET_DT,    CALL_DT,    USR_NBR,    EVENT_FORMAT_YTP_CD,    SRV_TYP_CD,    SUBSRV_TYP_CD,    CX_FILE_IND,    BILL_TYP_CD,    CALL_AREA_CD,  DISC_BASS_PRDCT_CD1,    DISC_BASS_PRDCT_CD2,    XD_TYP_CD,    RESERVE,    RESERVE2,    RESERVE3,    DUR_VOL_TYP_CD,    ROAM_TYP_CD,    EVENT_TYP_CD,    SPECIAL_TYP_CD,    FILE_TYP,    IMEI,    NET_TYP_CD,    A_USR_TYP_CD,    CMCC_BRANCH_CD,    BRND_CD,    MOB_FEE,    TOLL_FEE,    INF_FEE,    CALL_DUR,    DEBET_MOB_DUR,    CALL_CNT,    UP_CALL_FLUX,    DOWN_CALL_FLUX,    INTR_UP_FLUX,    INTR_DOWN_FLUX,    CALL_FREE_DUR,DEDUCTION1,DEDUCTION2 FROM JCFW.TW_CDR_USR_GPRS_BUSI_D_TXT;"
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -rm /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=QY/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -mv  /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_PAQ/branch=QY/month=201704/day=20170403/* /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=QY/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -rm /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_TXT/branch=GMCC/month=201704/day=20170403//*
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -mv /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=CZ/month=201704/day=20170403/ /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_TXT/branch=GMCC/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day use jcfw;INSERT INTO JCFW.TW_CDR_USR_GPRS_BUSI_D_PAQ PARTITION(branch='CZ',month=201704,day=20170403) SELECT     DEBET_DT,    CALL_DT,    USR_NBR,    EVENT_FORMAT_YTP_CD,    SRV_TYP_CD,    SUBSRV_TYP_CD,    CX_FILE_IND,    BILL_TYP_CD,    CALL_AREA_CD,  DISC_BASS_PRDCT_CD1,    DISC_BASS_PRDCT_CD2,    XD_TYP_CD,    RESERVE,    RESERVE2,    RESERVE3,    DUR_VOL_TYP_CD,    ROAM_TYP_CD,    EVENT_TYP_CD,    SPECIAL_TYP_CD,    FILE_TYP,    IMEI,    NET_TYP_CD,    A_USR_TYP_CD,    CMCC_BRANCH_CD,    BRND_CD,    MOB_FEE,    TOLL_FEE,    INF_FEE,    CALL_DUR,    DEBET_MOB_DUR,    CALL_CNT,    UP_CALL_FLUX,    DOWN_CALL_FLUX,    INTR_UP_FLUX,    INTR_DOWN_FLUX,    CALL_FREE_DUR,DEDUCTION1,DEDUCTION2 FROM JCFW.TW_CDR_USR_GPRS_BUSI_D_TXT;"
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -rm /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=CZ/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -mv  /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_PAQ/branch=CZ/month=201704/day=20170403/* /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=CZ/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -rm /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_TXT/branch=GMCC/month=201704/day=20170403//*
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -mv /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=JY/month=201704/day=20170403/ /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_TXT/branch=GMCC/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day use jcfw;INSERT INTO JCFW.TW_CDR_USR_GPRS_BUSI_D_PAQ PARTITION(branch='JY',month=201704,day=20170403) SELECT     DEBET_DT,    CALL_DT,    USR_NBR,    EVENT_FORMAT_YTP_CD,    SRV_TYP_CD,    SUBSRV_TYP_CD,    CX_FILE_IND,    BILL_TYP_CD,    CALL_AREA_CD,  DISC_BASS_PRDCT_CD1,    DISC_BASS_PRDCT_CD2,    XD_TYP_CD,    RESERVE,    RESERVE2,    RESERVE3,    DUR_VOL_TYP_CD,    ROAM_TYP_CD,    EVENT_TYP_CD,    SPECIAL_TYP_CD,    FILE_TYP,    IMEI,    NET_TYP_CD,    A_USR_TYP_CD,    CMCC_BRANCH_CD,    BRND_CD,    MOB_FEE,    TOLL_FEE,    INF_FEE,    CALL_DUR,    DEBET_MOB_DUR,    CALL_CNT,    UP_CALL_FLUX,    DOWN_CALL_FLUX,    INTR_UP_FLUX,    INTR_DOWN_FLUX,    CALL_FREE_DUR,DEDUCTION1,DEDUCTION2 FROM JCFW.TW_CDR_USR_GPRS_BUSI_D_TXT;"
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -rm /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=JY/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -mv  /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_PAQ/branch=JY/month=201704/day=20170403/* /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=JY/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -rm /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_TXT/branch=GMCC/month=201704/day=20170403//*
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -mv /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=YF/month=201704/day=20170403/ /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_TXT/branch=GMCC/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day use jcfw;INSERT INTO JCFW.TW_CDR_USR_GPRS_BUSI_D_PAQ PARTITION(branch='YF',month=201704,day=20170403) SELECT     DEBET_DT,    CALL_DT,    USR_NBR,    EVENT_FORMAT_YTP_CD,    SRV_TYP_CD,    SUBSRV_TYP_CD,    CX_FILE_IND,    BILL_TYP_CD,    CALL_AREA_CD,  DISC_BASS_PRDCT_CD1,    DISC_BASS_PRDCT_CD2,    XD_TYP_CD,    RESERVE,    RESERVE2,    RESERVE3,    DUR_VOL_TYP_CD,    ROAM_TYP_CD,    EVENT_TYP_CD,    SPECIAL_TYP_CD,    FILE_TYP,    IMEI,    NET_TYP_CD,    A_USR_TYP_CD,    CMCC_BRANCH_CD,    BRND_CD,    MOB_FEE,    TOLL_FEE,    INF_FEE,    CALL_DUR,    DEBET_MOB_DUR,    CALL_CNT,    UP_CALL_FLUX,    DOWN_CALL_FLUX,    INTR_UP_FLUX,    INTR_DOWN_FLUX,    CALL_FREE_DUR,DEDUCTION1,DEDUCTION2 FROM JCFW.TW_CDR_USR_GPRS_BUSI_D_TXT;"
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -rm /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=YF/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -mv  /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_PAQ/branch=YF/month=201704/day=20170403/* /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=YF/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -rm /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_TXT/branch=GMCC/month=201704/day=20170403//*
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -mv /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=OTH/month=201704/day=20170403/ /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_TXT/branch=GMCC/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day use jcfw;INSERT INTO JCFW.TW_CDR_USR_GPRS_BUSI_D_PAQ PARTITION(branch='OTH',month=201704,day=20170403) SELECT     DEBET_DT,    CALL_DT,    USR_NBR,    EVENT_FORMAT_YTP_CD,    SRV_TYP_CD,    SUBSRV_TYP_CD,    CX_FILE_IND,    BILL_TYP_CD,    CALL_AREA_CD,  DISC_BASS_PRDCT_CD1,    DISC_BASS_PRDCT_CD2,    XD_TYP_CD,    RESERVE,    RESERVE2,    RESERVE3,    DUR_VOL_TYP_CD,    ROAM_TYP_CD,    EVENT_TYP_CD,    SPECIAL_TYP_CD,    FILE_TYP,    IMEI,    NET_TYP_CD,    A_USR_TYP_CD,    CMCC_BRANCH_CD,    BRND_CD,    MOB_FEE,    TOLL_FEE,    INF_FEE,    CALL_DUR,    DEBET_MOB_DUR,    CALL_CNT,    UP_CALL_FLUX,    DOWN_CALL_FLUX,    INTR_UP_FLUX,    INTR_DOWN_FLUX,    CALL_FREE_DUR,DEDUCTION1,DEDUCTION2 FROM JCFW.TW_CDR_USR_GPRS_BUSI_D_TXT;"
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -rm /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=OTH/month=201704/day=20170403/
 perl ~schadm/dssprog/bin/remote_cli.pl bd_day hadoop fs -mv  /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D_PAQ/branch=OTH/month=201704/day=20170403/* /tenant/BIGDATA/JCFW/BZMX/DAY/EDS/TW_CDR_USR_GPRS_BUSI_D/branch=OTH/month=201704/day=20170403/

